### ISSUE TITLE
 Neighborhoods:  Are campsite reports and responses (sweeps) consistent over time? Compare to estimated number of campsites per week.

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/civic#100]
# Story Card Request

**Project: Neighborhoods**
**Card Title: Estimates of the magnitude/# of people who were swept by police**

## Description / Wireframe

The idea is to relate the number campsite reports per week with the estimated number of unique campsites per week, and the campsite sweeps data by week on a line plot. 

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
This comparison is important for understanding how reports of campsites are being responded to by the police, and what relationship there is to the quantity of reports & the response. 

## Data Details (APIs)

datasets:
- campsite reports
- campsite sweeps
- estimated numbers of unique campsites per week

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by christinatommeraasen** [comment]
Is it possible to do a 3D rendering of the magnitude of the population moving around the city over time. The magnitude of resources that the police are putting into this initiative.

**Comment by mckinneybock** [comment]
Hi @jaronheard - We caught an issue with plotting these three lines by month, as the third line that we added can't be aggregated by month (it's meaningless to talk about unique campsites per month). We will need the granularity of this plot to be by week, as it was originally stated. I'll come talk with you right now. Thanks for this! (and great catch, @hassanshamim).

**Comment by hassanshamim** [comment]
This is complete now.  Should be pretty straightforward (line?) graph.

API endpoint - http://service.civicpdx.org/neighborhood-development/api/camp_weekly_aggregates?limit=130

data points are
- `date` start day of each week (Mondays if you're curious)
- `report_count` number of reports received from the public during that week
- `sweep_count` number of campsite sweeps that ocurred during that week
- `unique_sites_estimate` the estimated number of unique campsites reported that week (from ppd not us)

It's sorted ascending by date.  You'll see some `null` values for `sweep_count` and `unique_sites_estimate` as data wasn't being published for those datapoints at that time.  Not sure if you should just truncate any weeks that don't have all 3 or if that's okay.

**Comment by mckinneybock** [comment]
Hi @jaronheard! I wanted to check in and see if there is hope for this card to be in production for Demo day tomorrow! You all are amazing :)
