### ISSUE TITLE
WIP -> Housing Policy Card

### ISSUE THREAD

**Issue by danmelton** [hackoregon/civic#101]
# Story Card Request

**Project: Rental Affordability**
**Card Title: Housing Policy**

## Description / Wireframe

<img width="557" alt="housing_card_wireframes" src="https://user-images.githubusercontent.com/99731/39678060-8ccca540-513a-11e8-9861-59dcdf4682d5.png">

This card shows an affordable housing policy with plain language on what it means, an audio clip, links, and which governments in a region implement it.

https://www.figma.com/proto/Sx4NhVdMgKdKKjPV6IEWIX7i/Housing-Card-Wireframes?node-id=201%3A80&scaling=contain

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)
We have a spreadsheet of the inventory so far at:
https://docs.google.com/spreadsheets/d/1nc_luva5sNZI2X5bIgjg_jPhErbVspJ933AFAnNPYRw/edit#gid=0

### How did we calculate this
We interviewed local governments and researched the policies.

**Comment by jaronheard** [comment]
The concept of this card is really cool, and I'm excited to see it take shape.

From a data visualization perspective - one of the things that I'd like to see is some sort of visual grouping of the different levels of government - state, county, city. Other than that, I think from a data visualization perspective, I'm ready to approve it.

If we think of this in the context of our card designs - I'm imaging that this could fit into this style:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/7065695/40084438-fd8e42ee-584b-11e8-8f7e-9718ebb6a210.png">

@karieleana @sixfoot6 would love your feedback on this card from a design perspective.

**Comment by danmelton** [comment]
@jaronheard we were thinking this card https://github.com/hackoregon/civic/issues/106 would capture the data viz aspects of which governments have implemented which policies.

**Comment by jaronheard** [comment]
@danmelton That makes sense - I guess I was thinking in terms of just information design, that to have some visual indicator of the level of government would be useful for the governments shown in the top right corner. Could be just grouping the text a little differently, adding a label, or something else.

**Comment by karieleana** [comment]
This wireframe is super helpful!
Questions:
- What are the top/bottom arrows doing?
- What is the extent of the "Categories" ie purpose? (clarification - this seems relevant just trying to understand all uses of content)

**Comment by jaronheard** [comment]
@karieleana could you whip up a wireframe for this? @sixfoot6

**Comment by karieleana** [comment]
<img width="1004" alt="screen shot 2018-06-04 at 4 36 02 pm" src="https://user-images.githubusercontent.com/22756837/40947044-72cf4dc2-6815-11e8-8a66-c886eb554b43.png">
3 interaction step wireframe for this card

**Comment by karieleana** [comment]
Interaction 1: Select a Policy

<img width="592" alt="screen shot 2018-06-04 at 4 37 09 pm" src="https://user-images.githubusercontent.com/22756837/40947062-a1db403a-6815-11e8-9802-cf35261f3145.png">

**Comment by karieleana** [comment]
Interaction 2: Once a policy has been selected, choose a government for information about that policy

<img width="587" alt="screen shot 2018-06-04 at 4 38 33 pm" src="https://user-images.githubusercontent.com/22756837/40947087-c085d8d8-6815-11e8-8c67-a4757deefc95.png">

**Comment by karieleana** [comment]
Step 3: Information about Policy is shown

<img width="590" alt="screen shot 2018-06-04 at 4 39 09 pm" src="https://user-images.githubusercontent.com/22756837/40947109-db9102ec-6815-11e8-8c82-f0185281fb26.png">

**Comment by karieleana** [comment]
Here is a another version without the side navigation that might be easier to code
<img width="586" alt="screen shot 2018-06-05 at 5 11 46 pm" src="https://user-images.githubusercontent.com/22756837/41009134-f61c4ab2-68e3-11e8-9a28-71f1330f24e1.png">

**Comment by jaronheard** [comment]
#391 implemented
