### ISSUE TITLE
Explore Urban Campsite Sweeps by Neighborhood / Human Impact

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/civic#102]
# Story Card Request

**Project: Neighborhoods**
**Card Title: Explore Urban Campsite Sweeps by Neighborhood**

## Description / Wireframe

Potentially contains an animation by week or month aggregate, that flashes through all available sweeps data from 10/2016-present. (April 2018, as May 2018 is incomplete).

Also ideally an interactive map of campsite sweeps (by point), with neighborhood boundaries, to illustrate how many sweeps there have been. This will help show where sweeps are happening around the city; it will be combined with descriptive statistics (means) on estimated numbers of people per campsite to estimate the number of people affected per week in the Expanded Content.

Related to Issue #100 

## Data Visualization / Design Concerns
Animation over time is very important
Second is an interactive component, so users can explore their neighborhoods & areas of Portland over time.

## Context
This is a pretty critical comparison to make to better understand how frequent the campsite sweeps are occurring, and what response is to the local un-housed population.

## Data Details (APIs)

datasets:

- campsite sweeps

Data will be located in the Neighborhoods API.

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by christinatommeraasen** [comment]
Neighborhood map on one side and a line graph on the other.

**Comment by jaronheard** [comment]
This is in the Civic Sandbox
