### ISSUE TITLE
Issue with filters

### ISSUE THREAD

**Issue by tml3** [hackoregon/civic#1022]
# Story Card Improvement
Tried to filter data viz by category and geography, but the default appears to be disaster data rather than the Portland race data.  I can scroll down to access it from the menu, but  it doesn't pop to the top when the filter is utilized.

**How could this card be better?**

Let us know about your experience and how it could be better -- whether it's a bug, or an idea for improvement. Thanks for helping make CIVIC better, together! 🙌

**Additional context**

Add any other context or screenshots

**Comment by jaronheard** [comment]
For this issue to be resolved, the following tests should be met:

The table below shows categories of tags (first row), and tag in those categories.

| topic | location | visualization |
| --- | --- | --- | 
| disaster resilience | nationwide | chart | 
| race | oregon | infographic | 
| transportation | portland | map |

Tests:

| selected tags | matching criteria |
| --- | --- |
| race | race |
| race, transportation | race OR transportation |
| race, portland | race AND portland | 
| race, transportation, portland | (race OR transportation) AND portland |
| race, transportation, portland, oregon, chart, infographic | (race OR transportation) AND (portland OR oregon) AND (chart OR infographic)
| race, portland, chart | race AND portland AND chart |

**Comment by cosmolightfoot** [comment]
These are excellent tables, I have a solid understanding of how to carry out this functionality improvement. OR matching within a category, as well as AND matching between categories. 

I have a question regarding cards that contain multiple tags from the same category. For example several cards contain both "Race" and "Transportation". If ONLY the "Race" filter is selected should cards containing "Race" AND "Transportation" be showing, or should it only display cards that have "Race" as the exclusive tag from the "Topics" category.

**Comment by jaronheard** [comment]
> For example several cards contain both "Race" and "Transportation". If ONLY the "Race" filter is selected should **cards containing "Race" AND "Transportation" be showing**, or should it only display cards that have "Race" as the exclusive tag from the "Topics" category.

Bolded the correct answer. The "matching criteria" in the table above means that the tags list contains a set of tags that matches the criteria.

**Comment by cosmolightfoot** [comment]
Resolved by #1146
