### ISSUE TITLE
Hold - Neighborhoods: Demographics of reports & who is reporting

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/civic#104]
# Story Card Request

**Project: Neighborhoods**
**Card Title: Campsite Reports & income levels of a community**

## Description / Wireframe

Are the economically privileged the ones reporting & getting responses? Looking at which neighborhoods the are actively reporting crime; actively reporting public camping, etc. A map visualization of income demographics vs. crime, or campsite reports (aggregated by neighborhood and/or census block).

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
The question of who is speaking up and having their voices represented in the city is important (campsite reports, crime reports, etc). Exploring this visualization (the ones we have currently are crime and campsites) will help shed light on whose voices are represented in these reporting systems.

## Data Details (APIs)

datasets:
- campsite reports (in progress)
- crime reports

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by LMorgan-veraly** [comment]
Katy, you mention data sets but need specifics about which attributes need to be accessible in the API. @accua @hassanshamim - fyi and any other input?

**Comment by mckinneybock** [comment]
Hi Lynn, This analysis is still in progress and at this point is a lower priority. I'll catch up on Thursday with updates to story cards.

**Comment by mckinneybock** [comment]
Not going in!
