### ISSUE TITLE
Mobile landing page improvements

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#1058]
### What

Landing page needs to be improved for mobile

### Why

People come to check out CIVIC Platform on their phones

### When

ASAP, but not time sensitive

- [x] Text overlap
- [x] Weird button spacing
- [ ] Tab group mobile view
- [x] Add spacing between contact us email and creative and tech HQ

Screens below from iPhone SE:

![UNADJUSTEDNONRAW_thumb_3068](https://user-images.githubusercontent.com/7065695/65583972-06b07880-df35-11e9-8859-3a49fd691f72.jpg)
![UNADJUSTEDNONRAW_thumb_306b](https://user-images.githubusercontent.com/7065695/65583973-06b07880-df35-11e9-93e0-034ae2febc96.jpg)
![UNADJUSTEDNONRAW_thumb_305c](https://user-images.githubusercontent.com/7065695/65583974-06b07880-df35-11e9-9a14-e6d267f29d8c.jpg)
![UNADJUSTEDNONRAW_thumb_3060](https://user-images.githubusercontent.com/7065695/65583975-06b07880-df35-11e9-8dbf-5ac201454b8a.jpg)
![UNADJUSTEDNONRAW_thumb_305e](https://user-images.githubusercontent.com/7065695/65583976-06b07880-df35-11e9-9092-bee00a2d0bc4.jpg)

**Comment by Dianna** [comment]
Fixed in #1115
