### ISSUE TITLE
Add tooltip to ScreenGridMap

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#1063]
### What

Add a tooltip to ScreenGridMap

### Why

Needed for http://civicplatform.org/cards/earthquake-damage-estimates-for-buildings-in-tillamook-county

From this list of items to improve before sharing with FEMA.
https://gist.github.com/karenng-civicsoftware/a75a67bbd435544da846d14fcf4d1817

### When

ASAP

**Comment by karenng-civicsoftware** [comment]
@jaronheard we may still want this. But we have to be careful what information we display on the tooltip. Let me know how I can help to add this change?

**Comment by jaronheard** [comment]
@karenng Would you classify this as “release blocking” for sharing with FEMA?

We need to implement the tooltip at the component level first, and I’m not sure how involved it will be.

**Comment by jaronheard** [comment]
Resolved
