### ISSUE TITLE
ButtonNew text disappears on mouseover when provided link

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#1068]
## Description

Mouse-over the button
<img width="735" alt="image" src="https://user-images.githubusercontent.com/7065695/65747950-99792080-e0b7-11e9-8ff8-dbeeaac08fed.png">

### Steps to reproduce

ButtonNew with an href prop. See "help make this better" section of any card (e.g. http://civicplatform.org/cards/demo-card)

```js
            <ButtonNew
              href="https://civicsoftwarefoundation.org/#volunteers"
              label="Get Involved!"
            />
```

### Expected result

Should be able to read the text

### Actual result

Text same color as button

### Environment

Production environment

**Comment by amoury** [comment]
Hey @jaronheard, may I take up this issue? If no one else is working on it, please assign it to me. Thanks

**Comment by jaronheard** [comment]
Hi @amoury! Thanks for raising your hand for this issue, I've assigned the issue to you.

Please let me know if you have any questions!

**Comment by amoury** [comment]
Thanks @jaronheard ... will do!

**Comment by jaronheard** [comment]
Hi @amoury -- happy to assist if you ran into any issues here, or if you've moved on to other things, let me know and I'll un-assign you

**Comment by meamitacharya** [comment]
Hi, @jaronheard is this issue still open???

**Comment by jaronheard** [comment]
Hi @meamitacharya, looks like it's been resolved! Thanks for catching this, much appreciated!
