### ISSUE TITLE
Campaign Finance Dashboard: Money Raised

### ISSUE THREAD

**Issue by dhgwilliam** [hackoregon/civic#108]
# Story Card Request

**Project:** Campaign Finance/Elections
**Card Title:** Total Money Raised

## Description / Wireframe

This card is a straightforward bar chart with a date range selector. We'd like to be able to provide some preset duration options to the user (30 days, 90 days, 1 year) while still allowing flexibility to "zoom" in or out of arbitrary date ranges.

Data represented will be donation "events" that have a date and an amount. Bars will be sum of all donations over the date sub-range... We don't have a specific number of bars identified yet.

![screenshot 2018-05-06 at 4 05 41 pm](https://user-images.githubusercontent.com/36499/39678771-7953048e-5147-11e8-8c34-6794ad29e944.png)

[Figma](https://www.figma.com/file/VfgCakKOUMTxTVjGfn5xywV7/Elections-v1)

## Data Visualization / Design Concerns

It's possible a line chart would be preferred over a bar chart. We may also want to stick with a bar chart and use stacking to represent the "character" of the donations (corporate, union, grassroots, etc). I will lock this down with the team and report back.

## Context

This is one of the building blocks of our PAC "view" and represents a fundamental unit of analysis.

## Data Details (APIs)

API is in flight

**Comment by dhgwilliam** [comment]
I think it's fine if it's not infinity flexible, but we'd like to be able to at least represent multiple time frames. if we were able to identify, e.g., a set of specific time frames that a user could toggle between (e.g. Election Cycle 2016, Election Cycle 2018, etc), would that simplify things for the frontend team?

**Comment by mbodenator** [comment]
Data details: for single selected election cycle: /local-elections/totalcontributionsmonthly/
for multiple election cycle selected: /local-elections/totalcontributionsyearly/

**Comment by Dianna** [comment]
@jaronheard https://github.com/orgs/hackoregon/projects/9

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
