### ISSUE TITLE
Campaign Finance: Top Donors to Committee

### ISSUE THREAD

**Issue by dhgwilliam** [hackoregon/civic#109]
# Story Card Request

**Project:** Campaign Finance/Elections
**Card Title:** Top 5 Donors

## Description / Wireframe

![screenshot 2018-05-06 at 4 21 07 pm](https://user-images.githubusercontent.com/36499/39678859-8fb838fa-5149-11e8-842a-ef210d176b39.png)

Bar chart representing the total donations in $ for each of the top 5 donors. We very likely want to call out or color code these based on donor category: corporate (with possible industry information), union, etc.

## Data Visualization / Design Concerns
I'm not sure we'll want to have a legend for every card in the collection, but we may need to in order for them to make sense in a solo context (unless we can put the info in a tooltip, maybe?)

**Comment by jaronheard** [comment]
I like the horizontal bar chart for this. Making a connection based on color may be effective, or perhaps this might be a good use of an icon?

**Comment by jaronheard** [comment]
This isn't being used in the dashboard, and doesn't have API information, so closing this issue.

**Comment by grantholly** [comment]
Data details: /local-elections/committeecontributors/
