### ISSUE TITLE
Campaign Finance Dashboard: Contributor Breakdown

### ISSUE THREAD

**Issue by dhgwilliam** [hackoregon/civic#110]
# Story Card Request

**Project:** Campaign Finance
**Card Title:** Donations by Category

## Description / Wireframe

![screenshot 2018-05-06 at 4 30 23 pm](https://user-images.githubusercontent.com/36499/39678945-44430fec-514b-11e8-96a7-d2d960b52d9a.png)

Donut chart representing the breakdown of total $ donated by each of the donor categories: corporate, union, grassroots, out-of-state, etc. We will lock down the actual categories as soon as possible.

## Data Visualization / Design Concerns
I believe this should be total dollar amount (% of donations as opposed to % of donors).

## Context
Representing who and "where" the money that supports a candidate comes from gives a user some signals about which political constituencies feel aligned with the candidate
 
### See the source

ORestar

**Comment by jaronheard** [comment]
How many categories are there for this? If there are more than 3 or 4 categories, I would recommend using our basic bar chart component instead.

**Comment by jaronheard** [comment]
Talking to @dhgwilliam, the part of the whole is an important part of this visualization. Also - being able to make comparisons in a small multiples context is important to this component.

**Comment by dhgwilliam** [comment]
This is an example of what i might be interested in:
![image](https://user-images.githubusercontent.com/36499/39737367-85e9f304-5239-11e8-9a11-7cafaeeeea0b.png)
or
![image](https://user-images.githubusercontent.com/36499/39737432-e1ad99ca-5239-11e8-8ecd-fb5bf13e9edb.png)

at least visually

**Comment by mbodenator** [comment]
Data Details: /local-elections/totalcontributions

**Comment by Dianna** [comment]
@jaronheard https://github.com/orgs/hackoregon/projects/9

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
