### ISSUE TITLE
Campaign Finance: Donors by location

### ISSUE THREAD

**Issue by dhgwilliam** [hackoregon/civic#111]
# Story Card Request

**Project:** Campaign Finance
**Card Title:** Donors by location

## Description / Wireframe

Map that represents # of donors/total $ of donations by zip code. I will have to talk to the team and see which we think is more communicative.

## Data Visualization / Design Concerns
We will need to figure out a way to represent both in-state and out-of-state donations

## Context
For many PACs/candidates, it will be important to show whether funding is primarily local to the district or not.
 
### How did we calculate this
Donations have zip codes attached.

### See the source
ORestar

**Comment by jaronheard** [comment]
I'm thinking this may not need to be a map - it might make sense to break down into categories:
local
in-state
out-of-state

But it could also work on a map.

**Comment by jaronheard** [comment]
We're splitting in-state and out of state donations on the dashboard, but not showing them on a map. Closing this issue.
