### ISSUE TITLE
Campaign Finance Dashboard: Spending by Category

### ISSUE THREAD

**Issue by dhgwilliam** [hackoregon/civic#112]
# Story Card Request

**Project:** Campaign Finance
**Card Title:** Expenditures by Category

## Description / Wireframe

![screenshot 2018-05-06 at 4 59 47 pm](https://user-images.githubusercontent.com/36499/39679237-005afdae-514f-11e8-80e7-f1e0437eea0f.png)

ORestar categorizes PAC expenditures as, e.g., Media, Transportation, Payroll, etc. We may further break these categories down or combine them in the process of EDA.

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
Where the money goes should give our users a good idea of what values/value a PAC has (does it funnel money to other PACs? is it spending a lot on media in support of a candidate/issue?), as well as giving us an opportunity to pinpoint the average cost of voter acquisition somewhere down the line.

## Data Details (APIs)

In flight

### How did we calculate this
directly from ORestar

### See the source
ORestar

**Comment by jaronheard** [comment]
This looks like a great use of our basic bar chart component. If we have more than 5 categories, we may want to use our horizontal bar chart component.

📊☑️

**Comment by mbodenator** [comment]
Data Details: /local-elections/spendingbreakdown

**Comment by Dianna** [comment]
@jaronheard https://github.com/orgs/hackoregon/projects/9

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
