### ISSUE TITLE
Document package contribution workflow

### ISSUE THREAD

**Issue by clemf** [hackoregon/civic#12]
How to work on individual packages within the monorepo?

**Comment by MikeTheCanuck** [comment]
Howdy @clemf - could you take a look at [the current README](https://github.com/hackoregon/civic/blob/059146947991fc5d42149b3104200491255f3740/README.md) and comment whether this concern is adequately addressed for you?

**Comment by clemf** [comment]
@MikeTheCanuck Looks great!
