### ISSUE TITLE
Share functionality should always copy https by default

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#1204]
## Description

If you click the embed option under share link when you're on a `http://` connection, it will copy an embed link with `http://`, which will give you an insecure connection error if you try to embed it somewhere else.

All share links for cards should be `https://` by default

### Steps to reproduce

http://civicplatform.org/cards/demo-card > then click share link to get https://civicplatform.org/cards/demo-card/embed

### Expected result

Should copy link with `https`

### Actual result

Copies link with `http`

### Environment

Production

**Comment by yden063** [comment]
Hello Jaron, can you assign it to me? I would like to work on it, thanks!

**Comment by jaronheard** [comment]
@yden063 Assigned! Let me know if you have any questions.

**Comment by yden063** [comment]
Thanks Jaron, I am going to get familiar with the project first, and then start the coding.
