### ISSUE TITLE
Add accessibility features to components

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#122]
Once we have a11y accessibility testing in our storybook #82 , the next step is to work in the components and add accessibility features. For this issue, just add accessibility in a way that doesn't change the functionality or design of the components.

Also, for accessibility issues that would require design changes, note what changes would be required.

**Comment by jaronheard** [comment]
Welcome
Editable UI components
Header
Button
StoryLink
StoryFooter
StoryCard
Pie
HorizontalBarChart
Line Chart
Placeholder
Sankey
Slider
Dropdown

**Comment by jasonleonhard** [comment]
I believe Daron and I have completed this, let me know if there is anything else.
