### ISSUE TITLE
Neighborhood - Civic Sandbox - Map Layer -  Green Spaces

### ISSUE THREAD

**Issue by LMorgan-veraly** [hackoregon/civic#124]
# Story Card Request

**Project: Neighborhood - Civic Sandbox**
**Card Title: Map Layer -  Green Spaces**

## Description / Wireframe
Map Layer that allows for display on or off of data from the Neighborhood API related to Green Spaces.

> Include a detailed description and/or image that describes your story or visualization using
> the data described below. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> If you have a wireframe, include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

## Data Visualization / Design Concerns

User should be able to toggle the display of various data fields.

> If you have specific design or data visualization concerns, mention them here

## Context
Map Layer for the Interactive Map and the multi-dimensional display of data by neighborhood or other boundary file.

> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)
dataset: street_trees - geometry: type:Point, coordinates; properties: Common
dataset: parks_trails - geometry: type:LineString, coordinates; properties: surface
dataset: community_gardens - geometry: type:Polygons, coordinates; properties: SITENAME, Status, Plotsperga
dataset: parks - geometry: type:Polygons, coordinates; properties: NAME

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## About this data
Green space related data.

### How did we calculate this
Nothing to be calculated just to be availale to be displayed

>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data
source data from the neighborhood development inventory documentation

**Comment by jaronheard** [comment]
Closing for now, I think we may have a different process for this, but we may reopen and this is a good reference.
