### ISSUE TITLE
 WIP >Disaster : Card 6 Personalized Action Items

### ISSUE THREAD

**Issue by maryannet** [hackoregon/civic#128]
# Story Card Request

**Project:** Disaster Resilience
**Card Title:** Action Items
Card 6 Personalized Action Items
## Description / Wireframe
This card will help users to develop a personalized list of “next steps” to prepare for a disaster.  Users will answer approximately 8 - 10 questions (y/n) and receive 3 key recommendations of their preparation priorities based on their answer.
wireframe landing page Intro start survey
Each description comes up, then you click yes or no, then it moves on to the next description.

Each question will come up individually, and a response will be provided before going on to the next questions.  For example:

Does your family have an action plan in response to a disaster?
If no: A family plan should include a meeting place, travel plans from work and school, and include day and night contingencies.
If yes: Good for you!  Don’t forget that a family plan should include a meeting place, travel plans from work and school, and include day and night contingencies.  Discuss your family plan regularly and incorporate any changes.

Each card should have a “Next” and “Back” button so users can move forward or go back and change their answers.
add wire frame, do you want radio button or check box?
Do all question have to have answer?
After going through all the questions, the user receives a score on the final summary page with a total of “yes” answers:
Congratulations!  You’ve completed 3 of 10 priority preparation tasks.  Your next steps should be:
wireframe congrat then next steps 
The personalized recommendations of next steps should be based on the first three “no” answers in the survey.  The questions will be given in order of importance, so the first three nos should be the top three priority next steps.  The final summary page will include more detailed information on that question and link(s) for more information.

After the three priority recommendations, there will be a link to “see more preparation tips” where the detailed information for all the questions will be provided.
wire frame ending page with links
Pasting in Erin’s questions 
1. Does your family have an action plan in response to a disaster?  
A plan should include a family meeting place, a travel plan from work and school, and include day and night contingencies.  

2. Do you know at least 3 people who live within 3 blocks of you?
Knowing your neighbors makes your neighborhood safer and more resilient. Since first responders will be overwhelmed, neighbors will likely be the first ones to help victims. 

3. Do you have a 3-day evacuation kit?  It should include 3 days of supplies, including water, for each member of your family.
A 3 day evacuation kit will provide supplies for your family in the event that you cannot remain in your home.  It should include water, food, radio, basic first aid, and a thermal blanket.  

4. Do you have a 2-bucket toilet system?
After a major disaster, water and sewer infrastructure will not be functional for some time.  A 2-bucket toilet system keeps human waste sterile and secure and populations healthy.

5. Do you have 2 weeks of food and water for your household?
Water supplies for 2 weeks will require 14 gallons of water per person in your household.  Food supplies can include all kinds of non-perishable items, such as canned food, freeze-dried, and MREs.  

6. Is the interior of your house earthquake-proofed?
Earthquake proofing your house should include strapping tall, heavy furniture to the wall and moving heavy mirrors or art pieces away from beds and desks.

7. Do have a communication plan in the event of a disaster?
It is likely that cell phones will not work for some time after a disaster.  Walkie-talkies and hand-held radios will be a good way to communicate.  The city of Portland has a plan for radio communications across the city called BEECN.

8. Have you considered becoming a neighborhood resilience champion?
Neighborhood Emergency Teams (NETs) are Portland residents trained by PBEM and Portland Fire & Rescue to provide emergency disaster assistance within their own neighborhoods. NET members are trained to save lives and property until professional responders can arrive. These volunteers are specially trained to help others without putting themselves in harm’s way. 

Summary Information: More detail about the first 3 “no” responses
Plan
Knowing Neighbors
3 day kit
2-bucket toilet
Food and water
Interior
BEECN
NET

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

## Description / Wireframe

> Include a detailed description and/or image that describes your story or visualization using
> the data described below. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

![my plan card _6 - 1 of 2](https://user-images.githubusercontent.com/17058320/40323675-fcea1eaa-5cea-11e8-9ebc-083ebe03c584.png)

![my plan card _6 - 2 of 2](https://user-images.githubusercontent.com/17058320/40323679-021d868c-5ceb-11e8-8ef4-b1d50aae521d.png)

> Also include a link to a Figma design if you have one.

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by PoeStewart** [comment]
See new version
