### ISSUE TITLE
Fix Collections Menu Transition Animation

### ISSUE THREAD

**Issue by danieltomasku** [hackoregon/civic#133]
When you click to close the Collections NavSubMenu, there's a little white box that lingers a couple of milliseconds after the main container disappears. The component lives under Navigation > NavSubMenu.

<img width="496" alt="screen shot 2018-05-14 at 6 41 26 pm" src="https://user-images.githubusercontent.com/14880569/40031915-cdc19a98-57a6-11e8-95d5-d96bd7e5cabf.png">

**Comment by danieltomasku** [comment]
Bonus points if you can get the NavSubMenu to close when clicking anywhere outside the menu container.

**Comment by jaronheard** [comment]
#162 addressed. Bonus points above is issue #146.
