### ISSUE TITLE
Add deck.gl HexagonLayer component on top of BaseMap

### ISSUE THREAD

**Issue by mendozaline** [hackoregon/civic#136]
A new deck.gl HexagonLayer component needs to be created.

This should layer on top of our existing BaseMap component.

Todo:
- [x] Add the HexagonLayer component
- [x] Add unit tests
- [x] Update the HexagonLayer story

**Comment by jasonleonhard** [comment]
Attempted to self assign this after speaking with David Mendoza, but my permissions do not appear to be working yet. Will be working on this.

**Comment by jaronheard** [comment]
Looks like this is almost done, but the story could still use updates. Currently is throwing an error in the storybook.

**Comment by jasonleonhard** [comment]
Hi Jaron, the only errors I am seeing in my console are from other components, are you still seeing other errors? If not I believe this issue is ready to close. I have a pull request in that finishes up the tooltip too. https://github.com/hackoregon/civic/pull/255

**Comment by jaronheard** [comment]
#209 addressed
