### ISSUE TITLE
Bug (2017 package) - are app routes working as intended?

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic#145]
## Potential bug

Observed in the just-launched 2017.civicpdx.org containerized Express site.

From what I can infer from [index.js](https://github.com/hackoregon/civic/blob/master/packages/2017/src/index.js#L103), the five 2017 apps should respond to the following URLs:
http://2017.civicpdx.org/budget
http://2017.civicpdx.org/emergency
http://2017.civicpdx.org/housing
http://2017.civicpdx.org/homelessness
http://2017.civicpdx.org/transportation

Of those apps, none of them render the expected homepage:
- Budget:  **Bad Request (400)** error - which may be coming from AWS ALB
- Emergency: **Bad Request (400)** error - which may be coming from AWS ALB
- Homelessness:  **DisallowedHost** error - which is a Django error, not an Express or React error
- Housing: **DisallowedHost** error - which is a Django error, not an Express or React error
- Transportation:  **Bad Request (400)** error - which may be coming from AWS ALB

I'm not 100% convinced this is an issue with the React `2017` package - it could also be something wonky in the Route 53 or ALB configuration.

However, http://2017.civicpdx.org/about seems to render fine.

(And http://2017.civicpdx.org/ still renders as the dummy "Civic Lab" placeholder, which is odd because it isn't even listed among the `routes`.)

**Comment by DingoEatingFuzz** [comment]
Just checked all five of those links and they work.
