### ISSUE TITLE
Dropdown in Header should close on click-outside

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/civic#146]
It's been driving me kinda batty.

**Steps to reproduce**
1. Click the collections link in the header, in either the 2017 or 2018 packages or in Storybook.
2. Click somewhere else in the page.
3. Observe the dropdown is still open.

**Expected result**
The dropdown should close after clicking anything other than the dropdown or the contents of the dropdown.

**Comment by jaronheard** [comment]
Connected to #133

**Comment by ericgold** [comment]
I found this and tried to implement a similar approach. Not working yet :)
https://larsgraubner.com/handle-outside-clicks-react/

**Comment by jaronheard** [comment]
@ericgold - I unassigned you from this issue, but feel free to reassign yourself if you're still working on it.

**Comment by jaronheard** [comment]
New header doesn't have this problem! ✨
