### ISSUE TITLE
Hold - Neighborhoods: address counts for each age group from 2006 - 2016

### ISSUE THREAD

**Issue by ylee22** [hackoregon/civic#150]
# Story Card Request

**Project: Neighborhoods**
**Card Title: number of unique addresses for each age group from 2006 to 2016**

## Description / Wireframe
The main plot is a bar plot of the average number of unique addresses for each age group. Included is also the individual histograms and the total address count data summary for each age group.

## Data Visualization / Design Concerns
Chart Title: How many homes did people have from 2006 to 2016?
Chart Subtitle: Grouped by age at 2006

I would like to show the average address count as a bar graph for each age group. I have also included the data summary along with the histogram for each age group. This can be shown in the source.

## Context
In order to understand whether young people move more than the older population, voters were separated into age groups (18-25, 26-32, 33-39, 40-49, 50+) and the average number of unique addresses from 2006 to 2016 are visualized as bar graphs for each age group. Included are the individual histograms and the data summary for each age group.

## Data Details (APIs)
Dataset: voter_info
Fields: age2006, counts
Description:
- age2006: age of the individual at 2006
- counts: number of unique addresses from 2006 to 2016 period for each individual

The individual histograms and the data summary for each age group can be shown in the data source, if it's too cluttered to include it with the main bar chart.

## About this data
Attached the notebook for how the data summary and the histograms: [ipython_notebook](https://gist.github.com/ylee22/a68ab816da9e358c30cf5a0c49b2c259)

Data will be located in the Neighborhoods database.

### How did we calculate this
Aggregate unique addresses by age groups (18-25, 26-32, 33-39, 40-49, 50+)

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by hassanshamim** [comment]
@ylee22 did you say the age brackets changed for this one?  Is is still by decade?

**Comment by ylee22** [comment]
Changed age groups for the total counts to the following groups: [18, 25], [26, 32], [33, 39], [40, 49], 50+

**Comment by hassanshamim** [comment]
This is done.  See: http://service.civicpdx.org/neighborhood-development/api/voter_movement_counts?limit=50 (there are only 50 results so you can fetch them all in a single request)

**Comment by jaronheard** [comment]
Closed as part of 2018 project season clean-up
