### ISSUE TITLE
Neighborhoods: percent shared housing over time

### ISSUE THREAD

**Issue by ylee22** [hackoregon/civic#151]
# Story Card Request

**Project: Neighborhoods**
**Card Title: Percent of households with 4 or more people from 2006 to 2016**

## Description / Wireframe
Chart Title: How has shared housing changed over time?
Chart Subtitle: Percent of households with 4 or more people from 2006 to 2016

Line plot of the percent shared housing (as defined as addresses with 4 or more people) over time. Y axis is the percent shared housing and x ticks are the dates.

Click here for the line plot: [ipython_notebook](https://gist.github.com/ylee22/d98a69f6b525e9061e5d3309592955fc)

## Data Visualization / Design Concerns
Just a line plot showing shared housing over time. Looks like it's increasing.

## Context
An increase in shared housing might indicate that people can't afford to buy houses or that Portland is getting too expensive to live alone.

## Data Details (APIs)

Dataset: shared_housing
Fields: dates, four_or_more

Line plot of dates column vs four_or_more column

## About this data
Data will be located in the Neighborhoods database.

### How did we calculate this
For each date, count the number of people living in the same address and filter for addresses with 4 or more people

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by hassanshamim** [comment]
@jaronheard can you close this issue?  @ylee22 says it's been nixed

**Comment by hassanshamim** [comment]
Closed because it reflects a similar analysis as last year.
