### ISSUE TITLE
Build housing ranking component story-cards

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#152]
#55, #56, #57, #58, #194  are a set of similar ranking components that need to be built into individual story-cards.

These cards can be built using CivicStoryCard, GradientScale (#218), our chart components and the autocomplete search box (#141). Since each of these cards is so similar, it may make sense to create a component that is used for all of these story-cards.

There are some design / data visualization concerns with how these cards will look, since they display a large number of data points in our BarChart component.

- [x] #55 
- [x] #56 
- [x] #57 
- [x] #58 
- [x] #194 

See rough wireframes below.

[card_mockup_housing.sketch.zip](https://github.com/hackoregon/civic/files/2103634/card_mockup_housing.sketch.zip)

<img width="710" alt="image" src="https://user-images.githubusercontent.com/7065695/41431938-5cd9da08-6fc9-11e8-8a0c-37e6a604366c.png">

Housing API: http://45.55.145.111:8000/api
Endpoints are specified in each of the linked issues.

**Comment by jaronheard** [comment]
@adpeters Can you fill in the API endpoints / details for the issues referenced above?

**Comment by jaronheard** [comment]
@adpeters would it be possible to return "rank" and "total" in your API responses? I think that calculating it on the front-end will be more involved and our general workflow dictates that it should be done on the back-end.

**Comment by adpeters** [comment]
@jaronheard Yeah, I can add a "rank" field to each response. For now I'll fill in all of the other details for those cards, and then let you know when the "rank" column is added. Just to be sure, is the "total" column just the total number of items in the ranking?

**Comment by jaronheard** [comment]
Just to be sure, is the "total" column just the total number of items in
the ranking?

Yes, thanks!

**Comment by adpeters** [comment]
We would like to add another aspect to this component: when the user selects a location, a graphic will be displayed below the ranking graphic that is another, more in-depth look at that location's data. Each card will have a different graphic associated with it, and we will be adding the details of that graphic to each of the issues associated with this component. Let me know if you need any more information or have any questions.

**Comment by jaronheard** [comment]
Will the additional graphic be expandable content - "below the fold" in the card? I think that could work? This might require further discussion, but thought it'd see if you had thoughts on this.

**Comment by adpeters** [comment]
I'm not totally sure, if anybody has a strong thought on this feel free to chime in. We'll talk about it on Wednesday and come to a decision.

**Comment by kmorrice** [comment]
We have another card we'd like to be featured in this ranking framework about rent-burdened households. It's described here: https://github.com/hackoregon/civic/issues/194
I think having the additional graphic as expandable content sounds like a possibility. What other ways would work? Could the user tap on the ranked feature and it would then switch to the additional figure?

**Comment by jaronheard** [comment]
@adpeters - discussed with @DingoEatingFuzz and one thing that we need in order to build the search box is an endpoint for each dataset that returns the list of geography names needed in order to populate the search box.

For example, in #55, this would need to return the complete list of possibilities for
`county_name`, `state_name`, and `id`.
Even more ideal would just be to return a field "geography" that combines county_name and state_name in the format it would be displayed in the search box. In this case, you would be returning just `geography` and `id`.

**Comment by adpeters** [comment]
@jaronheard Got it, I'll add those endpoints and let you know.

**Comment by adpeters** [comment]
@jaronheard I've commented in each of these issues how to request the geographies. Let me know if you need anything else!

**Comment by jaronheard** [comment]
Completed
