### ISSUE TITLE
Disaster Resilience: Card #2 A life altering event for Portlanders (Neighborhood Level)

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/civic#154]
# Story Card Request Template

**Project:** Disaster Resilience
**Card Title:** Neighborhood Stats

## Description / Wireframe

> Include a detailed description and/or image that describes your story or visualization using the data described below. This can be as detailed as a wireframe, or as simple as a description such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

For this card, a user can input their street address and will be presented with a map that shows their neighborhood, and some statistics about their neighborhood, including risk metrics and social vulnerability/resilience metrics.

The map will be centered on the corresponding neighborhood for the input address and  zoomed to a level of 1 in = 1000 ft. The neighborhood boundary will be outlined. This zoom level may not capture the entire neighborhood, but the map allows the user to move around to explore the entire neighborhood.

A heat map showing a selected metric of risk will be overlayed on the map; the user can toggle between multiple different risk metrics - including Modified Mercalli Intensity scale (“Shaking Intensity”), Liquefaction, and Landslide classification. A legend on the side of the map will show the colored scale of the depicted metric; a link to more info on the depicted scale will be included (>> where is this link included?).

![my neighborhood card _2](https://user-images.githubusercontent.com/17058320/40322764-48977e72-5ce8-11e8-8928-c74fa9914e24.png)

Icons on the map will show:
Basic Earthquake Emergency Communication Node (BEECN) site
Hospitals
Fire station
Schools
Note to not include: community centers, NET staging site

Below the map will be listed some statistics/ estimated outcomes both for day and night about the neighborhood. Either in a table or using a toggle button.

  | Daytime (2pm) | Nighttime (2am)
-- | -- | --
Est. Neighborhood population | # (roundup to whole number) | # (roundup to whole number)
Est. Potential displaced population | # (roundup to whole number) | # (roundup to whole number)
Est. Potential injured population | # (roundup to whole number) | # (roundup to whole number)
Est. Potential fatalities | # (roundup to whole number) | # (roundup to whole number)

  | Daytime (2pm) | Nighttime (2am)
-- | -- | --
Est. Neighborhood population | # (roundup to whole number) | # (roundup to whole number)
Est. Potential displaced population | # (roundup to whole number) | # (roundup to whole number)
Est. Potential injured population | # (roundup to whole number) | # (roundup to whole number)
Est. Potential fatalities | # (roundup to whole number) | # (roundup to whole number)

There will also be a score presented for this neighborhood’s social capital and social vulnerability.

> If you have a wireframe, include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

We would like a way to navigate to adjacent neighborhoods. Whether those are depicted and clickable on the map, or listed as links below the map, we have not yet decided; we don’t know what would be most doable or user friendly.

This color scale for the risk metric (MMI or liquefaction) should be constant across different input addresses and across the different maps in different cards - it should not vary with the range of data specific to that map view (meaning if the specific map only has one color, the full color scale should still be present).

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.
This card follows the address specific card, it is one step back from the address level. It is meant to show the user’s full neighborhood and the potential impacts due to the earthquake. It builds on the previous card (address). This card shows the human impact (total population → displaced population, injuries, fatalities). It also brings in the day/night aspect and the differences in how many people are injured because they are at work or school in an unreinforced masonry building OR they are at home in a wood-framed home. Which gets the user ready for the city level card.

## Data Details (APIs)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
From Disaster Database:
Building_footprints
Include fields:
year_built
bldg_stat
Filters:
bldg_stat = “EXISTING”

Unreinforced_masonry_buildings
Include fields:
address
year_built
demolished
upgraded
upgrad_da (year upgraded)
wkb_geometry

Hospital
Include fields:
name
address
city
zipcode
wkb_geometry

Basic_earthquake_emergency_communication_node_beecn_locations
Include fields:
hub_name
site_name
location (address)
wkb_geometry

Address (may not be in the database yet)
Include fields:
add_full (address)
city
zip_code
geometry (point)
county
Filters:
county = “MULTNOMAH”

Schools (may not be in the database yet)
Include fields:
name
address
city
zipcode
geometry  (point)
level_no  (1 is elementary, 2 is middle school, 3 is high school)
county
Filters:
level_no in {1,2,3}
county = “Multnomah”

Need to complete:
Est. Neighborhood population day
Est. Neighborhood population night
Est. Potential displaced population day
Est. Potential displaced population night
Est. Potential injured population day
Est. Potential injured population night
Est. Potential fatalities day
Est. Potential fatalities night

Loss_Neighborhood_Unit_Csz_M9P0_Dry (>> for these I believe we discussed choosing the highest numbers for the impacts… which I think were during wet)
Loss_Neighborhood_Unit_Csz_M9P0_Wet (>> see above)
Population_And_Building_Density

Tables we do not yet have available:
<< MMI → need to calculate from ground velocity, from DOGAMI raster data >>
<< neighborhoods table >>
<< fire stations >>

<< MMI → get from DOGAMI raster data >>
<< neighborhoods table >>
<< addresses table >>
<< fire stations >>

>Link to original source data

http://rlisdiscovery.oregonmetro.gov/
https://gis-pdx.opendata.arcgis.com/
http://www.oregongeology.org/pubs/ofr/p-O-18-02.htm

**Comment by Kodiraet** [comment]
### Contextual Description 

It will be critical for individuals to understand their location relative to key resources immediately following an earthquake. The BEECN site is a place to go in Portland after a major earthquake to ask for emergency assistance or report severe damage/injury. Places like hospitals, fire stations and schools will be rallying points for the community and crucial for recovery efforts. Input your address, or a friend/family member’s address below to generate a personalized map. 
[Link for the BEECN site program: https://www.portlandoregon.gov/pbem/59630]
