### ISSUE TITLE
Add axis labels to BarChart, HorizontalBarChart, and LineChart

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#171]
The BarChart (#44), HorizontalBarChart (#83), and LineChart (#48) components should have axis labels as shown in their original issues (#44, #83, #48).

The Scatterplot component implements these labels, so could be useful for an example.

- [ ] Add axis labels to these components
- [ ] Ensure that axis labels are implemented in the stories for these components.

For reference, the axis labels in the scatterplot below are Number and Rating, but the location of the label varies by component, please see the original issues for details.
<img width="732" alt="image" src="https://user-images.githubusercontent.com/7065695/40519450-7211a92e-5f74-11e8-94d9-1da2f44fb603.png">

**Comment by flamingveggies** [comment]
#207
