### ISSUE TITLE
Campaign Finance: Who Funds Oregon Elections?

### ISSUE THREAD

**Issue by dhgwilliam** [hackoregon/civic#172]
# Story Card Request

**Project:** Campaign Finance
**Card Title:** Who Funds Oregon Elections?

## Description / Wireframe

This is very similar to a previous card, but with some additional components:
We'd like to present a map of all donations positioned according to zip code (or rolled up to an easier to display geo-collection). We'd also like to filter the data on two variables: election cycle by 2 year period (with option to display "all time", probably), and "type" of donor (e.g. corporations, individual, out-of-state PACs, etc). Dataviz details are up to you, but we'd be happy with a heatmap or bubble map if possible. We'd also like the ability to display the total percentage of in-state (or out of state?) donations, also filtered by user selections.

![image](https://user-images.githubusercontent.com/36499/40534709-40a4ed2c-6007-11e8-8118-b27801b7e949.png)

## Data Visualization / Design Concerns
We put some effort in to trimming the complexity of this chart but if you have any guidance, we're all ears.

## Context
In some ways, this is at the foundation of this collection of cards. We hope to ask the questions "who funds elections" and "what is the effect of donors-qua-stakeholders in a candidacy", as well as identifying the "fingerprint" or "donor DNA" of particular types of office.

## Data Details (APIs)

TBD

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by jaronheard** [comment]
This is going to be shown as in-state / out of state breakdown on the dashboard. Closing this issue.
