### ISSUE TITLE
The Increasing Volume of Money in Oregon Elections

### ISSUE THREAD

**Issue by dhgwilliam** [hackoregon/civic#173]
# Story Card Request

**Project:** Campaign Finance
**Card Title:** The Rising Cost of Elections

## Description / Wireframe

We'd like to do a composite chart for this, overlaying the total amount of donations over time with a two regression lines, one that includes general election spending and one that ignores it. We expect this will demonstrate two different trends. We should be able to tag transactions as being primary or general spending. We'd like to also have a display of the "inflation" of cost that changes with filters. This chart will not have a time filter (as it will include data from all time periods). We'd like to filter on type of election (governor, state rep, state senate, city commissioner, school board, ballot measure). The regression lines should also be included in this filter. We'd also like to have a marker indicating when Citizens United was passed.

![image](https://user-images.githubusercontent.com/36499/40535980-fc1d8926-600a-11e8-9ad5-024e2bc1ac48.png)

The interactive components of this chart are two selectors. One is a selector for race type. The other is a selector for in-state / out of state. The same chart is shown for all race types, but with the appropriate filters applied. 

Race type:
![image](https://user-images.githubusercontent.com/7065695/41264076-88aa6958-6d9f-11e8-9fd5-242500b09312.png)

☑️All ◻️Out of State

![image](https://user-images.githubusercontent.com/7065695/41263922-ccc2c1a4-6d9e-11e8-9301-537072d61555.png)

The chart should be a line chart, with a filled area below the line showing contributions. The example above shows the title, subtitle, and axis labels with the "State Legislature" race type selected.

## Data Visualization / Design Concerns
The original design envisioned multiple trendlines, which may detract from the readability. Recommend reducing to one trendline.

## Context
This chart will help show the rising cost of elections and how different types of elections have changed differently.

## Data Details (APIs)
- [ ] Sum by race type and date

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by jaronheard** [comment]
In order to be built, we need the following:

- [ ] List of options for race type selector
- [ ] API details

**Comment by mbodenator** [comment]
List of options for race type selector:
1. *All*
2. *State legislature* (state senate and House rep)
3. *Statewide executive* (governor, secretary of state, labor commissioner, treasurer, labor commissioner)
4. *Portland metro* (pdx mayor, Pdx commissioners, metro president, metro commissioners, Multnomah County chair, Multnomah County commissioners)
5. *Statewide ballot measures*
6. *Other* (anything else)

**Comment by jaronheard** [comment]
In order to make this chart, we need the following API endpoint:
Sum by race type and date

The API response could be the same as this endpoint:
http://service.civicpdx.org/local-elections/electioncycles/

But with the totals for each race type. So, for example:
```
    {
      "id": 79,
      "name": "May 21, 1996 Primary Election",
      "type": "Primary Election",
      "start_date": "1994-11-09",
      "end_date": "1996-05-21"
      "all_contributions": 456456.25
      "state_legislature_contributions": 257000.50
//    ... total contributions for all other race types here
    },
```

Otherwise, we'd be requesting over 40,000 records from your API, and nobody wants that 😜

**Comment by mbodenator** [comment]
Oh right, got too used grouping by committee_id. This should be fixed now.

**Comment by mbodenator** [comment]
Need anything else to unblock this?

**Comment by jaronheard** [comment]
@mbodenator - what we have looks good, and I'm moving this to unblocked. Two more small requests:
Can you please add "All" to the race_types?
Can you provide a list of all possible race_types either in an endpoint or in this issue?

**Comment by mbodenator** [comment]
The list above should still be current. I've added the /local-elections/totalcontributionsrawmonthtotal endpoint for the "All" group.

**Comment by jaronheard** [comment]
#308 implemented, new issues should be created for other improvements
