### ISSUE TITLE
Campaign Finance: Who Funds Election by Race Type

### ISSUE THREAD

**Issue by dhgwilliam** [hackoregon/civic#174]
# Story Card Request

**Project:** Campaign Finance
**Card Title:** Who Funds Elections by Race Type (placeholder title)

## Description / Wireframe

This card should have 5 or so donut charts (or stacked bars to 100%, your call) representing the percentage of in-state vs. out-of-state funding. We'd like to add an election cycle slider with an option to view all years.

![image](https://user-images.githubusercontent.com/36499/40538787-f31ede08-6012-11e8-9f14-a65791129d1d.png)

## Data Visualization / Design Concerns
Our initial sketch of this was donut charts, since there are only two options this should be possible. If you think stacked bar is the way to go, we're open to that. We may also want to size the donuts according to sum of donations, although it is fairly obvious that the ballot initiatives pull in a much larger sum than any of the other races, in particular we expect they would be _far_ larger than, say, city council races.

## Context
This card represents another data type that allows users to see the difference in funding/stakeholders by race and to explore how this has changed over time.

## Data Details (APIs)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by jaronheard** [comment]
This is being incorporated into the dashboard in a different capacity. Closing this issue.
