### ISSUE TITLE
Hold - Neighborhoods: Change in taxlots over time (WIP)

### ISSUE THREAD

**Issue by avdonald** [hackoregon/civic#176]
# Story Card Request

**Project:** Neighborhoods 
**Card Title:** Change in housing by taxlots over time 

## Description / Wireframe

Looking from 2000-2018, I'm looking at the number of available taxlots with landuse of single family and multi-family and comparing these to the demolition of single family (which appears to be overlapping slightly with multi family, which is why I'm keeping it in there). 

Through an iterative process, I'm taking the demoed taxlots and looking to see when and what is rebuilt on the lot. In theory, looking for the delta of SFR and MFR over time. 

So, zoomed in view of 2000:
![2000](https://user-images.githubusercontent.com/37200699/40561317-9305093a-6011-11e8-9229-d534487bd0dd.JPG)

So you can see the taxlots by landuse value and the couple little lots demoed that I've hashed marked out. 

Then in 2001 to see what's happened to those demos it looks a little something like this:
![2001](https://user-images.githubusercontent.com/37200699/40561474-4e102d72-6012-11e8-93a9-6bbd2d9067c2.JPG)

In this AOI, some have remained SFR or actually the land has been split to become two lots as SFR. Others remain vacant/unknown. 

> Include a detailed description and/or image that describes your story or visualization using
> the data described below. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> If you have a wireframe, include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.
The words "housing crisis" are thrown around a lot in PDX. So, I was hoping, despite being able to look at the actual number of units, we would be able to begin to really access what this looks like through availability of lots as well as building sqft. 

## Data Details (APIs)

I can send the model I've built/buildinging in Model Builder if that will help, but I've used:

city_fill, from RLIS to get just PDX
taxlot polygons 
demolition permits -- I had an issue late in the game where a taxlot had a landuse value of Industry. So, I ended up having to join this with taxlots to do a select by attribute (status = Final AND LANDUSE IN (SFR, MFR))

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## About this data
taxlots and demo permits were both clipped to the PDX boundary file 

### How did we calculate this
>Description or link to GitHub description of data methodology

From 2000, I started by just looking at the total number of tax lots with a summary by type (SFR/MFR, COM, IND, OTHER)
Total number of demolitons

For the subsequent years: same as above, plus, the number of lots replaced from 2000 and by type to get a change over time. 

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by kmorrice** [comment]
Hey, I've been looking at some of the taxlot data for a potential housing card. It seems like some of the analysis I'm working on is duplicating what you might be outlining here, but I wanted to double check. Are you doing any time series analysis to look at change in values of lots over time? Feel free to message me on slack too.

**Comment by avdonald** [comment]
Hey Katie,

I messaged you on slack, but maybe this will get to you quicker. I’m not looking at taxlot values. It’s more a change over time of demolitions and just simply what is that taxlot becoming (commercial, remains housing, goes vacant, whatever). I’m just comparing pre-demoed housing building sqft to new building sqft as well as land use codes. 

Am I overlapping? 

Thanks for hitting me up. I can give you what I have so far if it’ll help you.

**Comment by jaronheard** [comment]
We are showing this in #215, so closing this issue.
