### ISSUE TITLE
Need a unique link to specific "card"/component when a user clicks the share button

### ISSUE THREAD

**Issue by meganmckissack** [hackoregon/civic#18]
Need to develop a plan and standard to route to project pages and components/cards. 

Need a unique link to specific "card"/component when a user clicks the share button.

Should the routing pattern be something like:
civicpdx.org/homlessness/unsheltered
civicpdx.org/emergency-response/response-time

**Comment by MikeTheCanuck** [comment]
Updating the title to call out the specific user-facing need, for which a routing standard and plan is one (and likely a very good) approach.

**Comment by jaronheard** [comment]
#247 addressed!
