### ISSUE TITLE
RFC: Card Routes

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/civic#182]
A major missing piece to our routing story is card routes. A card route will show a page dedicated to a single story card with a link back to the collection it is from. It serves as a standalone, shareable experience for a single card. This is why cards have the requirements that they do.

## Proposed Routing Structure

Currently our routing structure looks something like this:

  - Home page: `/`
  - About page: `/about`
  - Sandbox: `/sandbox`
  - Project Pages: `/:project-name`

The only route that this proposal aims to add is:

  - Card Page: `/card/:card-slug`

### Why not nest card links under the projects the cards are from?

Despite cards emerging from projects, we don't consider cards to be tightly coupled to a project. This is why cards have had the requirement of being independently informational and useful. In this manner, cards could be recycled in later projects, (e.g., a Trimet congestion card is just as useful in a story about the decline of Trimet ridership as it is in a general Portland traffic analysis).

### Where do card slugs come from?

Card slugs will be decided on by developers but should be loosely based on the card title.

```
Card Title: Housing Policies in Portland Metro Area
Card Name: housing-policies-in-portland-metro-area
Full URL: /card/housing-policies-in-portland-metro-area
```

### What do we do about card slug conflicts?

Slugs will have to be universally unique. We should strive to create tooling to prevent duplicates and inform a developer that a slug conflict exists as soon as possible.

**Example workflow:**

  1. Developer create a new card with the slug `donors-by-month`
  2. Development website performs a live reload/hot module replacement
  3. An error is thrown saying something like:
```
  Two cards with the slug donors-by-month have been registered
    donors-by-month, Campaign Donors By Month, @hackoregon/project-one/components/donors-by-month
    donors-by-month, Non-profit Donors By Month, @hackoregon/project-two/components/donors-by-month
```
  4. Developer chooses a unique name for the card they just created

## How does the Card page find the correct Story Card component to show?

The Card page will know the card slug via React Router. The challenging part is going from having the slug to having a reference to the component to render. 

A way to do this is to have each project export their card registries, then have the year package merge all registries. Then the card page will be able to lookup a card component in the registry based on the slug name.

**A step by step example:**

  1. The card page render hook is called
  2. The card page imports the CardRegistry
  3. The CardRegistry is a list of meta objects that include the card slug and the card component
  3. The card page finds the first object in the CardRegistry that has a slug that matches the ReactRouter slug parameter
  4. The card page renders the card component that corresponds to the slug parameter found in the CardRegistry.
  5. If no card is found, a 404 error is shown instead.

## How does the Year Package assemble the CardRegistry?

The Year Package already imports, Routes, Reducers, and the App component for each project. The Year Package will also expect a CardRegistry for each project. This import will be a plain object with a mandatory format. At load time, the Year Package will import all five CardRegistry lists from each project package, concatenate the five lists, verify that there are no duplicates, and export the result.

**Example of a project registry and the year registry merging together.**
```js
// Project index.js
import DonorsByMonth from './components/donors-by-month';
const Registry = [
  {
    slug: 'donors-by-month',
    component: DonorsByMonth,
  }
];

export { App, Routes, Reducers, Registry as CardRegistry };
```

```js
// Year registry.js
import { CardRegistry as LocalElectionsRegistry } from '@hackoregon/2018-local-elections';
import { CardRegistry as DisasterResilienceRegistry } from '@hackoregon/2018-disaster-resilience';

const FullRegistry = [].concat(LocalElectionsRegistry).concat(DisasterResilienceRegistry);

if (FullRegistry.length !== FullRegistry.uniqBy('slug').length) {
  throw new Error('Duplicate card found!' + GoodErrorMessageForDuplicateCard());
}

export default FullRegistry;
```

## How does a Card link to its own Card Page?

The easiest way to achieve this is to have `slug` be a property passed into the StoryCard component. Then the StoryCard component can blindly build a `Link` component assuming it can trust its input. Then the project StoryCard components (which wrap the StoryCard component) will provide the proper slug. This pulls as much configuration as possible out of the Year packages in favor of giving that responsibility to the card author.

## Putting it all together

1. Each project exports a CardRegistry defining all card metadata including a mapping of Card slugs to Card components.
2. The Year package imports all project CardRegistries and exports a global CardRegistry based on concatenating all project CardRegistries.
3. A new CardPage component and route will handle looking up the correct Card component based on the slug from the URL and render it
4. Cards in collections will include links to their own Card page, which is achieved by passing their own slug to the StoryCard component.

With all these pieces in motion, cards can have their own pages.

**Comment by jaronheard** [comment]
I read through this pretty carefully, and it sounds like a good plan to me. It sounds like it will properly set the foundation for the ability for cards to escape the confining boundaries of a story card collection. Soon cards will roam free like the self-contained data paragraphs that they were meant to be.

📇✨
