### ISSUE TITLE
Rent Burdened Households

### ISSUE THREAD

**Issue by kmorrice** [hackoregon/civic#194]
# Story Card Request

**Project: Housing 2018**
**Card Title: Rent Burdened Households**

## Description / Wireframe

Portland is ranked 46 out of 100 metropolitan areas with regards to the percentage of renter households that are severely burdened (in 2015). A rank of 1 is the smallest percentage of burdened households, while a rank of 100 is the greatest percentage of burdened households. Data are from the Harvard report, and are also on Housing google drive on sheet W-13: 
https://drive.google.com/open?id=17x2bhiX5omUtDNn0jd3GrPSHLEFbRszGSxldflPRywY
Data are also available on Harvard's site: http://www.jchs.harvard.edu

We will be featuring this in a similar context to our other ranking cards, using the same kind of wireframe: 
https://www.figma.com/proto/Sx4NhVdMgKdKKjPV6IEWIX7i/Housing-Card-Wireframes?scaling=contain&node-id=69%3A196&redirected=1
 
In addition to the ranking graphic, once a city is selected, there would be an additional graphic featuring data for that city that depicts the percentage of moderately burdened, severely burdened and not burdened rental households. Something like a pie chart would work. This is featuring Portland-Vancouver-Hillsboro.
![cost burden rates renters](https://user-images.githubusercontent.com/3445877/40829683-10d9e34a-6539-11e8-86cf-9f9f00e6c1ad.png)

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data: http://www.jchs.harvard.edu

**Comment by kmorrice** [comment]
@adpeters Can you add the API information/JSON sample for this? It's sheet W-13.

**Comment by kmorrice** [comment]
In addition to the ranking graphic, once a city is selected, there would be an additional graphic featuring data for that city. Something like a pie chart would work. 
![cost burden rates renters](https://user-images.githubusercontent.com/3445877/40829683-10d9e34a-6539-11e8-86cf-9f9f00e6c1ad.png)

**Comment by adpeters** [comment]
API Sample:
http://45.55.145.111:8000/api/harvardjchs/?source=W-13&datapoint=portland-vancouver-hillsboro-or-wa&limit=12
```
{
    "count": 12,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 178419,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Moderately Burdened Owners",
            "source": "W-13",
            "valuetype": "count",
            "value": "86.50000",
            "rank": 79,
            "total": 101
        },
        {
            "id": 178425,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Moderately Burdened Owners, Share of All Households",
            "source": "W-13",
            "valuetype": "percent",
            "value": "15.59000",
            "rank": 79,
            "total": 101
        },
        {
            "id": 178422,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Moderately Burdened Renters",
            "source": "W-13",
            "valuetype": "count",
            "value": "81.20000",
            "rank": 79,
            "total": 101
        },
        {
            "id": 178428,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Moderately Burdened Renters, Share of All Households",
            "source": "W-13",
            "valuetype": "percent",
            "value": "23.23000",
            "rank": 58,
            "total": 101
        },
        {
            "id": 178420,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Severely Burdened Owners",
            "source": "W-13",
            "valuetype": "count",
            "value": "52.40000",
            "rank": 75,
            "total": 101
        },
        {
            "id": 178426,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Severely Burdened Owners, Share of All Households",
            "source": "W-13",
            "valuetype": "percent",
            "value": "9.46000",
            "rank": 49,
            "total": 101
        },
        {
            "id": 178423,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Severely Burdened Renters",
            "source": "W-13",
            "valuetype": "count",
            "value": "85.00000",
            "rank": 77,
            "total": 101
        },
        {
            "id": 178429,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Severely Burdened Renters, Share of All Households",
            "source": "W-13",
            "valuetype": "percent",
            "value": "24.34000",
            "rank": 45,
            "total": 101
        },
        {
            "id": 178421,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Total Burdened Owners",
            "source": "W-13",
            "valuetype": "count",
            "value": "138.90000",
            "rank": 79,
            "total": 101
        },
        {
            "id": 178427,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Total Burdened Owners, Share of All Households",
            "source": "W-13",
            "valuetype": "percent",
            "value": "25.05000",
            "rank": 71,
            "total": 101
        },
        {
            "id": 178424,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Total Burdened Renters",
            "source": "W-13",
            "valuetype": "count",
            "value": "166.20000",
            "rank": 77,
            "total": 101
        },
        {
            "id": 178430,
            "date": "2015-01-01",
            "datapoint": "Portland-Vancouver-Hillsboro, OR-WA",
            "datatype": "Total Burdened Renters, Share of All Households",
            "source": "W-13",
            "valuetype": "percent",
            "value": "47.57000",
            "rank": 50,
            "total": 101
        }
    ]
}
```

**Comment by jaronheard** [comment]
@adpeters How do you get the geography list for this one?

**Comment by adpeters** [comment]
@jaronheard Ahh sorry I missed the reference to this one. 

API call for geography list: http://service.civicpdx.org/housing-affordability/api/harvardjchs/meta/?source=W-13&fields=geography
