### ISSUE TITLE
Scatter plot legend positioning differs between browsers

### ISSUE THREAD

**Issue by flamingveggies** [hackoregon/civic#206]
Take a look at: https://hackoregon.github.io/civic/?knob-Data%20key=sortOrder&knob-Title=Some%20title&knob-Data=%5B%7B%22x%22%3A1%2C%22y%22%3A2%2C%22series%22%3A%22cat%22%7D%2C%7B%22x%22%3A2%2C%22y%22%3A3%2C%22series%22%3A%22cat%22%7D%2C%7B%22x%22%3A3%2C%22y%22%3A5%2C%22series%22%3A%22fish%22%7D%2C%7B%22x%22%3A4%2C%22y%22%3A4%2C%22series%22%3A%22fish%22%7D%2C%7B%22x%22%3A5%2C%22y%22%3A7%2C%22series%22%3A%22cat%22%7D%2C%7B%22x%22%3A1%2C%22y%22%3A3%2C%22series%22%3A%22dog%22%7D%2C%7B%22x%22%3A3%2C%22y%22%3A3%2C%22series%22%3A%22dog%22%7D%5D&knob-Data%20values=population&knob-Subtitle=A%20description%20of%20this%20chart.&knob-dataValue=y&knob-yLabel=Rating&knob-xLabel=Number&knob-Data%20Series=%5B%22cat%22%2C%22dog%22%2C%22fish%22%5D&knob-Size=%7B%22key%22%3A%22y%22%7D&knob-Domain=%7B%22x%22%3A%5B0%2C6%5D%2C%22y%22%3A%5B0%2C8%5D%7D&knob-dataKey=x&knob-Data%20key%20labels=label&selectedKind=Scatterplot&selectedStory=with%20props&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

The legend appears centered above the chart in Chrome, and what appears to be left-justified in Safari. I have not tested any other browsers or non-Mac OSs.

**Comment by jaronheard** [comment]
This also impacts the line chart component, which also uses the same legend component.

**Comment by jaronheard** [comment]
#375 addressed
