### ISSUE TITLE
When we run 'npm install' at the top of the repo, do we also need to run it at each package?

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic#21]
The README indicates that we run `npm install` at the top level, then when we want to work with one of the sub-packages (such as the homelesness project) we just run `npm run build`.

However, in trying to get `npm run build` to work in e.g. the homelesness project, `eslint` is throwing a ton of *errors* such as:

```
error  'prop-types' should be listed in the project's dependencies. Run \'npm i -S prop-types\' to add it
```

When we run `npm i -S prop-types` at the package level (e.g. /packages/homelesness/) it throws off a ton of "unmet dependency" warnings, such that it appears we need to run `npm install` at the package level as well before going further.

Does this match others' experience as well?  If so, the README should be reformulated.  One suggestion is to break it up into two sections (with separate, task-oriented instructions for each): "Do This Before Working With Any Package", then "Do This Before Working With One Specific Package".  And if there's a scenario in which someone will be  coding at the global level, then provide instructions to that scenario as well.

**Comment by DavideDaniel** [comment]
Should only run `lerna bootstrap`. Also with the unreliable nature of npm client we are using yarn, so never do npm install, only yarn. Might have to edit docs if it says npm install.

**Comment by DavideDaniel** [comment]
I actually realized that Megan already addressed this in the README.md - I enhanced it some more in https://github.com/hackoregon/civic/pull/5
