### ISSUE TITLE
What does affordability mean?

### ISSUE THREAD

**Issue by danmelton** [hackoregon/civic#211]
# Story Card Request

**Project: Housing**
**Card Title: what does affordability mean?**

## Description / Wireframe

<img width="673" alt="screen shot 2018-06-06 at 7 51 20 pm" src="https://user-images.githubusercontent.com/99731/41075769-05ea3582-69c3-11e8-98e3-a4917b0da10c.png">

This card allows the user to play around with the 'nobs' that determine what is affordable.

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.

Understanding MFI is pretty critical to understanding why rental rates matter in Portland. This card invites the user to adjust the family size and % of median family income to see how much monthly rent a family can afford.

As an example, if i select 4 and 80% MFI, then affordable rent is $1553.

If I select 2, and 30% MFI, then affordable rent is $420.

## Data Details (APIs)

The data comes from a small report, no API for this data.
https://www.portlandoregon.gov/phb/article/651806

Spreadsheet available here:
https://docs.google.com/spreadsheets/d/1BghT9l6PknsREZwNsznOVtr2LHj2fxEs_VNJem7LXyk/edit#gid=148227845

**Comment by Dianna** [comment]
@jaronheard https://github.com/orgs/hackoregon/projects/9

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
