### ISSUE TITLE
The Challenge of Preserving Affordability in a Complex Housing Market

### ISSUE THREAD

**Issue by danmelton** [hackoregon/civic#212]
# Story Card Request

**Project: Housing**
**Card Title: The Challenge of Preserving Affordability in a Complex Housing Market**

## Description / Wireframe

We'd like to embed the Metro housing pdf as an image on the page, and when clicked, have it get bigger (perhaps a modal?)

https://www.oregonmetro.gov/sites/default/files/2018/04/19/Equitable-Housing-Initiative-Factsheet-Affordability-201804.pdf

it could also possibly be an iframe?

**Comment by jaronheard** [comment]
#358 addressed
