### ISSUE TITLE
Measuring Market Value of Homes in Portland

### ISSUE THREAD

**Issue by kmorrice** [hackoregon/civic#215]
- [ ] use our map components instead of a static image

# Story Card Request

**Project:** Housing 2018
**Card Title:** Measuring Market Value of Homes in Portland

## Description / Wireframe

This is a map within a card. It will use our CivicStoryCard, BaseMap, and MapOverlay components. The MapOverlay should use one of the divergent Civic color scales, probably this one?
<img width="235" alt="image" src="https://user-images.githubusercontent.com/7065695/41435350-62b158b6-6fd3-11e8-9fd1-38d8e4cfe951.png">

This will be a map of single family residential lots in the Portland city limits. The annual percent change in total value of the tax lot is computed for years 2005 - 2017 (see note below). Data are represented as polygons. The attribute to be featured is the percent change. 
[tl_2017_change.pdf](https://github.com/hackoregon/civic/files/2088874/tl_2017_change.pdf)
![tl_2017](https://user-images.githubusercontent.com/3445877/41215431-1ddceece-6d05-11e8-8908-8073ef07b797.png)

## Data Visualization / Design Concerns
I have gone through and validated against historical taxlot data on Portland maps. There was an offset for some years, and some redundancies for others. After corresponding with Metro, I received corrected files for years that were causing issues, and I updated the other data where there was an offset. I suggest we feature 2005-2017.  

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.
This map will clearly show how different regions are changing with regards to increasing (or decreasing) value of single family homes over time. 

## Data Details (APIs)

Data are processed and will be added in the next few days to housing API. 

The data include yearly taxlot data and feature the percent change in a taxlots total value from year to year. 

See API details in @adpeters's comment below

- [ ] Need to provide flat files

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

Metro RLIS data

**Comment by adpeters** [comment]
Details:
This is polygon data that the API returns as geojson. The value we want to look at is `percent_change`. You can filter by a specific year, or by a year range using the parameters `year_range_0=MIN&year_range_1=MAX`. Here is a sample API call:

http://service.civicpdx.org/housing-affordability/api/taxlots/?year=2016
```
{
    "count": 162665,
    "next": "http://service.civicpdx.org/housing-affordability/api/taxlots/?limit=10&offset=10&year=2016",
    "previous": null,
    "results": {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "geometry": {
                    "type": "MultiPolygon",
                    "coordinates": [
                        [
                            [
                                [
                                    -122.727840761296,
                                    45.4679814269519
                                ],
                                [
                                    -122.727847210122,
                                    45.4676458547267
                                ],
                                [
                                    -122.728276363326,
                                    45.4676290001664
                                ],
                                [
                                    -122.728269499856,
                                    45.4679855178845
                                ],
                                [
                                    -122.727840761296,
                                    45.4679814269519
                                ]
                            ]
                        ]
                    ]
                },
                "properties": {
                    "year": 2016,
                    "total_value": 470940,
                    "percent_change": 15.14
                }
            },
            ...
            {
                "type": "Feature",
                "geometry": {
                    "type": "MultiPolygon",
                    "coordinates": [
                        [
                            [
                                [
                                    -122.650799167282,
                                    45.5575055344294
                                ],
                                [
                                    -122.650800255742,
                                    45.5573684753255
                                ],
                                [
                                    -122.651221012502,
                                    45.5573700875343
                                ],
                                [
                                    -122.65121975629,
                                    45.5574796451931
                                ],
                                [
                                    -122.651219440447,
                                    45.5575071395068
                                ],
                                [
                                    -122.650799167282,
                                    45.5575055344294
                                ]
                            ]
                        ]
                    ]
                },
                "properties": {
                    "year": 2016,
                    "total_value": 558380,
                    "percent_change": 19.81
                }
            }
        ]
    }
}
```

**Comment by jaronheard** [comment]
@adpeters I'm currently getting a server error on the API endpoint listed above, but this looks really good. Just to confirm, @AraOshin is not making this one into a Sandbox layer, so this will be a map within a card?

To me, this card has progressive levels of interactivity / difficulty on the front-end, and the developer building this card should pick the level appropriate for the time remaining:
![image](https://user-images.githubusercontent.com/7065695/41434411-7fcdf254-6fd0-11e8-8aed-3bf8e2dc1553.png)

**Comment by jaronheard** [comment]
There is useful discussion about animation in #166

**Comment by adpeters** [comment]
@jaronheard Ah yeah, we're currently waiting on the new database version to be uploaded so that's why the error is there right now. Hopefully that will be up tonight. I think the idea is that this would be a map within a card, but we're open to adding it to the sandbox too. I mentioned to @AraOshin that we have this data coming up and might want to do something with it, but I don't feel strongly about it.

**Comment by adpeters** [comment]
@jaronheard The data is in the API now so the link is working!

**Comment by jaronheard** [comment]
@adpeters In order to generate the map, we'd have to pull all 160000+ tax lot polygons. That's quite a bit larger than my understanding of what our APIs can handle, but correct me if I'm wrong. 

I think we need each year in a flat file in order to display - I recall discussing this with Katie. Our front-end framework will be able to handle the display.

**Comment by adpeters** [comment]
@jaronheard Okay we can do flat files! Do you need it as a shapefile or geojson? And how should they be delivered? Can we just have them in our S3 bucket?

**Comment by jaronheard** [comment]
@adpeters geojson in your S3 bucket is 🍇 - er, great!

**Comment by adpeters** [comment]
@jaronheard Great, uploading them now. Do they need to be publicly accessible?

**Comment by jaronheard** [comment]
@adpeters I believe they do... I don't know all the deetz. Might want to check with devops

**Comment by jaronheard** [comment]
@adpeters @kmorrice can you make sure the link to the files gets in this issue so this can be unblocked?

**Comment by adpeters** [comment]
@jaronheard All of the files are up: https://s3-us-west-2.amazonaws.com/hacko-data-archive/2018-housing-affordability/data/taxlots/geojson/taxlots_portland_2005.geojson where you can change the year for all years between 2005-2017. However I am currently unable to make these files public (it says Access Denied) so I'm not sure if that's something somebody else has to do or what. Do you know if there's anyway for you to access them with credentials?

**Comment by Dianna** [comment]
@jaronheard https://github.com/orgs/hackoregon/projects/9 ?

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
