### ISSUE TITLE
Disaster Resilience: Card #1 - Severe Shaking and Ground Deformation

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/civic#217]
**Project:**  Disaster Resilience
**Card Title:** Violent Shaking and Ground Deformation

## Description / Wireframe
City-level map showing shaking intensity, and total deformation scenarios for a wet and a dry season event.

![card a](https://user-images.githubusercontent.com/17058320/41377654-a11e0ef4-6f11-11e8-8865-46688beeeb8a.png)

Three different maps of impacts to Portland from the Cascadia Subduction Zone (9.0) earthquake:
Shaking intensity
Landslide
Liquefaction

Ground Shaking Intensity (Modified Mercalli Index) estimates by neighborhood. Shaking in Portland will be Very Strong to Severe. 

Very strong: Damage negligible in buildings of good design and construction; slight to moderate in well-built ordinary structures; considerable damage in poorly built or badly designed structures; some chimneys broken.

Severe: Damage slight in specially designed structures; considerable damage in ordinary substantial buildings with partial collapse. Damage great in poorly built structures. Fall of chimneys, factory stacks, columns, monuments, walls. Heavy furniture overturned.

![mmi_portland_by neighborhood](https://user-images.githubusercontent.com/17058320/41083082-2c82de84-69e5-11e8-8185-771dc9534311.PNG)

LandSlide and Liquefaction estimates for a Cascadia Subduction Zone Magnitude 9.0 Earthquake - Wet (Saturated) Soil Scenario

![landslide_liquefaction_wet_saturated_soil_scenario_by_neighborhood](https://user-images.githubusercontent.com/17058320/41083097-34fabd16-69e5-11e8-924d-420ca3694175.PNG)

Landslide estimates - Dry Soil Scenario

![landslide_estimate_dry_soil_scenario_by_neighborhood](https://user-images.githubusercontent.com/17058320/41083105-3bbf0e22-69e5-11e8-86de-09a8bb6a2e5f.PNG)

## Context

Contextual Description: Based on developed models, scientists can estimate what will happen to the ground in a 9.0 Cascadia Subduction Zone earthquake. The below maps apply these models to Portland based on a calculated average for each neighborhood, based on the following:
Shaking intensity, how much the surface of the earth moves during an earthquake, is represented using a Modified Mercalli (MM) Intensity scale. [link for Modified Mercalli (MM) Intensity: https://earthquake.usgs.gov/learn/topics/mercalli.php]

Total Deformation (average of liquefaction/landslide combined) during a wet season is impacted by both landslide potential and liquefaction potential. Landslide potential is based on topography and soil conditions. Liquefaction potential estimates the potential for saturated (wet), unconsolidated/loose ground materials to liquefy or give way during an earthquake.

Total Deformation (average of landslide - there’s no liquefaction) during a dry season season is impacted by landslide potential based on topography. The lack of moisture in the ground will lessen the impact of the event.

## Data Details (APIs)
These might be static graphics or they might be in the Sandbox.

Shaking Intensity: http://service.civicpdx.org/disaster-resilience/sandbox/foundations/shaking/
Landslide: http://service.civicpdx.org/disaster-resilience/sandbox/foundations/landslide/
Liquefaction: http://service.civicpdx.org/disaster-resilience/sandbox/foundations/liquefaction/
### How did we calculate this
Modified Mercalli Intensity (MMI) values are defined by binning Peak Ground Velocity (PGV) values obtained from the DOGAMI model output (raster) for the Cascadia Subduction zone earthquake simulation.  The following bounds were used to convert PGV (in cm/s) to MMI:

'Not felt (I)' = 0 - 0.1
 'Weak (II-III)' = 0.1 - 1.1
'Light (IV)' = 1.1 - 3.4
'Moderate (V)' = 3.4 - 8.1
'Strong (VI)' = 8.1 - 16
'Very Strong (VII)' = 16 - 31
'Severe (VIII)' = 31 - 60
'Violent (IX)' = 60 - 116
'Extreme (X)' = >116

Similarly, Permanent Ground Deformation Intensity (PGDI) values are defined by binning Permanent Ground Deformation (PGD) values obtained from the DOGAMI model output (rasters) for the Cascadia Subduction zone earthquake simulation.  The following bounds were used to convert PGD (in cm) to PGDI:

'None' = 0
‘Low’ = 0 - 10
‘Moderate’ = 10 - 30
‘High = 30 - 100
‘Very High’ =  >100

### See the source
>Link to API / data documentation on GitHub
DOGAMI model output data source: https://www.oregongeology.org/pubs/ofr/p-O-18-02.htm
RDPO report containing PGD binning values: http://www.oregongeology.org/pubs/ofr/O-18-02/O-18-02_report.pdf

**Comment by PoeStewart** [comment]
@AraOshin is this something that we can make in the sandbox or should we use static images? Thanks!

**Comment by AraOshin** [comment]
@PoeStewart  Hi! Yes this will be 3 separate sandbox foundations and then you will be able to layer the slide on top with the icons for points of interest (schools, fire stations etc). I am just waiting on the data (the table Fred pulled up) to be loaded into the database.

**Comment by PoeStewart** [comment]
Okay, yeah, it seems that there is a technical bottle neck there that I
don't totally understand but they are working on it. Thanks!

**Comment by eecooper** [comment]
##new text for context

Contextual Description: Based on developed models, scientists can estimate what will happen to the ground in a 9.0 Cascadia Subduction Zone earthquake. The below maps apply these models to Portland based on a calculated average for each neighborhood, based on the following:
Shaking intensity, how much the surface of the earth moves during an earthquake, is represented using a Modified Mercalli (MM) Intensity scale. [link for Modified Mercalli (MM) Intensity: https://earthquake.usgs.gov/learn/topics/mercalli.php]
Total Deformation (average of liquefaction/landslide combined) during a wet season is impacted by both landslide potential and liquefaction potential. Landslide potential is based on topography and soil conditions. Liquefaction potential estimates the potential for saturated (wet), unconsolidated/loose ground materials to liquefy or give way during an earthquake.
Total Deformation (average of landslide - there’s no liquefaction) during a dry season season is impacted by landslide potential based on topography. The lack of moisture in the ground will lessen the impact of the event.

**Comment by Kodiraet** [comment]
Did @AraOshin get what she needs to make this a sandbox feature?

**Comment by PoeStewart** [comment]
I am not sure, we have a new version of our API with a sandbox portion now but I don't think the POI is what is needed for this card. http://service.civicpdx.org/disaster-resilience/

**Comment by AraOshin** [comment]
I think I have everything! Was waiting on the database update but that was
handled earlier this week. Should have endpoints up today.

**Comment by AraOshin** [comment]
I think I have everything! Was waiting on the database update but that was handled earlier this week. Should have endpoints up today.
@PoeStewart  will connect with you if I have questions

**Comment by eecooper** [comment]
API for landslide map: /disaster-resilience/sandbox/foundations/landslide/
API for liquifaction map: /disaster-resilience/sandbox/foundations/liquefaction/
API for shaking intensity map: /disaster-resilience/sandbox/foundations/shaking/

@AraOshin we're not sure if you still needed these or not

**Comment by AraOshin** [comment]
@eecooper  I'm confused. Those are the endpoints I made :). Is something else going on/needed?

**Comment by AraOshin** [comment]
@eecooper no worries at all! just wanted to make sure all was well 👍

**Comment by jaronheard** [comment]
This is a Civic Sandbox layer now!
