### ISSUE TITLE
Create gradient scale component

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#218]
We need to build a simple gradient scale component for use in #152 and #156.

- [x]  Add any necessary dependencies
- [x]  Write GradientScale component
- [x]  Add unit tests
- [x]  Add the GradientScale story

This gradient scale component should take the following:

- A data range [domain]
- A number in that data range
- Optionally, two additional numbers in that data range to show variation
- A gradient option from the gradients on page 14 and 17 in this style guide - should look like the gradients on page 14 with the slight border

[Civic-Style-Guide-v1.1beta.pdf](https://github.com/hackoregon/civic/files/2081020/Civic-Style-Guide-v1.1beta.pdf)

The component should look something like this with one number in the data range:
![image](https://user-images.githubusercontent.com/7065695/41110198-ad506f20-6a2d-11e8-8454-d4c78eec25fe.png)

And something like this with three numbers in the data range:
![image](https://user-images.githubusercontent.com/7065695/41110342-fc4c1e9e-6a2d-11e8-9af1-a3ff1cd36061.png)

**Comment by clemf** [comment]
@jaronheard Can you give an example of how this would be used in one of the linked projects? Do you want labels? Is the gradient a simple background or does it represent the data somehow?

**Comment by jaronheard** [comment]
The gradient does represent data.

#152 has the ranking component story cards for housing, and has 4 linked cards that will use this component.

Essentially, this component takes the following:
domain <- array with two numbers, 
rank <- a number in the domain
variation <- two additional numbers in the domain (optional)

If you look at the API sample in this [comment](https://github.com/hackoregon/civic/issues/55#issuecomment-386904808), it has rank and total. 
```
domain = [1,total]
rank = [rank]
```
https://github.com/hackoregon/civic/issues/55

**Comment by jaronheard** [comment]
I will share additional use cases, but it shouldn't change the functionality needed in this component.

**Comment by clemf** [comment]
@jaronheard @DingoEatingFuzz I've made some progress with this, but am still struggling to fully understand what I'm building. Without any labels or an example it's hard to visualize. Exactly how does the gradient represent the data? There's only one axis, which represents "rank", right?

**Comment by jaronheard** [comment]
@clemf -  per our conversation - the gradient is actually kind of just a background - we're using the full gradient range for every data set - and it just uses a linear scale. Supporting other scales or using only part of the gradient range would be a cool feature for the future, but for now we're keeping it simple.

@DingoEatingFuzz

**Comment by jaronheard** [comment]
#304 addressed
