### ISSUE TITLE
Class Size and Quality 

### ISSUE THREAD

**Issue by NatalieRaketic** [hackoregon/civic#227]
- [x] Needs API endpoints

Description / Wireframe

Scatterplot of average teacher experience (years) to average number of student a teacher has in a classroom. There is a dropdown a to select years.

The scatterplot will show data for the selected year:
Note, there will be 4 categories, see details in comments below.
![image](https://user-images.githubusercontent.com/7065695/41449260-d12c8608-7014-11e8-9c15-4bf5d6bf341a.png)

Data Visualization / Design Concerns

Having the various schools types in different colors (elementary,PK-5, PK-8/PK-12,6-8,9-12) allows the user to see how staffing is affected by the age of the schoolchildren.

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.
Average class size was used as a metric to determine which schools would receive or lose FTE in the 2018-19 fiscal year. Understanding fluctuations in student teacher ratios across schools and time as well as in relation to teacher experience, provides the end user with context to understand a staffing model

 Data Details (APIs)

pps_classsize.csv (average class size)
school_fte_2018.csv (school_fte_2018_19)

About this data
This data is pulled from published PPS reports.

How did we calculate this?

**Comment by jaronheard** [comment]
@NatalieRaketic Please update with wireframe from story document.

**Comment by hassanshamim** [comment]
@NatalieRaketic @arailsya 

Where does average teacher experience come from?    we have a teacher_experience table in the DB  but the only related column is called 'Average Experience School FTE (in years)' and most are < 1???


I see the student:teacher ratios in 'pps_fte_2018.csv' for that single year (2018)

Notes for me:
- Selector is by year

**Comment by jaronheard** [comment]
@arailsya do you have any more comprehensible titles for these categories?

PK/K-8th and K-12th 
PK/K-5th 
9th-12th and 6th-12th 
6th-8th

**Comment by arailsya** [comment]
Not sure there's a comprehensible title for PK/K-8th and K-12th, but I got the rest...

Elementary School PK/K-5th
High School 9th-12th and 6th-12th
Middle School 6th-8th

**Comment by jaronheard** [comment]
@arailsya How does Elementary, Middle, High, and Combined sound for categories? We can detail the breakdown in the text.

**Comment by arailsya** [comment]
Works for me.

**Comment by arailsya** [comment]
So PPS shared a more complete and cleaner dataset with me today that it looks like Hassan is going to use. They have a school type column that is this: E = Elementary, M = Middle, H = High, and O= Other. They also have first_grade and last_grade columns. 

That still work?

**Comment by jaronheard** [comment]
Ah, perfect, let's use that school type and label then.

**Comment by arailsya** [comment]
We changed the school type! 

Now we have:
The school type column is now: E = Elementary, M = Middle, H = High, C=Charter and  O= Other. Charter was added by us because those schools were not assigned a type by PPS.

**Comment by hassanshamim** [comment]
Endpoint: http://service.civicpdx.org/neighborhood-development/api/school_class_size

filter by year as so: http://service.civicpdx.org/neighborhood-development/api/school_class_size?year=2012

There is never more than 100 data points per year, so you can fetch it all in a single query

http://service.civicpdx.org/neighborhood-development/api/school_class_size?year=2012&limit=100
