### ISSUE TITLE
Neighborhoods - Understanding Proposed Staffing Changes in Portland Public Schools 

### ISSUE THREAD

**Issue by NatalieRaketic** [hackoregon/civic#235]
# Story Card Request

Project: Neighborhood Development
Title: Understanding Proposed Staffing Changes in Portland Public Schools 

## Description / Wireframe

If table (tables suck):

Headers: School Type, School Name, Proposed Staffing Change, Predicted Staffing Change, Predicted Change in Enrollment, Predicted Change in Free and Reduced Lunch, Student Teacher Ratio, Proposed Student Teacher Ratio(maybe?).

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by hassanshamim** [comment]
is this still a thing?

**Comment by jethard** [comment]
It’s a table, it should be generated in the script

**Comment by hassanshamim** [comment]
okay so what's the data source?  name of the csv?  I've gotten a lot of csvs I don't remember which this one was.

Is proposed student teacher ratio included in the table?

**Comment by jethard** [comment]
Sorry, I thought i set it up as an output of the notebook, but I guess
that’s not actually helpful to you. I’ll upload the csv to the data folder
and link it in this thread

**Comment by jethard** [comment]
The file is in this folder, under the name dataresults.csv

https://drive.google.com/open?id=1WWhDVlVU6CdfY-xSNwu_a2v_EqMnCJB0

Sorry to make that more complicated then it needed to me.

-Jeanette

**Comment by hassanshamim** [comment]
@jaronheard this is done as well.

Original csv headers:
```csv
School,Students per FTE 2018 - 19,Predictions,Variation,Historically Underserved % ,% Changes in Enrollment,2018-19 % Free Meals by Direct Cert
```

example response:
```json
        {
            "school": "Creative Science",
            "students": 17.5,
            "predictions": 16.916784,
            "variation": 0.583215998,
            "historically_underserved_pct": 0.14,
            "changes_in_enrollment_pct": 0.0,
            "free_meals_direct_cert_pct": 0.14
        }
```


URL: http://service.civicpdx.org/neighborhood-development/api/school_staffing_changes?limit=80

**Comment by jaronheard** [comment]
#354 addressed

**Comment by Dianna** [comment]
@jaronheard , moved to https://github.com/orgs/hackoregon/projects/9 ?

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
