### ISSUE TITLE
Add expand / contract functionality to CivicStoryCard

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#238]
A new feature for CivicStoryCard - it should have the ability to expand and contract.

We've discussed this in our design meetings, and have been operating as if this is happening, but I don't think there is an issue out there for this yet.

There are some implementation details to be ironed out, but the idea is that you can set a breakpoint, and all content below the breakpoint will be hidden until you expand the card.

- [ ] Add update the CivicStoryCard component
- [ ] Add unit tests
- [ ] Update the CivicStoryCard story
- [ ] Test for any regressions in the 2018 package

Designs are below:
![image](https://user-images.githubusercontent.com/7065695/41255219-a9db3780-6d7a-11e8-9443-427aa2393aa4.png)

![image](https://user-images.githubusercontent.com/7065695/41255264-d4b515ac-6d7a-11e8-911c-794eacdf8166.png)

**Comment by DingoEatingFuzz** [comment]
Implemented in #243
