### ISSUE TITLE
Left align chart + add spacing in header container on mobile

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#254]
Chart container should render title and subtitle left aligned on mobile. 

![a6eb3656-148e-4157-87fe-5baf858b4a72](https://user-images.githubusercontent.com/7065695/41379712-937d55f6-6f17-11e8-8a2d-4afb72d8f5a0.png)

**Comment by karieleana** [comment]
Add more space between chart title + text....

**Comment by jaronheard** [comment]
#375 addressed
