### ISSUE TITLE
simplify card actions

### ISSUE THREAD

**Issue by sixfoot6** [hackoregon/civic#260]
For clarity and cleaner responsiveness, let's reduce the card footer to only contain `Info` (as currently) and `Share Card`, with link icon as shown in this mock. BUT let's give the Share link the functionality of the current View link. If the user wants to copy the URL to their clipboard, they can either right click and copy, or else click through to the card permalink and copy the URL. 

<img width="1135" alt="screenshot 2018-06-13 19 25 35" src="https://user-images.githubusercontent.com/11667/41427090-aa0b6bfc-6fba-11e8-977f-82fb65a9fdc1.png">

**Comment by jaronheard** [comment]
#361 addressed
