### ISSUE TITLE
adjust corner branding and title responsiveness for cleaner look on small screens

### ISSUE THREAD

**Issue by sixfoot6** [hackoregon/civic#261]
On smaller screens (say, below ~600px or whatever our medium breakpoint is), I'd recommend that we

1. Reduce H2 font-size to 2em
2. Shrink both heigh and width of civid corner to 75px

This, along with the simplification of the card footer actions in case #259, should leave us in good shape on small screens.

![screenshot 2018-06-14 10 10 48](https://user-images.githubusercontent.com/11667/41427370-8c10cfd8-6fbb-11e8-82d4-449b65760c03.png)

**Comment by jaronheard** [comment]
#375 addressed
