### ISSUE TITLE
Make story cards consistently wider than text content well

### ISSUE THREAD

**Issue by sixfoot6** [hackoregon/civic#262]
One the farmer's market demo, we see a narrow card and a wide card.

Ideally, all story cards would be wider than the normal content well, standing out to the user with a max-width of 1000px on larger screens. On small screens, cards should adapt to the device width, as they currently do.

![screenshot 2018-06-14 10 11 56](https://user-images.githubusercontent.com/11667/41427488-fa0aea96-6fbb-11e8-852f-eb765f7473e6.png)

**Comment by jaronheard** [comment]
#360 addressed
