### ISSUE TITLE
Disaster Resilience: Card #6 - Increasing Social Capital leads to Increased Resilience

### ISSUE THREAD

**Issue by kursin2** [hackoregon/civic#268]
# Story Card Request Template

**Project:** Disaster Resilience
**Card Title:** Increasing Social Capital leads to Increased Resilience

## Description / Wireframe
Starts with a map of Portland with the neighborhoods outlined (Looks similar to the second card on ER last year: http://emergency-response.civicpdx.org/). 

The neighborhoods are colored dark to light based on social capital. (below is an example not the actual values)
![image](https://user-images.githubusercontent.com/32722685/41495149-440d0d9e-70d5-11e8-8a95-dac34e1393e0.png)

If you hover over the neighborhoods, you will be able to see the name of the neighborhood.

Contextual Description: In the event of a devastating earthquake, community and connections within that community are frequently cited by survivors as being critical to recovery. Social capital is a means for measuring the social connections and engagement within a community, and the higher the social capital for a community, the greater the resilience in the face of a disaster will be.
Social capital is not a readily available statistic, but recent academic studies have demonstrated a strong correlation between census response rates, readily available data, and social capital. The below map uses census response rates by neighborhood as a stand-in for social capital.
[Link for recent academic studies: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1019.2188&rep=rep1&type=pdf]
https://www.citylab.com/solutions/2017/02/recovering-from-disasters-social-networks-matter-more-than-bottled-water-and-batteries/516726/

Some ways to increase the social capital of your neighborhood include meeting your neighbors, attending community events such as National Night Out or Neighborhood Association Meetings, attending/hosting a block party, and volunteering in your neighborhood. Anything that can deepen the interactions and trust in your locality can potentially improve how well you and your neighbors weather and recover in the face of a disaster.
[Link for meeting your neighbors: http://www.preporegon.org/MYN_overview]
[Link for National Night Out: https://www.portlandoregon.gov/oni/55345]
[Link for block party: https://www.portlandoregon.gov/transportation/66080] 

![social capital and resilience](https://user-images.githubusercontent.com/17058320/41506429-6f8fc67a-71d2-11e8-97e9-0c136e3f136e.PNG)

## Data Visualization / Design Concerns
This map may look very similar to the “A Life-Altering event for Portlanders” map. It is showing something different, so different colors or potentially something else to make it stand out would be good. This one is positive when the number is higher so maybe it can be greens?

## Context
This shows the potential resilience of a neighborhood based on the social capital.

## Data Details (APIs)

http://service.civicpdx.org/disaster-resilience/sandbox/foundations/censusresponse/

Census Response rates (grade the color of the neighborhood by this):
census_response_rate

Neighborhood:
name

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
https://www.census.gov/research/data/planning_database/2016/

**Comment by kursin2** [comment]
@PoeStewart @jaronheard this is card 6... i don't believe it has anything to do with sandbox... but if it does the API endpoints will need to be updated.

**Comment by jaronheard** [comment]
This is a Sandbox card. @AraOshin is building this endpoint.

**Comment by AraOshin** [comment]
The endpoint for this is done. (Though now that I am seeing this card written out I will add the neighborhood name on hover.

**Comment by kursin2** [comment]
updated with sandbox link

**Comment by kursin2** [comment]
## NOTE: this is our second highest priority card for demo day

**Comment by jaronheard** [comment]
This is a layer in the Civic Sandbox now!
