### ISSUE TITLE
Civic Sandbox Dashboard

### ISSUE THREAD

**Issue by mendozaline** [hackoregon/civic#269]
The Civic Sandbox map will include a dashboard as seen in issue [#163](https://github.com/hackoregon/civic/issues/163).

The dashboard will display data from the foundation layers using the [half-doughnut chart](https://github.com/hackoregon/civic/issues/245), [comparison bars](https://github.com/hackoregon/civic/issues/245), [gradient scale components](https://github.com/hackoregon/civic/issues/218), and text.
![Dashboard1](https://i.imgur.com/4v00DnN.png)

It will also include a view that provides a description of the map. Users can switch back and forth between the data display and the description.
![Dashboard2](https://i.imgur.com/skd4mSv.jpg)

**Comment by jaronheard** [comment]
#271 addressed
