### ISSUE TITLE
Disaster Resilience: Card #3 - A Life-Altering event for Portlanders

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/civic#272]
- [x] Needs API details
- [x] New API endpoint that delivers GeoJSON instead of WKB geometries.

**Project:** Disaster Resilience
**Card Title:** A Life-Altering event for Portlanders

## Description / Wireframe
Starts with a map of Portland with the neighborhoods outlined (Looks similar to the second card on ER last year: http://emergency-response.civicpdx.org/).

The neighborhoods are colored dark to light based on number of fatalities..

![card 3 city map](https://user-images.githubusercontent.com/17058320/41572850-c109769c-732e-11e8-9872-0d4b8c7757ca.PNG)

Before you click on a neighborhood, below the map you see the following fields:

#City Population: (roundup to whole number)
#City Potential Displaced Population: (roundup to whole number)
#City Damage Estimates: (roundup to whole number)

  | Daytime (2pm) | Nighttime (2am)
-- | -- | --
Est. City Occupants | # (roundup to whole number) | # (roundup to whole number)
Est. City Potential injured population | # (roundup to whole number) | # (roundup to whole number)
Est. City Potential fatalities | # (roundup to whole number) | # (roundup to whole number)

You can then click on a neighborhood and get the stats below.

![card 3 neighborhood map](https://user-images.githubusercontent.com/17058320/41572853-c8f076a8-732e-11e8-9e14-959c71ac0d72.PNG)

Neighborhood Name

#Neighborhood Population: (roundup to whole number)
#Neighborhood Potential Displaced Population: (roundup to whole number)
#Neighborhood Damage Estimate: (roundup to whole number)

  | Daytime (2pm) | Nighttime (2am)
-- | -- | --
Est. Neighborhood Potential injured population | # (roundup to whole number) | # (roundup to whole number)
Est. Neighborhood Potential injured population | # (roundup to whole number) | # (roundup to whole number)
Est. Neighborhood Potential fatalities | # (roundup to whole number) | # (roundup to whole number)

## Data Visualization / Design Concerns
This map may look very similar to the “Increasing Social Capital leads to Increased Resilience” map. It is showing something different, so different colors or potentially something else to make it stand out would be good. This one is negative when the number is higher so maybe it can be reds?

## Context
It shows the impact of the earthquake on the whole city and allows them to toggle between neighborhoods to see how they are impacted. This starts to open the user’s eyes that they need to be concerned about more than just their house.

## Data Details (APIs)

API endpoint: http://service.civicpdx.org/disaster-resilience/api/DisasterNeighborhoodView/

For the city stats, we can sum the data for each neighborhood. 

For the neighborhood stats, this will simply serve up the data in the row of the table described in the city stats (above) that corresponds to the selected disaster neighborhood.

Roundup all people numbers to whole number
Roundup all dollars to decimal point

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
Original data source: https://www.oregongeology.org/pubs/ofr/p-O-18-02.htm

**Comment by sowright** [comment]
# API Details:
# All data is from the endpoint: http://service.civicpdx.org/disaster-resilience/api/DisasterNeighborhoodView/
# Everything in quotes that follows are API field names.

# The map neighborhood outlines come from: 
“wkb_geometry”

# Start with city-wide level (default before neighborhood is selected) 
# At this level, statistics are calculated as the sum of all the neighborhood statistics.
# All values should be rounded up to the largest integer.

# Values populate these labels:
City Population: SUM(“total_population”)
City Potential Displaced Population: SUM(“displacedpopulation”)
City Damage Estimates: SUM(“buildingloss”)    # Should be dollars

# Table:
  | Daytime (2pm) | Nighttime  @(2am)
-- | -- | --
Est. City Occupants | SUM(“dayoccupants”) | SUM(“nightoccupants”)
Est. City Potential Injured Population | SUM(“injuriestotal_day”) | SUM(“injuriestotal_night”)
Est. City Potential Fatalities | SUM(“fatalitiestotal_day”) | SUM(“fatalitiestotal_night”)

# Once neighborhood is selected:
# All values should be rounded up to the nearest integer.

“name”
Neighborhood Population: “total_population”
Neighborhood Potential Displaced Population: “displacedpopulation”
Neighborhood Damage Estimates: “buildingloss”   # Should be dollars

**Comment by jaronheard** [comment]
@sowright the details look good. 

@mxmoss @PoeStewart We need the API to deliver GeoJSON instead of WKB geometries.

This API is also being used for #274 so be careful about changing the shape of the endpoint... maybe just add a new one that delivers GeoJSON. 

Related, if you're in there making new endpoint - user experience could be significantly improved for this and #274 by trimming down the information delivered to just the information that is going to be use in the visualization. Make sure to communicate what changes you're making in this issue as well as #274 and if someone is assigned reach out to them directly

**Comment by mxmoss** [comment]
@PoeStewart @sowright @jaronheard I added the new field to the existing view.
disasterNeighborhoodView - Field name is ngeo_json.

**Comment by jaronheard** [comment]
@mxmoss the response of this endpoint still needs to be restructured into GeoJSON format. For example, this Sandbox endpoint delivers GeoJSON under "slide_data" that would be very similar to what this endpoint would need to deliver.
http://service.civicpdx.org/disaster-resilience/sandbox/foundations/censusresponse/

```
 "slide_data": {
    "type": "FeatureCollection",
    "features": [
      {
        "id": 0,
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                -122.6507145389833,
                45.55771642087534
              ],
              [
                -122.6429083130228,
                45.55768675715896
              ],
// ... more geometry data
              [
                -122.6507145389833,
                45.55771642087534
              ]
            ]
          ]
        },
        "properties": {
          "name": "SABIN",  // this is where the non-geometry properties from your existing endpoint would go
          "census_response_rate": 83.9444513
        }
      },
      {
        "id": 1,
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                -122.6586036745098,
                45.54827282164544
              ],
```

Let me know if you have any questions

**Comment by nam20485** [comment]
I can take care of this tomorrow.

**Comment by nam20485** [comment]
@jaronheard This is fixed now.

http://service.civicpdx.org/disaster-resilience/api/DisasterNeighborhoodView now returns geo_json format, thusly:

```
 "url": "http://service.civicpdx.org/disaster-resilience/api/DisasterNeighborhoodView/0/",
            "name": "SABIN",
            "wkb_geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [
                            -122.6507145389833,
                            45.55771642087534
                        ],
                        [
                            -122.6429083130228,
                            45.55768675715896
                        ],
                        [
                            -122.642924772506,
                            45.55543377124673
...
```

Let me know if you need any further on this.

**Comment by jaronheard** [comment]
Hey @nam20485 - thanks for making the modification, the polygons geometries look great, but the output still needs to be structured a little bit differently to work with our map components. 

The features (the polygons) need to be in a "FeatureCollection", and the properties need to be associated with each feature. Please refer to the example I provided in my comment above, or you can see another example here: https://en.wikipedia.org/wiki/GeoJSON

**Comment by nam20485** [comment]
OK the polygons are now inside of a FeatureCollection and the output matches the example you provided. 

Let me know if this is correct.

```
 "id": 1,
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    -122.6586036745098,
                    45.54827282164544
                ],
                [
                    -122.6586089483765,
                    45.54210991947267
                ],
                [
                    -122.6586090994982,
                    45.54193942036202
                ],
               ...
            ]
        ]
    },
    "properties": {
        "name": "ELIOT",
        "pgv_site_count": "27086",
        "pgv_site_max": "40.94626998901367",
        "pgv_site_mean": "29.56741259322159",
        "pgv_site_min": "20.018796920776367",
        "pgv_site_std": "5.6167202509812295",
        "pgd_landslide_dry_count": "243753",
        "pgd_landslide_dry_max": "81.0",
        "pgd_landslide_dry_mean": "0.38536551345009085",
        "pgd_landslide_dry_min": "0.0",
        "pgd_landslide_dry_std": "5.500018955765576",
        "pgd_landslide_wet_count": "243752",
        "pgd_landslide_wet_max": "752.0",
        "pgd_landslide_wet_mean": "11.324042469395122",
        "pgd_landslide_wet_min": "0.0",
        "pgd_landslide_wet_std": "63.81520559643452",
        "pgd_liquefaction_wet_count": "243752",
        "pgd_liquefaction_wet_max": "254.0",
        "pgd_liquefaction_wet_mean": "68.04380271751616",
        "pgd_liquefaction_wet_min": "0.0",
        "pgd_liquefaction_wet_std": "91.04300656700758",
        "pgd_total_wet_mean": "79.36784518691128",
        "pgv_site_min_mmi": 7,
        "pgv_site_max_mmi": 8,
        "pgv_site_mean_mmi": 7,
        "pgd_landslide_dry_min_di": "None",
        "pgd_landslide_dry_max_di": "High",
        "pgd_landslide_dry_mean_di": "Low",
        "pgd_landslide_wet_min_di": "None",
        "pgd_landslide_wet_max_di": "Very High",
        "pgd_landslide_wet_mean_di": "Moderate",
        "pgd_liquefaction_wet_min_di": "None",
        "pgd_liquefaction_wet_max_di": "Very High",
        "pgd_liquefaction_wet_mean_di": "High",
        "pgd_total_wet_mean_di": "High",
        "pgv_site_min_mmi_txt": "Very strong (VII)",
        "pgv_site_min_desc": "Damage negligible in buildings of good design and construction; slight to moderate in well-built ordinary structures; considerable damage in poorly built or badly designed structures; some chimneys broken.",
        "pgv_site_max_mmi_txt": "Severe (VIII)",
        "pgv_site_max_desc": "Damage slight in specially designed structures; considerable damage in ordinary substantial buildings with partial collapse. Damage great in poorly built structures. Fall of chimneys, factory stacks, columns, monuments, walls. Heavy furniture overturned.",
        "pgv_site_mean_mmi_txt": "Very strong (VII)",
        "pgv_site_mean_desc": "Damage negligible in buildings of good design and construction; slight to moderate in well-built ordinary structures; considerable damage in poorly built or badly designed structures; some chimneys broken.",
        "census_response_rate": "75.19015876",
        "quadrant": "Northeast",
        "acres": "513.9555359994513",
        "buildingcount": "1127.0174398930847",
        "buildingsquarefeet": "9053135.80155152",
        "buildingcost": "1533182363.0704088",
        "buildingweight": "679275.2963973366",
        "contentcost": "1453484209.5720859",
        "permanentresidents": "3556.0",
        "dayoccupants": "11806.340315645419",
        "nightoccupants": "5146.083011334556",
        "total_population": "3556.0",
        "scenario_cd": "wet",
        "buildingloss": "266219278.97828156",
        "contentloss": "111935917.57491668",
        "debris": "150859.7957446013",
        "displacedpopulation": "228.86563027864182",
        "buildings_nodamage": "583.9621289185027",
        "buildings_slightdamage": "240.2147565902454",
        "buildings_moderatedamage": "145.01053365087898",
        "buildings_extensivedamage": "66.2210327567649",
        "buildings_completedamage": "91.60898797669262",
        "casualtiestotal_day": "282.27837314625845",
        "casualtieslevel1_day": "197.17850172855614",
        "casualtieslevel2_day": "57.710096388263096",
        "casualtieslevel3_day": "9.21415855614822",
        "fatalitiestotal_day": "18.175499604434023",
        "casualtiestotal_night": "60.068755763602205",
        "casualtieslevel1_night": "43.40202399837305",
        "casualtieslevel2_night": "11.789955593175659",
        "casualtieslevel3_night": "1.6514018552092333",
        "fatalitiestotal_night": "3.2253983702429694",
        "injuriestotal_day": "264.1027566729673",
        "injuriestotal_night": "56.84338144675795",
        "displaced_percap": "0.06436041346418499",
        "ngeo_json": "{\"type\":\"Polygon\",\"coordinates\":[[[-122.65860367451,45.5482728216454],[-122.658608948376,45.5421099194727],[-122.658609099498,45.541939420362],[-122.658614370431,45.5357829052486],[-122.658614558012,45.5355638079841],[-122.658614981168,45.5350700430986],[-122.658616979873,45.5350700595677],[-122.661813242237,45.5350942997675],[-122.666692788643,45.5351116639091],[-122.666913875936,45.535112446521],[-122.668392287385,45.5351176612572],[-122.672779196171,45.5326375200823],[-122.674094298641,45.5318939414617],[-122.674160401469,45.5318565678549],[-122.678143415549,45.5352451927908],[-122.678836871319,45.5356419685155],[-122.682921598546,45.5379789649095],[-122.681765816601,45.5389399307255],[-122.681441699455,45.5392037240968],[-122.676961318497,45.5428498252286],[-122.676088540401,45.5435600152058],[-122.675813244094,45.5437831221461],[-122.675543228394,45.544001949551],[-122.675359819359,45.5441605972462],[-122.675085510616,45.5443978913526],[-122.674803598579,45.5446417556543],[-122.674604066012,45.5448143443282],[-122.674301787771,45.5449737806377],[-122.673891079236,45.5451904007933],[-122.673604040829,45.5453417876948],[-122.673251666815,45.5455276335284],[-122.672878671461,45.5457243457397],[-122.672710268077,45.5458131688673],[-122.672483523205,45.5459327541938],[-122.672349751241,45.5460033063839],[-122.672124820031,45.5461726618241],[-122.671830442236,45.5463942951894],[-122.671384793644,45.546729827309],[-122.670996192983,45.5470259969702],[-122.670731299138,45.5472295896336],[-122.670544263299,45.5473603479948],[-122.670423244739,45.54744495132],[-122.67030930478,45.5474989239203],[-122.670177634683,45.547561287427],[-122.670043548649,45.5476248035618],[-122.669936107785,45.5476849271081],[-122.669770205311,45.547777776135],[-122.669627758887,45.5478200080905],[-122.669370582334,45.5478962611775],[-122.66901470555,45.5479892104018],[-122.668606998332,45.5480956932964],[-122.668277143976,45.5482005172786],[-122.667990146952,45.5482605329516],[-122.667965286658,45.5482657275536],[-122.666843282876,45.5482671236216],[-122.66202433167,45.548273016922],[-122.6616009167,45.548279944213],[-122.661600647515,45.5482799402731],[-122.65860367451,45.5482728216454]]]}"
    }
}
```

**Comment by nam20485** [comment]
Actually, not a FeatureCollection, but a Feature, I wonder if this is because there is only one feature? Properties are in their own collection/hashtable now too. So it more closely matches what you are looking for.

Can you give it a shot and see if it works? As far as I know, the geojson geometry in the API is set up correctly.

**Comment by Dianna** [comment]
@jaronheard , still happening?

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
