### ISSUE TITLE
Disaster Resilience: Card #7 - Proactive Planning for City-Wide Resilience

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/civic#274]
- [x] Per capita displaced (y axis):
Displaced_percap_wet (needs to be added to endpoint)

- [x] Total population (size of point):
Total_population (needs to be added to endpoint)

**Project:** Disaster Resilience
**Card Title:** Proactive Planning for City-Wide Resilience

## Description / Wireframe

For this card, a user will see a scatterplot of neighborhoods with census response rate on the x axis (high to low) and per capita displaced on the y axis (low to high). Each point represents a neighborhood which is colored by quadrant (N, NE, NW, SE, SW) and sized by population. Each neighborhood is labeled with its name (hover-text?). The neighborhoods in the top right of the plot are disproportionately impacted by the earthquake.

There are many actions, from updating infrastructure to boosting community engagement, that will need to take place to increase the overall resiliency of Portland. Examples include:
New infrastructure and capital improvement projects in Portland can be built with an emphasis on withstanding and delivering services after an earthquake.  Although this will add cost to the execution of projects, the results will pay off in a functional city after a disaster.  Projects like the “Earthquake Ready Burnside Bridge” show how existing projects can be expanded to emphasize resilience.
Investment in education and training for individuals to respond to natural disasters will help communities minimize the impacts of an earthquake and speed up recovery times.  Programs like NET and BEECN prepare communities to be self-sufficient during periods when other assistance cannot be accessed. 
Vulnerable populations have fewer resources to draw on in response to all kinds of natural disasters.  Projects that increase equity, and assist the most vulnerable groups will increase people’s ability to care for themselves and community in the immediate aftermath of an earthquake.
[Link for “Earthquake Ready Burnside Bridge”: https://multco.us/earthquake-ready-burnside-bridge]
[Link for NET: https://www.portlandoregon.gov/31667]
[Link for BEECN: https://www.portlandoregon.gov/pbem/59630]

New research from the aftermath of the devastating 9.0 Tohoku earthquake in Japan has also brought to light that resilience and the ability to recover quickly from disaster impacts is largely driven by the interpersonal connectedness and cohesion of neighborhoods -- what social scientists call social capital -- and can be even more important than the state of the physical infrastructure. When the mayor of Christchurch visited Portland last October and was asked for the single most important piece of advice she could offer Portland in preparing for the “Big One’”, it was not “reinforce all your bridges” or “give everyone a disaster kit”. It was “know your neighbors.”  The encouraging thing about this discovery is that every person has the ability to contribute to their neighborhood’s social capital and there are many ways to do so.

Social capital is not a readily available statistic and can be difficult to measure, but recent academic studies have demonstrated a strong correlation between census response rates, readily available data, and social capital. The below visualization, showing social capital v. displaced population using a wet season scenario, uses census response rates by neighborhood as a proxy for social capital. Neighborhoods with the combination of high earthquake impact and lower relative social capital should be the priority for directing community-building, resilience, and preparedness efforts. In the scatterplot below, each neighborhood is a bubble and the top right region represents the intersection of lower relative social capital and higher hazard impact. The size of each bubble is proportional to the population size of each neighborhood. We can see that neighborhoods such as Old Town/Chinatown and  Sunderland are in this region of relative higher displacement and lower social capital. Downtown is not as far to the top right but due to its relatively high population size, might also be considered a priority.
[Link for recent academic studies: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1019.2188&rep=rep1&type=pdf]

![census response rate](https://user-images.githubusercontent.com/17058320/41506473-2ddde63e-71d3-11e8-9d9e-d935a38ef2fa.PNG)

## Data Visualization / Design Concerns
There are a lot of neighborhoods, and it would be nice to see all the names, but it may make more sense to make the names of the neighborhoods only visible when hovering over them.

## Context
This scatterplot shows neighborhoods that are disproportionately impacted by the earthquake. It provides the city with a guide of where to prioritize their efforts.

## Data Details (APIs)

http://service.civicpdx.org/disaster-resilience/api/DisasterNeighborhoodView/

Census Response rates (x axis):
census_response_rate

Per capita displaced (y axis):
Displaced_percap_wet (needs to be added to endpoint)

Total population (size of point):
Total_population (needs to be added to endpoint)

Quadrant (color of point):
quadrant

Neighborhood (hover-text?):
name

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data
Original data source: https://www.oregongeology.org/pubs/ofr/p-O-18-02.htm
https://www.census.gov/research/data/planning_database/2016/

**Comment by kursin2** [comment]
@jaronheard the API endpoints will be in production by the end of today

**Comment by kursin2** [comment]
## NOTE: this is our highest priority card for demo day

**Comment by kursin2** [comment]
now available in the API:
Per capita displaced (y axis):
Displaced_percap

Total population (size of point):
Total_population

**Comment by kursin2** [comment]
@PoeStewart @jaronheard can one of you move this to ready for dev now that we have the API endpoints available?

**Comment by jaronheard** [comment]
Yep! Unblocked. This will be made.
