### ISSUE TITLE
WARN prefer global marked@0.3.6 during npm install

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic#28]
When performing the initial npm install from the top of the civic repo, the following warning is thrown:

```
$ npm install
npm WARN prefer global marked@0.3.6 should be installed with -g
```

**Comment by DavideDaniel** [comment]
No, this is an antiquated idea now. Always do local installs when possible so module is available in all envs. That being said I think this is a secondary dependency so we don't even use it directly and therefore cannot fix this.

**Comment by MikeTheCanuck** [comment]
As of #37 (or perhaps previously), this warning is no longer observed when following the current README, whose command sequence is this:

```
nvm use
yarn bootstrap
yarn build
cd packages/emergency-response
yarn start
```
