### ISSUE TITLE
[WIP] Campaign Finance: PR Curves

### ISSUE THREAD

**Issue by dhgwilliam** [hackoregon/civic#288]
# Story Card Request

**Project:** Campaign Finance
**Card Title:** [various]

## Description / Wireframe

Scale for all PR curve charts is 0 to 1 on both axes. Labels will be Recall on the X axis and Precision on the Y axis.

Sample PR Curves:
![image](https://user-images.githubusercontent.com/36499/41567164-be3fb07c-7313-11e8-80ac-ec9e3a541193.png)
![image](https://user-images.githubusercontent.com/36499/41567553-afe7316a-7315-11e8-9d81-0596d8f1c5ff.png)

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
Disclaimer: I am not a data scientist, this is very much my lay understanding and may need to be improved.

A PR curve line chart generally allows you to visualize the fitness of a machine learning algorithm. The curve represents the tension between precision (higher precision means a higher ratio of true positives to false positives when comparing algorithmic output to the "ground truth", i.e. a precision of 1 means no false positives are identified by the algorithm) and recall (higher recall means a higher percentage of all true positives are identified, in other words recall of 1 means all positives were identified correctly by the algorithm). Once you have charted the PR curve, you can make a "business" decision about the optimal relationship between precision and recall.

Our intent with this set of cards is to compare the accuracy (or inaccuracy) of a set of naive, single variable assumptions (e.g. "more money raised = win") with the (hopefully high) fitness of our ML-based, multi-variate algorithm. Within each chart we will be presenting 1 curve for all race types, and then a set of 4 curves that focus on the accuracy of the same algorithm for each different race type, potentially exposing clear differences between, e.g., the influence of money raised in different types of races within the state.

## Data Details (APIs)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by jaronheard** [comment]
Cool. This looks very doable. It looks like there are 5 categories. Does it make sense to show them all on one chart?

**Comment by seancorrigan1** [comment]
My understanding Jaron was that they would be shown on the same chart. The intent is to show how different election types were more or less related to a specific part of our predictive model. The comparison is important.

**Comment by jaronheard** [comment]
Hey Sean - showing them on one chart sounds possible for sure. How many
lines are we talking here? We could do up to 5. Let’s talk in the morning
... err, later in the morning. 🙈

**Comment by seancorrigan1** [comment]
It's 5!
