### ISSUE TITLE
Neighborhood Development Collection Does Not Render

### ISSUE THREAD

**Issue by nrbernard** [hackoregon/civic#291]
**Reproduction Steps**
* Navigate to the Neighborhood Development collection at `/cities/portland/neighborhood`

**Expected**
The neighborhood cards render

**Actual**
Nothing renders and the console has this error: `Uncaught TypeError: Cannot read property 'selectedNeighborhood' of undefined`

**Comment by jaronheard** [comment]
#293 addressed
