### ISSUE TITLE
"WARN postcss-modules-resolve-imports@1.3.0 requires a peer of postcss@^6.0.0..." during npm install

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic#30]
After `npm install` has completed the `lerna bootstrap` command, the following warning is displayed after the large tree of dependencies is displayed:

```
> lerna bootstrap

lerna info version 2.5.1
lerna info Bootstrapping 9 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished installing in root
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 9 packages
civic@ /Users/mike/code/HackOregon/civic
├─┬ @hackoregon/civic-server@0.0.10 
.
.
.
npm WARN postcss-modules-resolve-imports@1.3.0 requires a peer of postcss@^6.0.0 but none was installed.
```

**Comment by DavideDaniel** [comment]
Might not be an avoidable warning. Peer dependencies are not required dependencies and if a project has it, the root will get the warning but we can't list it in root.

**Comment by MikeTheCanuck** [comment]
As of #37 (or perhaps previously), this warning is no longer observed when following the current README, whose command sequence is this:

```
nvm use
yarn bootstrap
yarn build
cd packages/emergency-response
yarn start
```

Digging through the `yarn.lock` it appears this is an implicit dependency of `css-modules-require-hook` (which is an explicit dependency of `civic-server` - which isn't even a package included in this monorepo at present), so no idea why this warning has disappeared.
