### ISSUE TITLE
Changes to the display of housing team rankings

### ISSUE THREAD

**Issue by kmorrice** [hackoregon/civic#301]
The housing team has a number of cards where we are including rankings, and these were all designated into card #152. In some cases, it isn't immediately clear how the rankings are ordered, so it would be great to add text to the bar that is displaying where Portland ranks. This pertains to the following cards:

Portland needs affordable rental units #55 
Affordable Rental Units are Dwindling #56, #286
Who can afford to buy a home in America? #57, #296 
Pacific Northwest Tops the Nation in Surging Home Prices #58
Rent Burdened Households #194 

My suggestions for text to the ranking bar where the left hand side corresponds with a rank of 1, and the right hand side corresponds to the maximum rank, for each issue:

#55: 
**left hand side**: Most units available
**right hand side**: Least units available

#56 / #286: 
top ranking bar, units <$800: 
**left hand side**: Most units added 
**right hand side**: Least units added

bottom ranking bar, units >$2000: 
**left hand side**: Least units added
**right hand side**: Most units added

#57 / #296 : 
**left hand side**: Most affordable
**right hand side**: Least affordable

#58:
**left hand side**: Least percent change
**right hand side**: Greatest percent change

#194:
**left hand side**: Least burdened
**right hand side**: Most burdened

**Comment by kmorrice** [comment]
Also for card #56, I suggest that the language be updated for the rankings: 

Portland ranks 90/100 for change in units that cost <$800/mo between 2005 and 2015
Portland ranks 82/100 for change in units that cost >$2000/mo between 2005 and 2015

**Comment by kmorrice** [comment]
@DingoEatingFuzz I updated the text for the bar #194 (Rent Burdened Households) above. It should say Least burdened. Also, I checked the API, and it's returning the correct rank, so I'm not sure where 45/100 is coming from on this card. It should be 50. The datatype we're selecting for that ranking is 'Total Burdened Renters, Share of All Households'.

**Comment by DingoEatingFuzz** [comment]
> The datatype we're selecting for that ranking is 'Total Burdened Renters, Share of All Households'.

Ah, that'd be the issue! I'm using "Severely Burdened Renters, Share of All Households". Will fix!

**Comment by kmorrice** [comment]
Great thanks! I think there was some confusion about what we were showing.

**Comment by DingoEatingFuzz** [comment]
Indeed there was. Fixed in #334
