### ISSUE TITLE
WARN civic@ No repository field, No license field during npm install

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic#31]
At the end of the `npm install` sequence, the following two warnings are displayed:

```
npm WARN civic@ No repository field.
npm WARN civic@ No license field.
```

**Comment by DavideDaniel** [comment]
Not all Npm warnings are actual bugs and will be largely unavoidable with secondary dependencies.

**Comment by jaronheard** [comment]
#42 addressed
