### ISSUE TITLE
[emergency-response] doesn't run

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#34]
Per @MikeTheCanuck, the emergency response project is causing errors when you start the project using `yarn start`. May be related to the dev-dependency issues discussed in closed PR #20.

**Comment by jaronheard** [comment]
I'm planning to investigate later this afternoon...

**Comment by jaronheard** [comment]
I've created a pull request, but I haven't actually fixed this issue. I think it's an issue with the component library dependencies and I don't really understand it so I'm going to assign it to @DavideDaniel.

**Comment by meganmckissack** [comment]
@jaronheard I got the same result.  I do know that a lot of teams had a hard time keeping up with versioning and implementing the component library.

**Comment by MikeTheCanuck** [comment]
As of #37 (or perhaps previously), this will work when following the current README, whose command sequence is this:

```
nvm use
yarn bootstrap
yarn build
cd packages/emergency-response
yarn start
```
