### ISSUE TITLE
Neighborhoods Card #2 - viz

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/civic#370]
# Story Card Request

**Project: Neighborhoods**
**Card Title: "Human Impact of Sweeping Urban Campsites"**

## Description / Wireframe

I'd love some feedback on representing this data. Some comments:

- Data should be aggregated by month, rather than week, as it would smooth over some of the outliers/changes by time and be easier to digest (@hassanshamim, can we fix the endpoint?).
- The timeline is a little odd for the 3 data sets, since they don't have the same starting points. One option would be to restrict the timeline to 03/2017-05/2018, so all 3 data sets start at the same point. however, it's important to see the campsite reports from 2015 onwards, to show the increase in the reports. I wonder if it's worth splitting this into two cards: the one card still has the 3 lines, from 03-2017 to present, and the other card would be a bar chart of campsite reports over time to show the public's use of the system increasing (lower priority). What do you think?

Otherwise, this looks great! Thanks for all the hard work! 

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
