### ISSUE TITLE
Neighborhoods Cards (all) - source links broken

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/civic#371]
# Story Card Request

**Project: Neighborhoods**
**Card Title: all**

The Source Links for the neighborhoods projects don't link back to the methods reports we provided in the Google doc. Here is the original document with source links provided for each card, linking back to the github repo folder that contains our methods reports/further documentation: 

https://docs.google.com/document/d/1L5FfnL9JPQV2VCSmK2W3ykk_ZWoGTch-_JHV5nJEYVc/edit

**Comment by mckinneybock** [comment]
@ylee22, @arailsya, @jethard

**Comment by mckinneybock** [comment]
Also, a critical point for THE SANDBOX (potentially @AraOshin, @jaronheard)

The Eviction Lab data is in Sandbox, and it needs to be cited somewhere whenever it’s called up. There is a short blurb that needs to be cited, with the following (taken from their webpage):

Any works citing Eviction Lab data should use the following citation:

This research uses data from The Eviction Lab at Princeton University, a project directed by Matthew Desmond and designed by Ashley Gromis, Lavar Edmonds, James Hendrickson, Katie Krywokulski, Lillian Leung, and Adam Porton. The Eviction Lab is funded by the JPB, Gates, and Ford Foundations as well as the Chan Zuckerberg Initiative. More information is found at evictionlab.org.
If you use this data in your research or reporting, please share it with us.

The “share with us” link heads here: https://evictionlab.org/contact/

Thanks, you all!

**Comment by jaronheard** [comment]
#384 and #385 addressed.
