### ISSUE TITLE
Neighborhoods Card #3 (Map): Feature request

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/civic#372]
# Story Card Request

**Project: Neighborhoods**
**Card Title: Explore Urban Campsite Sweeps by Neighborhood**

The animation looks awesome  (mind blown)! I'm hoping that we can add a time slider someday so that people can pause the animation and interact with this data over time, as it goes by pretty quickly. The increase in sweeps in certain locations is very apparent, which is the purpose of this, but I know people will be left with questions and wanting to explore further. We could also point them to the Sandbox package so they can interact with the data. But, this card in particular would benefit from a time slider.

Thanks for all the hard work, everyone!

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
