### ISSUE TITLE
Dead link to civic on demo day page

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/civic#379]
Hey, just noticed this button goes to www.civicplatform.org which appears to be dead:

![dead_link](https://user-images.githubusercontent.com/26581237/44303100-da1b3d80-a2ec-11e8-96a1-e96382938a28.png)

page url:

http://www.hackoregon.org/demo-day-2018/

**Comment by jaronheard** [comment]
Fixed. However, noted that http://civicplatform.org works, while http://www.civicplatform.org does not.

**Comment by BrianHGrant** [comment]
@jaronheard this does appear to still be broken 

http://www.hackoregon.org/demo-day-2018/

**Comment by jaronheard** [comment]
@bhgrant8 thanks for pointing that out (again), it's fixed now. I also made a note in https://github.com/hackoregon/civic-devops/issues/194 about this.
