### ISSUE TITLE
Yarn build fails when run from within the component-library directory

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic#38]
Per Michael's final comment on #37:

Looks like running `yarn build` for the `component-library` package _should_ have worked, but babel wasn't found:

```
yarn run v1.3.2
$ BABEL_ENV=esm npm run build:esm && BABEL_ENV=cjs npm run build:cjs

> @hackoregon/component-library@1.0.0-alpha.1c62c05f build:esm /Users/mike/code/trash-repos/civic/packages/component-library
> babel src --out-dir es --copy-files --no-comments

sh: babel: command not found
```

What we do in other packages is use `npx babel-cli <command>` and include `babel-cli` as a dev dependency so `npx` doesn't fetch the package every time. 

It must work from the root because `babel` is accessible from that context.

**Comment by DingoEatingFuzz** [comment]
I believe so too.
