### ISSUE TITLE
Typo in main collection title - "Resiliance" vs "Resilience"

### ISSUE THREAD

**Issue by LepoutreA** [hackoregon/civic#388]
It looks like there is a typo in the title of the disaster resilience collection. We would need to change the title (class css-o7qjdw) from "Disaster Resiliance" to "Disaster Resilience" in the main page http://civicplatform.org/cities/portland/disaster (sorry browser won't let me put it as link + couldn't find the source). Hopefully this isn't a duplicate! :) @jaronheard

**Comment by jaronheard** [comment]
#388 Addressed
