### ISSUE TITLE
Incorporate yarn build into yarn bootstrap

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic#39]
Per Michael's final comment on #37:

> Just bare in mind that under working conditions, running `yarn build` from the `component-library` package should work. Potentially `yarn build` should also be incorporated in `yarn bootstrap`... We should also be striving for simplicity of setup.  ...Once we work all the kinks out, we should make sure to update the README.

**Comment by DingoEatingFuzz** [comment]
Update: `yarn bootstrap` should only run `yarn build` in the component-library. The other packages don't need to be prebuilt and it's time consuming to do so.

**Comment by jaronheard** [comment]
Addressed by #613
