### ISSUE TITLE
how to we want to handle hosting, storage, and deployment on aws

### ISSUE THREAD

**Issue by meganmckissack** [hackoregon/civic#4]
There is a reserved space on our AWS container service for the civic platform deployment.

Since as of 10/22/17 - we're no longer doing server-side rendering, should we host assets and all the app needs on S3?

**Comment by DavideDaniel** [comment]
are we ever going to want analytics or SEO? If so we will need some server. Static hosting I don't believe will get us data off the site, but I'll be honest I haven't kept up with what's possible with attic hosting now.

**Comment by DavideDaniel** [comment]
We don't have to do SSR but we can control the server and implement google analytics etc on there

**Comment by jaronheard** [comment]
2018 project season addressed.
