### ISSUE TITLE
Add Storybook Storysource Addon for component documentation

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#409]
We'd like to add the [Storybook Storysource Addon](https://github.com/storybooks/storybook/tree/master/addons/storysource) so you can see the source code of component stories in the storybook.

Here's an example of this Addon in action, from IBM:
http://react.carbondesignsystem.com/

This should be added to the webpack config for Storybook so that it doesn't need to be added to each story individually, per [the instructions](https://github.com/storybooks/storybook/tree/master/addons/storysource).

**Comment by jaronheard** [comment]
This is something that would be really useful to have as front-end development wraps up for the 2019 projects.

**Comment by bradfordjanice** [comment]
Addressed via #458.
