### ISSUE TITLE
Missing global styles

### ISSUE THREAD

**Issue by bradfordjanice** [hackoregon/civic#419]
Some typography styles defined in Civic-Style-Guide-v2.1, aren't in global.styles.css (which is used by components):

Lists and list items
Large paragraph (defined in Civic-Style-Guide-v2.1)
Data (defined in Civic-Style-Guide-v2.1)

Are they needed?  

Janice Bradford

**Comment by DingoEatingFuzz** [comment]
Yes! The global style sheet should do as much as possible to adhere to the civic style guide.

**Comment by Dianna** [comment]
This is in the process of being resolved by #790

**Comment by Dianna** [comment]
Resolved by #790
