### ISSUE TITLE
After rebuilding local master repository, git is tracking some changes to files in packages/component-library/es 

### ISSUE THREAD

**Issue by bradfordjanice** [hackoregon/civic#421]
After rebuilding a local repository for the master branch, a 'git status' terminal command showed several files as modified in the 'packages/component-library/es' directory.  No changes had been made to these files other than building the repository.  

Here are the files listed as modified:
        modified:   packages/component-library/es/BarChart/BarChart.js
        modified:   packages/component-library/es/Button/Button.js
        modified:   packages/component-library/es/Button/Button.test.js
        modified:   packages/component-library/es/Chart/Chart.js
        modified:   packages/component-library/es/ChartData/ChartData.js
        modified:   packages/component-library/es/Hero/Hero.js
        modified:   packages/component-library/es/Logo/Logo.js
        modified:   packages/component-library/es/Navigation/Header.js
        modified:   packages/component-library/es/Navigation/Nav.js
        modified:   packages/component-library/es/Navigation/NavRouterLink.js
        modified:   packages/component-library/es/Sankey/Sankey.js
        modified:   packages/component-library/es/Slider/RcSlider.js
        modified:   packages/component-library/es/Slider/Slider.js
        modified:   packages/component-library/es/Slider/SliderBox.css
        modified:   packages/component-library/es/Slider/SliderTooltip.js
        modified:   packages/component-library/es/StoryCard/StoryCard.js
        modified:   packages/component-library/es/StoryCard/StoryCard.test.js
        modified:   packages/component-library/es/StoryCard/StoryFooter.js
        modified:   packages/component-library/es/StoryCard/StoryLink.js
        modified:   packages/component-library/es/index.js
        modified:   packages/component-library/es/styleConstants.js
        modified:   packages/component-library/es/utils/isClient.js

Since they were modified during the initial build, and not development work, do they need to be tracked?  If not, can we set git so it doesn't track changes to these files?

**Comment by jaronheard** [comment]
Resolved by #425. These files were removed from source control and added to .gitignore.
