### ISSUE TITLE
add story to demonstrate multi-select dropdown list

### ISSUE THREAD

**Issue by demi-chaud** [hackoregon/civic#429]
# Component Story Request

**Storybook**
**Multi-select Dropdown List**

## Description
The dropdown list UI Component is capable of allowing multiple selections, but there is no story in the storybook to demonstrate that. 

![image](https://user-images.githubusercontent.com/19706055/54497987-74ad2080-48be-11e9-9313-effb750c40dd.png)

**Comment by bradfordjanice** [comment]
This is part of issue #577, Design System - Update Dropdown List story.
