### ISSUE TITLE
Dead link in component-library/README.md

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic#43]
When I browse to the "Hack Oregon Storybook" hyperlink in the readme for this package, it returns a variety of errors:
https://github.com/hackoregon/civic/tree/platform-revamp/packages/component-library

first time I received a "socket" error, subsequent attempts returned a 404.

Link points to https://hackoregon.github.io/civic/

**Comment by DingoEatingFuzz** [comment]
The link should work now. Storybook had never been deployed.

Related: #45
