### ISSUE TITLE
Update projects to use logos stored in the component library

### ISSUE THREAD

**Issue by bradfordjanice** [hackoregon/civic#434]
Currently some projects use duplicate logos stored in the project.  Update these projects to use the logos in the component library for consistency.

**Comment by hingham** [comment]
Hi! I would like to help contribute to this project. I pulled down the repo but couldn't find evidence of the logo being stored again the project repository. If this is still the issue, I would love to help. Please add additional info. Else, maybe close the issues?

**Comment by bradfordjanice** [comment]
Thank you for your comment.  I apologize I wasn't more specific!

The folder packages/2018/src/assets contains the logo civic-logo-animated.svg.  Any references to this logo file should be changed to refer to the logo stored in the component library:  packages/component-library/assets/civic-logo-animated.svg.

This is one specific case I found, and perhaps it is the only one, but it would be good to look through all the packages/projects for 2017 and 2018 to make sure all references to logo files come from the component-library.  There are nine variations on the logo, found in packages/component-library/assets that should be checked.  The file names are the same so only the path needs to be updated.

**Comment by hingham** [comment]
Great! I made the changes and would be happy to submit the pull request. I just need access to push up a new branch and make open the pull request.

**Comment by bradfordjanice** [comment]
Thank you!  I've notified the manager of the repo... (I don't handle permissions).

**Comment by jaronheard** [comment]
Hi @hingham! So excited that you want to contribute! 🙌

We've sent you an invite to the hack-oregon GitHub organization. Once you accept that invitation, you should be able to push your branch to the repo.

**Comment by hingham** [comment]
Great! I just opened the PR. Let me know if there is anything you would like done differently. Will keep my eyes on future issues. Amazing project!
