### ISSUE TITLE
Update Foundation references to incorrectly spelled Foundation names

### ISSUE THREAD

**Issue by nam20485** [hackoregon/civic#437]
https://github.com/hackoregon/civic/blob/master/packages/civic-sandbox/src/state/layerStyles.js

1. https://github.com/hackoregon/civic/blob/master/packages/civic-sandbox/src/state/layerStyles.js#L745

2. https://github.com/hackoregon/civic/blob/master/packages/civic-sandbox/src/state/layerStyles.js#L640

3. https://github.com/hackoregon/civic/blob/master/packages/civic-sandbox/src/state/layerStyles.js#L760

As well as any other misspellings of 'houshold'

Once these are updated and deployed then I can merge and deploy hackoregon/civic-sandbox#7
to address hackoregon/civic-sandbox#5

**Comment by jaronheard** [comment]
#438 addressed
