### ISSUE TITLE
Card: How has ridership changed throughout Tri-Met's service area over time?

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#47]
# Story Card Request

**Project: Transportation**
**Card Title: How has ridership changed throughout Tri-Met's service area over time?**

## Description / Wireframe

![image-1 1](https://user-images.githubusercontent.com/7065695/39147877-afd8d5ea-46ef-11e8-898b-755ab9a048ea.jpg)

## Data Details (APIs)
- [ ] see above, from ridership API

### How did we calculate this
- [ ] TBD
### See the source
- [ ] TBD

**Comment by code-farmhouse** [comment]
Related to Issue [76](https://github.com/hackoregon/civic/issues/76)

**Comment by jbeyer16** [comment]
This represents a lot of routes... how do we anticipate coloring / differentiating routes easily? If markersize indicates some sort of ridership metric, how can we prevent things from overlapping / cluttering?

**Comment by kiniadit** [comment]
@jbeyer16 one could use a color mapping to indicate ridership and keep the markersize constant. routes numbers could be annotated at terminals.

**Comment by jaronheard** [comment]
I've updated the original issue to conform to the latest template.

Coloring the routes is definitely too many colors if you're trying to really break things down by route - maybe it's worth moving away from that for this card. The idea behind this story card is to show ridership geospatially over time. It could be that binning up ridership by location could be useful, as in this example:
http://uber.github.io/deck.gl/#/examples/core-layers/scatterplot-layer

I'm starting to think about our map design more, and will circle back with more feedback for this issue.

**Comment by jaronheard** [comment]
I had a thought about how this card could evolve:
Starting with @jbeyer16 's animation of how the stops change over time.
![stops_over_time](https://user-images.githubusercontent.com/7065695/39834082-b9cf9c94-5380-11e8-8981-944a0b34bb81.gif)

We could use another dimension - color or size or height - to indicate ridership.

We could then layer the additional information by stop available in our API in a detail view - so something that you get when you click on an individual stop.

Something like this for the detail view:
Stop Name: Public description
Stop ID: XXXX
Routes: 12
Ons - small bar graph showing ons over time
Offs - small bar graph showing offs over time

**Comment by jbeyer16** [comment]
How might you handle stops that appear or disappear over the years? I would imagine they're a small subset of the data, so maybe it's okay to ignore them? 

I'm not too familiar with UI/UX, but would having a user interactive slider to set the year for the graphic help to immediately show spatially how the system has evolved over time? Quickly sliding up / down would essentially re-create the fig. Then upon clicking on any stop, the detail you outlined could appear to help show the ridership changes?

**Comment by jaronheard** [comment]
I think that for the map component, we will be using the Civic Sandbox.

I'd like to further discuss what we think is most meaningful to show within that framework. I'm labeling this with "Sandbox".

**Comment by ben-chaney** [comment]
- [ ] TODO:  Identify some interesting areas/lines/stops where the ridership data shows a notable trend since the end of the free fare zone. These are opportunities to show a story or insight at the demo. These might correspond to the locations where the PBOT sensors are coming in.

- [ ] TODO: define where the PBOT sensors will be
 
- [ ] TODO: find those old hand-sketches of potential Ridership insights

- [ ] TODO: determine the metrics for "Frequency" and "Area"

**Comment by jaronheard** [comment]
Addressed by layers in the Civic Sandbox.
