### ISSUE TITLE
Add Stacked Horizontal Bar Chart Option 

### ISSUE THREAD

**Issue by mendozaline** [hackoregon/civic#474]
The Civic Sandbox dashboard needs a stacked horizontal bar chart component. This will build off the Horizontal Bar Chart already in the component library.

It should look similar to this example, but horizontal: https://formidable.com/open-source/victory/gallery/100-column-chart/

- [x] Add stacked option to Horizontal Bar Chart
- [x] Add stacked example to Horizontal Bar Chart story

**Comment by jaronheard** [comment]
#622 addressed
