### ISSUE TITLE
[CARD] Hawthorne Bus Change

### ISSUE THREAD

**Issue by smooto** [hackoregon/civic#477]
# Story Card Request

**Project:** Transportation
**Card Title:** Hawthorne Bridge Bus Change
**Link to Card Template: [here](https://docs.google.com/document/d/170kdlp6yz0WhvocHIKwu5kuvVgqavaiRUBGtpCj2flU/edit)**

### Data process: Data -> API 
- [x] Data loaded to database
- [x] Database deployed to CIVIC Cloud
- [x] Basic API in container
- [x] Basic API deployed to CIVIC Cloud
- [ ] API endpoint with all needed calculations, filters and queries

### Data visualization and Design:
- [x] Clear concept
- [x] All components needed available in [Storybook](https://hackoregon.github.io/civic/)
- [x] Components available in [Storybook](https://hackoregon.github.io/civic/) demonstrate all needed features
- [ ] Follows data visualization and interface guidelines available in [Storybook](https://hackoregon.github.io/civic/)

### Documentation:
- [x] Documentation for source link complete

**Comment by znmeb** [comment]
Is this the bus lane hour change event that's been discussed in meetings or something else? I don't remember the bridge being part of the discussions.

**Comment by smooto** [comment]
I was going off the documentation we'd written out so far, but it looks like it hasn't been updated in a while. I'll keep it as "Hawthorne Bus Change" for now.

**Comment by znmeb** [comment]
OK - I'll assume it's the same thing we've been talking about. So far I have the whole system in the database so there won't be any database changes required if the bridge does suddenly want to get covered.
