### ISSUE TITLE
[CARD] Portland Population Change Over Time, by Demographic

### ISSUE THREAD

**Issue by xanderblair** [hackoregon/civic#481]
# Story Card Request

**Project:  Housing**
**Card Title:  Portland Population Change Over Time, by Demographic**
**[Link to Card Template](https://docs.google.com/document/d/1spL0Bk7d7r13Oi0iAnyMlQMzspbBrod_ozN_eana3As/edit)**

### Data process: Data -> API 
- [x] Data loaded to database
- [x] Database deployed to CIVIC Cloud
- [x] Basic API in container
- [ ] Basic API deployed to CIVIC Cloud
- [ ] API endpoint with all needed calculations, filters and queries

### Data visualization and Design:
- [x] Clear concept
- [x] All components needed available in [Storybook](https://hackoregon.github.io/civic/)
- [x] Components available in [Storybook](https://hackoregon.github.io/civic/) demonstrate all needed features
- [ ] Follows data visualization and interface guidelines available in [Storybook](https://hackoregon.github.io/civic/)

### Documentation:
- [x] Documentation for source link complete

**Comment by karenng-civicsoftware** [comment]
@xanderblair @BJHunnicutt can you and your team meet with me to talk about the version-controlling the calculations and data lineage of your datasets mentioned in this story card?

**Comment by xanderblair** [comment]
Hi @karenng-civicsoftware - of course!  Looks like our experts are already on a thread with you in Slack, I'll chime in there.

**Comment by Dianna** [comment]
Closing because handled in different issue on different board: https://github.com/hackoregon/2019-housing-data-science/issues/2
