### ISSUE TITLE
Increasing Volume of Money - NaN Error

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#495]
## Description

Instead of numbers in this card, we're seeing NaN:
![image](https://user-images.githubusercontent.com/7065695/56941206-eab0c400-6ac7-11e9-8d35-743ef2396d56.png)

I believe this is a bug introduced by the refactoring of the formatting utils and CivicFormat.

### Steps to reproduce

Visit http://civicplatform.org/cards/increasing-volume-of-money or http://civicplatform.org/cities/portland/elections

### Expected result

Should display dollars

### Actual result

See above.

### Environment

Not browser specific

### Notes

Maybe fix #376 at the same time if you're feeling motivated!

**Comment by abferris** [comment]
[shiratap](https://github.com/shiratap) and [abferris](https://github.com/abferris) have jointly fixed this issue. Please respond if issues arise.

**Comment by jaronheard** [comment]
@abferris @shiratap You can see this fix live now! Thanks! http://civicplatform.org/cities/portland/elections
