### ISSUE TITLE
Multi-touch interaction IconMap story demo

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#501]
### What

A demonstration map needs to be created that allows the user to add icons on to IconMap via multi-touch interaction. Include story knobs to enable and disable non-Icon placing map interactions (zoom, pan, etc)

This could be done as a story within Storybook for this demonstration. 

### Why

The disaster resilience team is working on a project that will include  a 65 inch multi-touch 4K display within OMSI. We’ll have our first access to the test with the display May 7th. This demo will give us a sense for potential focus areas, problem points, etc...

### When

Before May 7

**Comment by mendozaline** [comment]
Addressed by #511
