### ISSUE TITLE
[CARD] Black Homeownership over time

### ISSUE THREAD

**Issue by cassierandolph89** [hackoregon/civic#524]
# Story Card Request

**Project:** Housing
**Card Title:** Black Homeownership over time (1990 vs 2017)
**Link to Card Template: [Make a copy of this template](https://docs.google.com/document/d/1aNBU5m5vc7coXbHzItJB9sUMAGufMVYEJZqXUkY40Gc/edit#)**

https://docs.google.com/document/d/11ZjLyMLp_xDFAPbipEvdtBlu-AqfArrVUXXYwq1DjA8/edit

### Data process: Data -> API

- [x] Data loaded to database
- [ ] Database deployed to CIVIC Cloud
- [ ] Basic API in container
- [ ] Basic API deployed to CIVIC Cloud
- [ ] API endpoint with all needed calculations, filters and queries

### Data process: Data Science -> API

- [ ] Data science collaborative environment set up
- [ ] Data science results produced and documented
- [ ] Data science peer reviewed
- [ ] TBD process for peer reviewed data science results to APIs
- [ ] Data science results available through API with all needed calculations, filters and queries

### Data visualization and Design:

- [x] Clear concept
- [ ] All components needed available in [Storybook](https://hackoregon.github.io/civic/)
- [ ] Components available in [Storybook](https://hackoregon.github.io/civic/) demonstrate all needed features
- [ ] Follows data visualization and interface guidelines available in [Storybook](https://hackoregon.github.io/civic/)
![2017BlackShareByTract](https://user-images.githubusercontent.com/48421984/57500914-3e769680-729a-11e9-8e9c-b9906f19614f.png)
![1990BlackShareByTract](https://user-images.githubusercontent.com/48421984/57500916-3f0f2d00-729a-11e9-9e12-8683ee40340c.png)

### Documentation:

- [ x] Documentation for source link complete

**Comment by Dianna** [comment]
Closing because represented in a different issue on a different project board: https://github.com/hackoregon/2019-housing-data-science/issues/4
