### ISSUE TITLE
[CARD] Race vs Homeownership overtime

### ISSUE THREAD

**Issue by cassierandolph89** [hackoregon/civic#525]
# Story Card Request

**Project:** Housing
**Card Title:** Race vs Homeownership overtime
**Link to Card Template: [Link](https://docs.google.com/document/d/1Uc3Xx2WId3Ni1hTBpGFrdf-vNJjaZ_Ez5hBCOTRJMIk/edit)**

### Data process: Data -> API

- [x ] Data loaded to database
- [ ] Database deployed to CIVIC Cloud
- [ ] Basic API in container
- [ ] Basic API deployed to CIVIC Cloud
- [ ] API endpoint with all needed calculations, filters and queries

### Data process: Data Science -> API

- [ ] Data science collaborative environment set up
- [ ] Data science results produced and documented
- [ ] Data science peer reviewed
- [ ] TBD process for peer reviewed data science results to APIs
- [ ] Data science results available through API with all needed calculations, filters and queries

### Data visualization and Design:

- [x ] Clear concept - Side by side of homeownership race over time. Black vs White, years 1990 vs 2017
- [ ] All components needed available in [Storybook](https://hackoregon.github.io/civic/)
- [ ] Components available in [Storybook](https://hackoregon.github.io/civic/) demonstrate all needed features
- [ ] Follows data visualization and interface guidelines available in [Storybook](https://hackoregon.github.io/civic/)
![1990HomeOwnershipZoom](https://user-images.githubusercontent.com/48421984/57501195-63b7d480-729b-11e9-9b0d-f73b056f1423.png)
![1990BlackShareZoom](https://user-images.githubusercontent.com/48421984/57501196-63b7d480-729b-11e9-8de3-fbe2223121c5.png)
![1990BlackShare](https://user-images.githubusercontent.com/48421984/57501197-63b7d480-729b-11e9-8f71-da5a07d634b3.png)
![1990HomeOwnership](https://user-images.githubusercontent.com/48421984/57501198-63b7d480-729b-11e9-801e-3e239cf31ec0.png)

### Documentation:

- [ ] Documentation for source link complete

**Comment by Dianna** [comment]
Closing because copied to different project

**Comment by BJHunnicutt** [comment]
@Dianna we're trying to update all our Story Card documentation links in Google Docs & it seems like this is still an open issue. Do you know where this was moved?
