### ISSUE TITLE
Extra, undefined, knobs showing in addon panel.  After refreshing they disappear.

### ISSUE THREAD

**Issue by bradfordjanice** [hackoregon/civic#530]
## Description

While working locally, when I first open Storybook and look at the knobs of a component that has knobs defined, extra knobs appear.  After refreshing the story by going to another story and then back, only the defined knobs appear.

### Steps to reproduce

Open Storybook, or refresh when working on a story.
Go to a story component that has knobs.

### Expected result

You should see the defined knobs in the addon panel:

![2019-05-12_10-07-46](https://user-images.githubusercontent.com/13771753/57586651-9df8c000-74ad-11e9-8776-1f400c785113.jpg)

### Actual result

![2019-05-12_10-07-11](https://user-images.githubusercontent.com/13771753/57586645-86213c00-74ad-11e9-82f9-85ddc807af73.jpg)

### Environment

My local repo.  Happens in Chrome and Firefox.

**Comment by jaronheard** [comment]
#543 addressed
