### ISSUE TITLE
Trimet Congestion Dashboard

### ISSUE THREAD

**Issue by gouldc2** [hackoregon/civic#54]
# Story Card Request

**Transportation:**
**Trimet Congestion Dashboard:**

## API Details!

> From the Trimet Congestion Data, not on an API
use the init_cyclic-moving data 
variables required: 
-vehicle
-time of day
-gps location
lookup which route the vehicle was serving from the init_tripsh

## Client-side Calculations

Need to calculate vehicle speed per segment
Need to rank vehicle speeds into color codes 

## Data Sources

init_cyclic
init_tripsh

## Wireframes

I would like a geographical map, that shows all the bus routes that is colored by travel speed, that I can scroll throughout the time of day. Could show 1 day, or showing an average of a larger timeframe like a week or a month, weekdays, weekends.

Link to photo example: https://docs.google.com/presentation/d/1QJ5SfxQwRlPaHuzACUmBwOEiuwwTC1P24jDz4SmKxms/edit?usp=sharing Slide 14 and 15 of the slidedeck.

**Comment by gouldc2** [comment]
NACTO is an organization of transportation planners that produces studies, hold conferences, and has guidebooks of design options that lots of people use as a US reference for street design. I believe it stands for National Association of City Transportation Officials.

**Comment by znmeb** [comment]
Cool!

**Comment by jaronheard** [comment]
Thinking more concretely about what needs to be done for this card to become reality:
- [ ] Determine aggregation methodology for time
- [ ] Determine aggregation methodology for location
- [ ] Determine time period to use (e.g. one day, one month, entire three month period)
- [ ] Data science work to calculate average speed by time period and location
- [ ] Store data science results in PostGIS database
- [ ] Generate and deploy API from database

- [ ] Data viz and design work for map
- [ ] Front-end build

**Comment by gouldc2** [comment]
Questions
_What sort of time period increments make sense for calculating average speed? Is it something where average hourly speed would be enough?_
I dashboard I referenced showed the speed calculation on slide 13. They used the time and distance between locator pings i.e. 50meters/6.3sec 

_Calculating the rate of speed for an individual bus is straightforward enough, but how do we aggregate the average speed per vehicle location?_
You could visualize this as a series of lines for when many busses are on the same map, as a heat map for average of a location X,Y, or a discrete point for each data point (the points are close enough together on a map it might look very continuous)

I think in order to generate this visualization we need to host average speed by location and time in an API. This will require data science work.

_This is already a complex visualization, I wonder if the additional layer of separating out the routes is worthwhile. At least at the level of dealing with the flat CSV files instead of a database, this is tricky._
Routes would be valuable for people who are doing research for improvements per line, but this map would have a lot of value without routes. 

_I think this is valuable visualization - can we spell out a bit more about why it is valuable?_
When PBOT engineers on a separate project repave or re-stripe a street, they could easily reference this data in a few minutes to see if there could be an opportunity to improve bus service at that location. Currently, Trimet only publishes maps on select routes during specific projects. This tool would make collaboration easier and priorities clear.

**Comment by jaronheard** [comment]
@ben-chaney @gouldc2 I've added methodology to the checklist above. Any additional thoughts / concerns? 

@znmeb Is this fully specified enough for you? Anything else you need?

**Comment by ben-chaney** [comment]
The hexagon overlapping sounds like it could be a problem, especially if this is done once for each route and we are displaying multiple routes simultaneously.  Is the concept that one route would be shown at a time?

I'm used to seeing a hex-bin map with just one uniform grid.  Do you have an example of the hex-on-a-line style?

**Comment by znmeb** [comment]
I just started looking at this card yesterday. I'm putting the database (yes, the whole thing!) up on my workstation and with luck will have it on my laptop during the build-a-thon.

Do you know which fields you'll want from the two tables? As in a SELECT statement with a JOIN clause? That would be the first step.

**Comment by jaronheard** [comment]
Had a discussion with @geografa today about a different approach to bin things geographically. This approach would be:
Use Tri-Met route geometries (lines)
Break each route lines into line segments
Calculate a speed for each point
Assign each point to a line segment
Aggregate statistics for each line segment

**Comment by ben-chaney** [comment]
I like this approach

Thanks,
~ Ben

**Comment by znmeb** [comment]
@jaronheard @ben-chaney @geografa I'm working on the data munging for this approach at the moment. I've got the route data but I'm not using it yet.

There's a "PATTERN_DISTANCE" field in the data but

* I don't know what the units are,
* Sometimes there are missing values,
* Sometimes it isn't monotonically increasing with time.

So I dropped back to just calculating the travel times between stops. I'm filtering out short trips using a statistical cutoff but not making any attempt to overlay the path of the vehicle on the map.

Incidentally, in case you didn't know, the TriMet shapefiles are here: https://developer.trimet.org/gis

If you want to follow along the code is in an RStudio R Markdown notebook at https://github.com/hackoregon/transportation-congestion-analysis/blob/master/notebooks/loading_congestion_data.Rmd

**Comment by jaronheard** [comment]
Thinking that this will make sense as a layer in our interactive map tool!

**Comment by jaronheard** [comment]
I've updated the aggregation methodology to reflect our discussion.

**Comment by jaronheard** [comment]
This is also a Civic Sandbox layer, labelling as such. Can we get an update on where we are in the data-science > database > API process for this one?

**Comment by jaronheard** [comment]
Closing as part of post-2018 project season cleanup
