### ISSUE TITLE
Run Emotion 10 code-mod

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#544]
### What

Run Emotion 10 code-mod on all packages. This will include enabling eslint-plugin-emotion. Details below:

Automatically: The first part can be done automatically by using eslint-plugin-emotion at https://emotion.sh/docs/eslint-plugin-emotion#emotion-10-codemods. This will make the following changes:
    a. Change all react-emotion imports so that styled is imported from @emotion/styled and all the emotion exports are split into a second import.
    b. Add a css call to the css prop when a template literal is used.
    c. Add a jsx import and set jsx pragma

### Why

First step in #526

### When

Not time sensitive at the moment

**Comment by champagneabuelo** [comment]
Can I get assigned to this issue?

**Comment by jaronheard** [comment]
I assigned you! But also, I added you to the the proper team so that you can assign yourself in the future. 🙌
