### ISSUE TITLE
Remove unused deprecated components

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#545]
### What

Remove unused components marked as "deprecated" from component-library.

<img width="286" alt="image" src="https://user-images.githubusercontent.com/7065695/58055556-ec900500-7b12-11e9-88a6-0a4f1a58a6ab.png">

Please ensure the following for each deprecated component:
- [ ] The component in question is not imported from the component-library by any other packages
- [ ] Remove all files (source, test, stories) and references to component from the component-library

If a deprecated component is used in a project package, please file an issue to upgrade that component.

### Why

Removing unused components will eliminate developer confusion and trim the size of our bundles

### When

Not time sensitive

### Components identified as Deprecated (√ once removed):
- [x] Chart.js
- [x] ChartData.js
- [x] HeatMap.js
- [x] HexOverlay.js
- [x] Media.js
- [x] Sankey.js
- [x] ShareCollection.js
- [x] StoryFooter.js - used in StoryCard.js & CivicStoryCard
- [x] StoryLink.js - used in StoryFooter.js
- [x] Tag.js

**Comment by kdv24** [comment]
@jaronheard maybe I'm missing something, but when I search for "deprecated" in civic I'm not getting any hits...

**Comment by jaronheard** [comment]
@kdv24 maybe case sensitivity -- https://github.com/hackoregon/civic/search?q=deprecated&unscoped_q=deprecated

**Comment by kdv24** [comment]
yep- @jaronheard that did it.  Thanks!

**Comment by kdv24** [comment]
@jaronheard I removed the HeatMap component because it wasn't being referenced by any other components, but as I understand it now, changes were made so it _can_ be used going forward. It seems to me that I should amend my change to not remove it, and leave @mendozaline's changes.  Is there anything different that should be done with the HeatMap component?

**Comment by kdv24** [comment]
Okay, should be good to go now. @jaronheard will make issue cards for the StoryLink and StoryFooter components referenced above.

**Comment by jaronheard** [comment]
@kdv24 I reviewed your changes in #564, just a few lines to change. 

Per your comment above, I made issue #602 for the StoryLink and StoryFooter ... and then went ahead and did them myself in #604. If you're able to review #604 that would be ✨awesome✨!

**Comment by kdv24** [comment]
Looks good. And, thanks for catching the ShareCollection bit I missed too!
