### ISSUE TITLE
Portland needs affordable rental units 

### ISSUE THREAD

**Issue by danmelton** [hackoregon/civic#55]
# Story Card Request

**Project: Housing**
**Card Title: Housing Ranking Component**

## API Details

tktk

## Client-side Calculations

tktk

## Data Sources

tktk

## Wireframes

tkt

https://www.figma.com/proto/Sx4NhVdMgKdKKjPV6IEWIX7i/Dan-Test-Wireframe

![_page_1_-_dan_test_wireframe](https://user-images.githubusercontent.com/99731/39283622-f4fcf4dc-48c3-11e8-967d-6f735f90f94a.png)

**Comment by danmelton** [comment]
@adpeters Could you add our api information here and I'll update the description

**Comment by kmorrice** [comment]
Multnomah County is ranked 310 out of 3142. 
Data come from: http://apps.urban.org/features/rental-housing-crisis-map/

**Comment by christinatommeraasen** [comment]
Can we invert the data? Since the story is centered around the gap in affordable housing, the visualization will be stronger if we instead graph the housing deficit - e.g., instead of 29 available units, we've got a deficit of 71 units per 100 households.

**Comment by adpeters** [comment]
JSON Sample:
```
{
    "count": 9425,
    "next": "http://localhost:8000/api/rentalcrisis/?limit=10&offset=10",
    "previous": null,
    "results": [
        {
            "id": 1,
            "year": 2000,
            "eli_limit": "14350.00",
            "county_fips": "01001",
            "county_name": "Autauga",
            "state_name": "Alabama",
            "is_state_data": false,
            "eli_renters": "778.38",
            "aaa_units": "457.32",
            "noasst_units": "356.32",
            "hud_units": "76.00",
            "usda_units": "25.00",
            "no_hud_units": "381.32",
            "no_usda_units": "432.32",
            "aaa_units_per_100": 58.75279426501195,
            "noasst_units_per_100": 45.777126853207946,
            "hud_units_per_100": 9.763868547496081,
            "usda_units_per_100": 3.2117988643079216,
            "no_hud_units_per_100": 48.98892571751587,
            "no_usda_units_per_100": 55.54099540070403
        },
        {
            "id": 2,
            "year": 2000,
            "eli_limit": "13000.00",
            "county_fips": "01003",
            "county_name": "Baldwin",
            "state_name": "Alabama",
            "is_state_data": false,
            "eli_renters": "1581.00",
            "aaa_units": "846.00",
            "noasst_units": "307.00",
            "hud_units": "365.00",
            "usda_units": "174.00",
            "no_hud_units": "481.00",
            "no_usda_units": "672.00",
            "aaa_units_per_100": 53.51043643263757,
            "noasst_units_per_100": 19.41808981657179,
            "hud_units_per_100": 23.086654016445287,
            "usda_units_per_100": 11.005692599620494,
            "no_hud_units_per_100": 30.42378241619228,
            "no_usda_units_per_100": 42.50474383301708
        },
        etc...
    ]
}
```

**Comment by jaronheard** [comment]
Could you update with the latest details? I'd like to get the front-end team working on this since your API is ready. Please tag me once updated.

Please make sure to include the following:

- [ ] API details, including which attributes are used for the following:
- rank, including how to get both the ranking and the total
- available housing units, or deficit of available units. I'm guessing this is "aaa_units_per_100"

**Comment by kmorrice** [comment]
Alec can probably speak more to this as he set up the API. 

The rank is based on the 'aaa_units_per_100', and the rank is sorted on this column from largest to smallest for 2014. A rank of 1 indicates the most available units, and a rank of 3142 indicates the least available units. The total is the total number of counties for each respective year (e.g., 2014, 2009, 2000). We were basing our ranking above for Multnomah County (2833 out of 3142) on the 2014 data.

**Comment by adpeters** [comment]
Yeah, the available units is "aaa_units_per_100". I'll add a rank column soon.

**Comment by adpeters** [comment]
@jaronheard I updated the API sample for this one. Also added rank a total columns. If you want to filter for specific counties you can do so like this: http://45.55.145.111:8000/api/rentalcrisis/?county_name=multnomah+county

**Comment by jaronheard** [comment]
Consolidated into issue #152

**Comment by kmorrice** [comment]
As mentioned into issue #152, we would like for there to be a graphic that features the ranked location. Something like the following that indicates the number of extremely low income households and the number of AAA units available per 100 ELI households. 
![eli_households_line](https://user-images.githubusercontent.com/3445877/40860591-c992564a-659a-11e8-8a08-be373d5a6b40.png)
![aaa_units](https://user-images.githubusercontent.com/3445877/40860608-d5d8bde0-659a-11e8-9049-e850ab97c836.png)

**Comment by DingoEatingFuzz** [comment]
There are 9425 records in the `rentalcrisis` dataset. How do I fetch the neighbors of a county in order to render the ranker bar chart?

**Comment by adpeters** [comment]
Right now you would just have to fetch them all and order by rank. Would you like to be able to fetch by a rank range or something like that as well? That would be easy to add to the api.

**Comment by jaronheard** [comment]
@adpeters in my discussion with @DingoEatingFuzz, I don't think we need the rank range, but we do need what I mentioned in #152.

@DingoEatingFuzz feel free to add any corrections or clarifications here.

**Comment by adpeters** [comment]
API call for geography list: http://service.civicpdx.org/housing-affordability/api/rentalcrisis/meta/?fields=geography
