### ISSUE TITLE
Make yarn start open the browser

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#558]
### What

Make `yarn start` open the browser when the server starts in project packages, same as `yarn storybook`. This will be a change in the `dev-server` package, used by all other project packages.

### Why

Currently, running `yarn start` in a package doesn't open the browser, but `yarn storybook` does.  Changing this will make a consistent experience for development across different parts of CIVIC

### When

As soon as possible.

**Comment by corydm92** [comment]
Assigned, currently opening in a new tab but not waiting for Webpack Bundle. Linting errors were bypassed using git commit --no-verify for now, will be looking at the linting issue in the future.

**Comment by jaronheard** [comment]
#597 addressed
