### ISSUE TITLE
Affordable Rental Units are Dwindling

### ISSUE THREAD

**Issue by danmelton** [hackoregon/civic#56]
# Story Card Request

**Project: Housing**
**Card Title: Change in rental affordability**

## API Details

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround.

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## Client-side Calculations

> If the data from the API is not pre-calculated, please include all formulas here.
> e.g., `affordable = rent < monthlyIncome * 0.3`

## Data Sources

> All cards should trace back to their data origins. Include public links to those origins
> So card developers can embed the links in the card.

## Wireframes

> Include a detailed description and/or image that describes your story or visualization using
> the data described above. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> Once you have a wireframe, Include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

**Comment by kmorrice** [comment]
We have two different ranks for this, including the change in share of apartments < $800 and the change in share of apartments >$2000. Portland is ranked 11 out of 100 with regards to the change in share < $800 and is ranked 19 out of 100 with regards to the change in share > $2000. Thoughts for the visualization were to do a bar chart where the number of units for each rental bracket are shown for 2005 and 2015 (can do national or any city), and both years are shown on same plot colored by year.

**Comment by adpeters** [comment]
JSON Sample:
```
{
    "count": 100,
    "next": "http://localhost:8000/housing/api/harvardjchs/?datatype_clean=change-in-share-of-units-by-real-rent-level-20052015-real-gross-rents-under-800&limit=10&offset=10",
    "previous": null,
    "results": [
        {
            "id": 137907,
            "date": "2015-01-01",
            "datapoint": "Spokane",
            "datatype": "Change in Share of Units by Real Rent Level, 2005–2015, Real Gross Rents Under $800",
            "source": "W-16",
            "valuetype": "percentage points",
            "value": "-0.11125"
        },
        {
            "id": 137888,
            "date": "2015-01-01",
            "datapoint": "Youngstown",
            "datatype": "Change in Share of Units by Real Rent Level, 2005–2015, Real Gross Rents Under $800",
            "source": "W-16",
            "valuetype": "percentage points",
            "value": "0.02991"
        },
        {
            "id": 137868,
            "date": "2015-01-01",
            "datapoint": "Durham",
            "datatype": "Change in Share of Units by Real Rent Level, 2005–2015, Real Gross Rents Under $800",
            "source": "W-16",
            "valuetype": "percentage points",
            "value": "-0.03846"
        },
        {
            "id": 137848,
            "date": "2015-01-01",
            "datapoint": "Scranton",
            "datatype": "Change in Share of Units by Real Rent Level, 2005–2015, Real Gross Rents Under $800",
            "source": "W-16",
            "valuetype": "percentage points",
            "value": "-0.17028"
        },
        etc...
    ]
}
```

**Comment by jaronheard** [comment]
Similarly to #55, could you update with the latest details? I'd like to get the front-end team working on this since your API is ready. Please tag me once updated.

Please make sure to include the following:

- [ ] API details, including which attributes are used for the following:
-how to filter for each of the two ranking components, perhaps as specified below?
-rank, including how to get both the ranking and the total. please specify for both ranking components.
-percentage change, which I'm assuming is `value`
-location name, which I'm assuming is `datapoint`

filtering:
"datatype": "Change in Share of Units by Real Rent Level, 2005–2015, Real Gross Rents Under $800"
and 
"datatype": "Change in Share of Units by Real Rent Level, 2005–2015, Real Gross Rents Over $2000"

**Comment by adpeters** [comment]
@jaronheard Updated the API sample above. The sample is for the first filter, under $800. The link for over $2000 is http://45.55.145.111:8000/api/harvardjchs/?datatype=change-in-share-of-units-by-real-rent-level-20052015-real-gross-rents-2000-or-more. You are correct, `value` is percentage change, and `datapoint` is the location.

**Comment by adpeters** [comment]
@jaronheard I added `rank` and `total` fields to the json results.

**Comment by jaronheard** [comment]
Consolidated into issue #152

**Comment by kmorrice** [comment]
As Alec mentioned in issue #152, we would like for there to be a graphic that features the ranked location. Something like the following that indicates the percent change is what we'd like to feature. 
![percent_change_rentals](https://user-images.githubusercontent.com/3445877/40862025-03dc6fb6-65a0-11e8-996a-0464e23f5002.png)

**Comment by adpeters** [comment]
The API call for the above chart is: http://45.55.145.111:8000/api/harvardjchs/?datatype=change-in-share-of-units-by-real-rent-level-2005-2015-real-gross-rents&datapoint=portland&limit=14

**Comment by adpeters** [comment]
API call to get all geographies: http://service.civicpdx.org/housing-affordability/api/harvardjchs/meta/?datatype=change-in-share-of-units-by-real-rent-level-2005-2015-real-gross-rents-under-800&fields=geography

**Comment by kmorrice** [comment]
@adpeters and @DingoEatingFuzz it looks like he API call is pulling 'Change in Share of Units by Real Rent Level" for 
-Real Gross Rents $2,000 or more (id 49116)
-Real Gross Rents $800 or more (id 49140)

These are binned categories, and not meant to be included here. Alec, is this something that can be easily changed in the API call? Is there an easy way that they can be filtered out?

**Comment by adpeters** [comment]
@kmorrice Ok I fixed the ranking, it says 90 now. Filtering out the other two categories in the API call is harder though, since we want to include them in some of the results but not those. I think it would be easier to filter them out on the front-end side, but if we need to do it on the backend it could be done too.

**Comment by kmorrice** [comment]
Thanks @adpeters. I think filtering them on the front-end sounds like the best option since they're used in the ranking. This had been brought up yesterday, so it's on their radar, but just wanted to circle back to see what best steps moving forward were.
