### ISSUE TITLE
Design System - Update ScatterPlot Map Stories

### ISSUE THREAD

**Issue by mendozaline** [hackoregon/civic#567]
## What
**What needs to be done?**

**Standard**
- [x] Rename"Simple Usage" story to "Standard" story
- [x] Create knobs for each of these standard props and group as marker:
-`getFillColor`
-`getRadius`
-`opacity `
- [x] Create knobs for each of these standard props and group as data:
-`data`
-~~`getPosition`~~

**Custom**
- [x] Create "Custom" story 
- [x] Create knobs for each of these custom props and group as custom:
-`stroked`
-`getLineColor`
-`getLineWidth`
-`autoHighlight`
-`highlightColor`
-`onLayerClick`

**Example**
- [x] Rename "With tooltip" story to "Examples: With Tooltip" story

**Notes**
- [x] Add ScatterPlot Map Notes file

## Why
**Why does it need to be done? (Include links to related issues)**
Scatter Plot Map stories should follow the Civic design system pattern established in  [#508](https://github.com/hackoregon/civic/pull/508), [#553](https://github.com/hackoregon/civic/pull/553), and [#565](https://github.com/hackoregon/civic/pull/565). Please references these files:

**Button Component**
-[Button Stories File](https://github.com/hackoregon/civic/blob/master/packages/component-library/stories/Button.story.js)
-[Button Notes File](https://github.com/hackoregon/civic/blob/master/packages/component-library/stories/button.notes.md)

**Bar Chart Component**
-[Bar Chart stories](https://github.com/hackoregon/civic/blob/master/packages/component-library/stories/BarChart.story.js)
-[Bar Chart notes ](https://github.com/hackoregon/civic/blob/master/packages/component-library/stories/barchart.notes.md)

**Horizontal Bar Chart Component**
-[Horizontal Bar Chart stories](https://github.com/hackoregon/civic/blob/f7dcbc59a221df811d26d0133dd1b81929bb6761/packages/component-library/stories/HorizontalBarChart.story.js)
-[Horizontal Bar Chart notes](https://github.com/hackoregon/civic/blob/f7dcbc59a221df811d26d0133dd1b81929bb6761/packages/component-library/stories/horizontalBarChart.notes.md)

## When
**When does this need to be done?**
In the near future

**Comment by paigewilliams** [comment]
@jaronheard @mendozaline We are currently using data driven fill color, would we like to keep that, or would we rather have a single fill color? If we want to keep the fill color data driven, would we like to have a select knob for a color scheme similar to the color scheme for the path map story? Thanks!!

**Comment by jaronheard** [comment]
I’ll yield to @mendozaline here for thoughts. Let me know what you think!

Jaron Heard
Creative Director
Civic Software Foundation

+1-971-998-7180

**Comment by mendozaline** [comment]
1). In the "Standard" story, the fill color for the circle shouldn't be data driven. It should be a single color array input using the object knob.

So something like this:
`const getFillColor = object('Fill Color:', [114, 29, 124], GROUP_IDS.MARKER);`

This would make it clearer to the developer what is actually being passed to the 'getFillColor' prop in a simple use case. 

2). But there should also be an "Example" story where we show how a developer could use a value from a feature's properties object to determine the color, radius, etc of the circles. 


In general, I think that the "Standard" story should be kept as simple as possible with only the essential props used in the most basic way. The "Example" stories can be used to show more specific and complex options.

**Comment by mendozaline** [comment]
Addressed by #583
