### ISSUE TITLE
Design System - Update Path Map Stories

### ISSUE THREAD

**Issue by paigewilliams** [hackoregon/civic#568]
## What
**What needs to be done?**

**Standard**
- [x] Rename"Simple Usage" story to "Standard" story
- [x] Create knobs for each of these standard props and group as marker:
-`getColor`
-`getWidth`
-`opacity `

- [x] Create knobs for each of these standard props and group as data:
-`data`
-<strike>`getPath`</strike>

**Custom**
- [x] Create "Custom" story 
- [x] Create knobs for each of these custom props and group as custom:
-`rounded`
-`autoHighlight`
-`highlightColor`
-`onLayerClick`

**Example**
- [x] Rename "With tooltip" story to "Examples: With Tooltip" story

**Notes**
- [x] Add PathLayer Map Notes file

## Why
**Why does it need to be done? (Include links to related issues)**
PathLayer Map stories should follow the Civic design system pattern established in  [#508](https://github.com/hackoregon/civic/pull/508), [#553](https://github.com/hackoregon/civic/pull/553), and [#565](https://github.com/hackoregon/civic/pull/565). Please references these files:

**Button Component**
-[Button Stories File](https://github.com/hackoregon/civic/blob/master/packages/component-library/stories/Button.story.js)
-[Button Notes File](https://github.com/hackoregon/civic/blob/master/packages/component-library/stories/button.notes.md)

**Bar Chart Component**
-[Bar Chart stories](https://github.com/hackoregon/civic/blob/master/packages/component-library/stories/BarChart.story.js)
-[Bar Chart notes ](https://github.com/hackoregon/civic/blob/master/packages/component-library/stories/barchart.notes.md)

**Horizontal Bar Chart Component**
-[Horizontal Bar Chart stories](https://github.com/hackoregon/civic/blob/f7dcbc59a221df811d26d0133dd1b81929bb6761/packages/component-library/stories/HorizontalBarChart.story.js)
-[Horizontal Bar Chart notes](https://github.com/hackoregon/civic/blob/f7dcbc59a221df811d26d0133dd1b81929bb6761/packages/component-library/stories/horizontalBarChart.notes.md)

## When
**When does this need to be done?**
In the near future

**Comment by mendozaline** [comment]
Addressed by #589
