### ISSUE TITLE
Who can afford to buy a home in America?  

### ISSUE THREAD

**Issue by danmelton** [hackoregon/civic#57]
# Story Card Request

**Project: Housing**
**Card Title: Median Home Price Median Income Ratio - TBD**

## API Details

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround.

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## Client-side Calculations

> If the data from the API is not pre-calculated, please include all formulas here.
> e.g., `affordable = rent < monthlyIncome * 0.3`

## Data Sources

> All cards should trace back to their data origins. Include public links to those origins
> So card developers can embed the links in the card.

## Wireframes

> Include a detailed description and/or image that describes your story or visualization using
> the data described above. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> Once you have a wireframe, Include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

**Comment by kmorrice** [comment]
In 2016, Portland is ranked 34 out of 382. Thoughts on visualization is to show the time series for Portland, but user could select other cities.

**Comment by adpeters** [comment]
JSON Sample: 
```
{
    "count": 382,
    "next": "http://localhost:8000/housing/api/harvardjchs/?datatype_clean=median-home-price-to-median-income-ratio&date=2016-01-01&limit=10&offset=10",
    "previous": null,
    "results": [
        {
            "id": 120573,
            "date": "2016-01-01",
            "datapoint": "United States",
            "datatype": "Median Home Price-to-Median Income Ratio",
            "source": "W-12",
            "valuetype": "ratio",
            "value": "4.08429"
        },
        {
            "id": 120600,
            "date": "2016-01-01",
            "datapoint": "Abilene, TX",
            "datatype": "Median Home Price-to-Median Income Ratio",
            "source": "W-12",
            "valuetype": "ratio",
            "value": "3.30307"
        },
        {
            "id": 120627,
            "date": "2016-01-01",
            "datapoint": "Akron, OH",
            "datatype": "Median Home Price-to-Median Income Ratio",
            "source": "W-12",
            "valuetype": "ratio",
            "value": "2.30110"
        },
        {
            "id": 120654,
            "date": "2016-01-01",
            "datapoint": "Albany, GA",
            "datatype": "Median Home Price-to-Median Income Ratio",
            "source": "W-12",
            "valuetype": "ratio",
            "value": "2.58726"
        },
        etc...
    ]
}
```

**Comment by kmorrice** [comment]
Additional information for context: 

Portland is ranked 34 with a ratio of 5.25. The ratio for the US is 4.08. 
Metropolitan Areas that are ranked closely to us:
31: Santa Fe, NM
32: Reno, NV
33: Denver-Aurora-Lakewood, CO

Metropolitan Areas below us include:
35: Seattle-Tacoma-Bellevue, WA
36: Bend-Redmond, OR
37: Hilton Head Island-Bluffton-Beaufort, SC

Metropolitan Areas in Oregon that make the list:
17: Grants Pass, OR
21: Corvallis, OR
23: Medford, OR
34: Portland-Vancouver-Hillsboro, OR
36: Bend-Redmond, OR
47: Eugene, OR
67: Albany, OR
71: Salem, OR

**Comment by jaronheard** [comment]
Similarly to #55, could you update with the latest details? I'd like to get the front-end team working on this since your API is ready. Please tag me once updated.

Please make sure to include the following:

- [ ] API details, including which attributes are used for the following:
- rank, including how to get both the ranking and the total
- Median Home Price-to-Median Income Ratio, which I'm assuming is `value`
- location name, which I'm assuming is `datapoint`

**Comment by kmorrice** [comment]
The rank is based on the value field for the date '2016-01-01'. The total rank is the number of metropolitan areas represented in the data set (381). Location is datapoint.

**Comment by adpeters** [comment]
@jaronheard I've updated the API sample above. And you are correct about the `value` and `datapoint` fields.

**Comment by adpeters** [comment]
@jaronheard I added `rank` and `total` fields to the json results.

**Comment by jaronheard** [comment]
Consolidated into issue #152

**Comment by kmorrice** [comment]
As mentioned in issue #152, we would like for there to be a graphic that features the ranked location as well as the United States. Something like the following that shows a time series of the median home price-to-median income ratios would work well. 
![mhp_mir](https://user-images.githubusercontent.com/3445877/40862572-c4b4cfe8-65a1-11e8-82d9-4f1139ae14a3.png)

**Comment by adpeters** [comment]
API call for geography list: http://service.civicpdx.org/housing-affordability/api/harvardjchs/meta/?datatype=median-home-price-to-median-income-ratio&fields=geography

**Comment by DingoEatingFuzz** [comment]
@adpeters, the expected value for `datapoint` isn't simply the geography. It seems to be a slugified version of it.

Is there any rule beyond lowercase it, remove punctuation, and use hyphens instead of spaces?

**Comment by DingoEatingFuzz** [comment]
I'm moving forward with an implementation of django's slugify util (https://docs.djangoproject.com/en/2.0/_modules/django/utils/text/#slugify). Lemme know if I should be doing something different!
