### ISSUE TITLE
Pacific Northwest tops the Nation in Surging Home Prices

### ISSUE THREAD

**Issue by danmelton** [hackoregon/civic#58]
# Story Card Request

**Project: Housing**
**Card Title: Change in Home Prices 2000-2016**

## API Details

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround.

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## Client-side Calculations

> If the data from the API is not pre-calculated, please include all formulas here.
> e.g., `affordable = rent < monthlyIncome * 0.3`

## Data Sources

> All cards should trace back to their data origins. Include public links to those origins
> So card developers can embed the links in the card.

## Wireframes

> Include a detailed description and/or image that describes your story or visualization using
> the data described above. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> Once you have a wireframe, Include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

https://www.figma.com/proto/Sx4NhVdMgKdKKjPV6IEWIX7i/Housing-Card-Wireframes?scaling=contain&node-id=69%3A196

**Comment by kmorrice** [comment]
Portland is ranked number 17 out of 136. Need to think about the ranking for this one because the data include Metros as well as Metro divisions.

**Comment by adpeters** [comment]
JSON Sample:
```
{
    "count": 120,
    "next": "http://localhost:8000/housing/api/harvardjchs/?datatype_clean=real-percent-change-in-home-prices-from-troughdec2016&limit=10&offset=10",
    "previous": null,
    "results": [
        {
            "id": 96805,
            "date": "2016-12-01",
            "datapoint": "Winston-Salem, NC",
            "datatype": "Real Percent Change in Home Prices from Trough–Dec.2016",
            "source": "W-7",
            "valuetype": "2016 dollars",
            "value": "12.00152"
        },
        {
            "id": 96792,
            "date": "2016-12-01",
            "datapoint": "Wichita, KS",
            "datatype": "Real Percent Change in Home Prices from Trough–Dec.2016",
            "source": "W-7",
            "valuetype": "2016 dollars",
            "value": "11.74380"
        },
        {
            "id": 96780,
            "date": "2016-12-01",
            "datapoint": "Washington-Arlington-Alexandria, DC-VA-MD-WV Metro Division",
            "datatype": "Real Percent Change in Home Prices from Trough–Dec.2016",
            "source": "W-7",
            "valuetype": "2016 dollars",
            "value": "20.48782"
        },
        {
            "id": 96768,
            "date": "2016-12-01",
            "datapoint": "Silver Spring-Frederick-Rockville, MD Metro Division",
            "datatype": "Real Percent Change in Home Prices from Trough–Dec.2016",
            "source": "W-7",
            "valuetype": "2016 dollars",
            "value": "13.59363"
        },
        etc...
    ]
}
```

**Comment by adpeters** [comment]
@jaronheard I updated the API sample above. You are correct, `value` is the percent change and `datapoint` is the location. Will add a `rank` field.

**Comment by adpeters** [comment]
@jaronheard I added `rank` and `total` fields to the json results.

**Comment by jaronheard** [comment]
Consolidated into issue #152

**Comment by adpeters** [comment]
We would like to rank by the Data Type = "real-percent-change-in-home-prices-from-dec-2015dec-2016".

**Comment by adpeters** [comment]
API call for geography list: http://service.civicpdx.org/housing-affordability/api/harvardjchs/meta/?datatype=real-percent-change-in-home-prices-from-dec-2015dec-2016&fields=geography

**Comment by kmorrice** [comment]
@jaronheard we had been talking about making an additional graphic for this, and I think something like this would work. It compares the percent change in home prices from 2000-2016 with the percent change in home prices from 2015-2016, so capturing long-term change against recent short-term change. On the x-axis, we would have  Data Type = "real-percent-change-in-home-prices-from-jan-2000dec-2016" and on the y-axis, we would have Data Type = "real-percent-change-in-home-prices-from-dec-2015dec-2016"

![percent_change_home_prices](https://user-images.githubusercontent.com/3445877/41630189-9d3370ec-73e2-11e8-9bc6-b3a44b0da3e5.png)
