### ISSUE TITLE
Lint convenience packages

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#592]
### What

Fix all linting errors in the following packages:
- [ ] civic-babel-presets
- [ ] dev-server
- [ ] mock-wrapper
- [ ] webpack-common

This is a great opportunity to knock out an issue and familiarize yourself with CIVIC's convenience packages.

### Why

Improve code quality (#515)

### When

Not time sensitive, but as soon as possible

**Comment by davidfloyd91** [comment]
happy to take this one if it's available

**Comment by jaronheard** [comment]
@davidfloyd91 It's available! Go for it 🙌🙌 

Let me know if you have any questions as you're working through it. 

I've assigned myself to the issue to make sure nobody else takes it on.

**Comment by davidfloyd91** [comment]
@jaronheard there's one line that's giving me trouble, in `packages/dev-server/index.js`:

`const config = require(resolve(process.cwd(), "webpack.config.js"));`

This throws a `Calls to require() should use string literals` error (rule: `import/no-dynamic-require`), but I'm not sure what the string should be. I don't see a `webpack.config.js` anywhere. I'm guessing `packages/webpack-common/index.js` serves the same purpose? It _looks_ like a webpack config file ...

**Comment by jaronheard** [comment]
@davidfloyd91 Yep, `packages/webpack-common/index.js` is our common webpack config file, so it should be using that, I think.

**Comment by davidfloyd91** [comment]
@jaronheard I believe I've got these taken care of. I'm wondering what I should do to on my end to make sure I didn't break anything, prior to submitting a PR. 

So far I've run `yarn test` (all passing except for 4 pending). 

Really the only thing I'm nervous about is that I added dependencies to some of the packages (to solve `import/no-extraneous-dependencies`). It's yarn, so I'm less worried, but I still don't want to introduce some gnarly dependency version issue somewhere.

**Comment by jaronheard** [comment]
@davidfloyd91 Awesome! Sounds great. Running the tests should be enough to make sure you haven't broken anything. I'll check out the dependency changes -- I was doing a bunch of dependency work in #423 so I should be able to give the diff a look to see if it's right. 

Another check you can do us to If you feel like running the 2018 package, that's what deploys to civicplatform.org

**Comment by davidfloyd91** [comment]
Afraid running 2018 didn't work. Changing the line I mentioned above in `packages/dev-server/index.js` to `const config = require("../webpack-common/index.js");` broke it. I see what that's doing now -- I'd missed the `webpack.config.js` file in `packages/2018`. And elsewhere. 

Changing that line back to `const config = require(resolve(process.cwd(), "webpack.config.js"));` fixes it but makes the linter angry. I'm reading around but at the moment I can't think of a good way to avoid the dynamic require without making things a lot more complicated.

**Comment by jaronheard** [comment]
@davidfloyd91 I think it's fine to es-lint ignore that error for that line -- I think it's a spot where the dynamic require might be necessary

**Comment by davidfloyd91** [comment]
Ok opened a PR. Looks like there are merge conflicts, wasn't sure if I should pull changes from master beforehand or not, but happy to close the PR and do that if needed
