### ISSUE TITLE
Build react-map-gl component

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#62]
We are moving from leaflet to using mapbox, react-map-gl and deck.gl

This map will be the basic map for our visualization to be built on.
MORE DETAILS ON MAP TILES, DEFAULTS, ETC

Todo:
- [ ] Add necessary dependencies
- [ ] Write the ReactMap component
- [ ] Add unit tests
- [ ] Update the ReactMap story

**Comment by jaronheard** [comment]
Building a basic map component with these technologies can be started on.

**Comment by znmeb** [comment]
Is there a guide on what MapBox needs from APIs and / or databases?

**Comment by DingoEatingFuzz** [comment]
mapbox-gl-js uses either a vector tile server or a geojson object. I suspect we will only be using geojson.

Read more here: https://www.mapbox.com/mapbox-gl-js/api/

**Comment by znmeb** [comment]
Thanks!!

**Comment by jaronheard** [comment]
#114 addresses!
