### ISSUE TITLE
Upgrade react-router from v3 to v5

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#637]
### What

Update [react-router](https://github.com/ReactTraining/react-router) from v3 to v5.

Here's an [unofficial migration guide](https://codeburst.io/react-router-v4-unofficial-migration-guide-5a370b8905a) from v3 to v4. There's also a less detailed [official migration guide](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md). No additional changes are needed to upgrade from v4 to v5.

> But that’s not a small change. Migrating an existing app to v4 will take at least a couple hours, up to a couple days.

### Why

This is [blocking us from upgrading to Redux 7.1](https://github.com/reduxjs/react-redux/issues/1210) for Redux hooks and is also preventing us from using new React features such as React.Suspense and React.Memo.

### When

Not time sensitive, but as soon as possible

**Comment by garretjames** [comment]
After research and some implementation there is a choice we need to make about the router-redux integration.

I was able to update `react-router` (which is now called `react-router-dom`) to v5. And refactor the routes.

The routes are connected to `redux` via `react-router-redux` which is no longer maintained -- however `"react-router-redux": "^5.0.0-alpha.9"` which is the latest works fine for redux-router connection.

The advice via [React-Router](https://reacttraining.com/react-router/web/guides/redux-integration) is not to keep routes in the store at all though if we must, the new package for doing this is [connected-react-router](https://github.com/supasate/connected-react-router) 

So there are three options:

1) Keep `"react-router-redux": "^5.0.0-alpha.9"`  and hope nothing breaks in the future :(
2) Decouple the routes from redux.
3) Replace `"react-router-redux"` with `"connected-react-router"`

**Comment by jaronheard** [comment]
@garretjames -- I'd say, pick one of options 2 or 3.

My preference is 3, to use `connected-router-redux`, given that seems like the solution that will keep us moving more quickly.

That said, I don't have a great feeling on how much extra work it would be decouple routes from Redux, and what the advantages are of that approach, so if you or anyone else has a strong opinion please chime in!

**Comment by jaronheard** [comment]
@garretjames I discussed with @DingoEatingFuzz and he agreed with `connected-router-redux` as the best solution for this.

**Comment by jaronheard** [comment]
The latest release of react-router v3 update supports all of the features mentioned in the "why" of this issue:
https://github.com/ReactTraining/react-router/pull/6806

Going to close this issue for now and update to the latest v3.

> This is blocking us from upgrading to Redux 7.1 for Redux hooks and is also preventing us from using new React features such as React.Suspense and React.Memo.
