### ISSUE TITLE
Create a common VictoryTheme 

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#64]
We should create a common VictoryTheme for our data visualization components to match this style:

<img width="859" alt="screen shot 2018-04-30 at 7 19 14 pm" src="https://user-images.githubusercontent.com/7065695/39458754-bdbede86-4cab-11e8-9113-f70cadfa95e2.png">

<img width="806" alt="screen shot 2018-04-30 at 7 21 05 pm" src="https://user-images.githubusercontent.com/7065695/39458745-b7e660ce-4cab-11e8-9e99-ea99cad948b1.png">

<img width="807" alt="screen shot 2018-04-30 at 7 20 40 pm" src="https://user-images.githubusercontent.com/7065695/39458746-b7fa97ec-4cab-11e8-813a-fe30f2b60e61.png">

@danieltomasku

**Comment by AlexanderNull** [comment]
Done!
