### ISSUE TITLE
Build a common tooltip component in VictoryCharts

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#65]
A common tooltip component needs to be written to integrate with our barchart (#44), scatterplot (#49), line chart (#48), and pie / doughnut chart (#50)

https://formidable.com/open-source/victory/guides/tooltips/

The tooltip should highlight the selected data point and show more detailed information.
Examples:
<img width="308" alt="hb no toolkit" src="https://user-images.githubusercontent.com/7065695/39613184-4f54cd68-4f1a-11e8-8cb2-fb6b1591e0aa.png">
<img width="302" alt="hb toolkit" src="https://user-images.githubusercontent.com/7065695/39613185-4f6bef16-4f1a-11e8-9aca-e7b72469616d.png">
<img width="515" alt="lc no tooltip" src="https://user-images.githubusercontent.com/7065695/39613364-7e1e1310-4f1b-11e8-9180-657f043ddae6.png">
<img width="514" alt="lc tooltip" src="https://user-images.githubusercontent.com/7065695/39613365-8184b02c-4f1b-11e8-9376-7f001c39f845.png">
<img width="530" alt="sp no tooltip" src="https://user-images.githubusercontent.com/7065695/39613188-4fcc3d62-4f1a-11e8-8e9a-4e54b87348fb.png">
<img width="520" alt="sp tooltip" src="https://user-images.githubusercontent.com/7065695/39613189-4fe2d91e-4f1a-11e8-831f-559a392fd60e.png">
<img width="517" alt="vb no toolkit" src="https://user-images.githubusercontent.com/7065695/39613190-4ffb2942-4f1a-11e8-9949-88b23a262863.png">
<img width="501" alt="vb tooltip" src="https://user-images.githubusercontent.com/7065695/39613191-50243256-4f1a-11e8-98b1-438af485db24.png">

Todo:
  Add VictoryCharts as a dependency
  Write the VictoryTooltip component
  Add unit tests
  Update the VictoryTooltip story

**Comment by jaronheard** [comment]
Some potential implementation details:
You can also use a voronoi diagram to precompute a mapping of regions to closest points, then use that for hover/click targets

VictoryCharts also probably has something built in
yep: https://formidable.com/open-source/victory/docs/victory-voronoi/

They even have circular svg clipping to enforce a max distance from target: https://formidable.com/open-source/victory/docs/victory-voronoi/#size

**Comment by DingoEatingFuzz** [comment]
In the scatter plot tooltip, shouldn't the name be included in addition to the X and Y values? The example plots concerts. Hovering over a point shows the revenue and attendees, but what about the concert name?

**Comment by jaronheard** [comment]
Yes, good point, at least for this example it’d make sense to show name,
and probably in most cases. I’ll follow up with an updated design image but
imagine that name would be listed first in the tooltip.

**Comment by BJHunnicutt** [comment]
Is it ok if the tooltip is a separate component rendered outside the chart, possibly in something like the ChartContainer? 

Since each tooltip has a variable width I’ve had trouble figuring out how to center it using just Victory’s tooltip methods. My 2 workarounds were to either pull in the react-measure library to get the exact width and place it in the chart mathematically, or pass the tooltip to the ChartContainer where centering it is super easy. The container option would also require the legend to be rendered as part of the container since the tooltip needs to fully cover the legend (which is also a variable width).

**Comment by BJHunnicutt** [comment]
@jaronheard Should 'Rock' be part of the scatterplot tooltip? If so, where do you want it to go?

**Comment by jaronheard** [comment]
@BJHunnicutt I think per Micheal's comment above, I think the tooltip should actually take in concert name from the point, and not show the classification of "Rock" or "Hip Hop".

Like so:
Led Zeppelin | Revenue: $7,000 Attendees: 260

**Comment by jaronheard** [comment]
#207 addressed.
