### ISSUE TITLE
[FEEDBACK] demo-card

### ISSUE THREAD

**Issue by benlawrence-rhie** [hackoregon/civic#659]
# Story Card Improvement

**How could this card be better?**
Can we add quotes to:
The list of tools and practices that have been used to inhibit the prosperity of people of color is lengthy: Jim Crow laws, racialized mortgagelending practices, restrictive covenants and deeds, public works projects condemning entire Black neighborhoods, and zoning rules that reinforce segregation are only a few to be named.

It comes from: https://www.portlandoregon.gov/bps/article/700970

**Additional context**

Add any other context or screenshots

**Comment by jaronheard** [comment]
Closed via #738
