### ISSUE TITLE
Add a platform-wide number formatting utility to the component library

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#67]
A common number formatting utility needs to written and integrated into the component library.  It should take a number and format it to a set of platform wide-specifications. It should support multiple platform-wide presets. This number formatter should be a more restrictive interface that just uses d3-format underneath it.

- [x] Determine rules for a few number presets
- [x] Write the number-formats utility - see comment below for architectural details
- [x] Add unit tests

**Original context below:**
I think we should create a number formatter to ensure consistent display of numbers across our platform. Originally, I was thinking this would be useful for data visualizations, but I think that it would be useful across the platform. I think that this should be a component or something that lives on the platform and can be updated.

It should take a number and format it to a set of platform wide-specifications. It should support multiple platform-wide presets.

There should be some way to indicate the precision - or number of significant digits.

I'm not sure on the technological architectural details, so if someone has an idea on how this should work, please chime in. There may be a tool that we can use with common presets across our projects.

For a basic data visualization preset, use the following guidelines:
* Commas
    * Always use commas for thousands separator
* Numbers and decimal places
    * Use units that will result in showing a maximum of 6 digits
        * Fewer digits is better
    * Lean towards showing 0-1 decimal places. 
        * Should reflect the precision of the data
        * Show whole dollars or dollars and cents (e.g. $123 or $1.23)
    * Examples
        * $7.3 million, not $7,300,000
        * 24%, not 23.79%
        * $535,000
* Show units (e.g. dollar sign, percent)

Thoughts? @DingoEatingFuzz

**Comment by DingoEatingFuzz** [comment]
I think this is a good idea. Already present in some places is the use of [`d3-format`](https://github.com/d3/d3-format) to do things like commas and significant digits.

It might be nice to create a `utils/number-formats` that can be used as a more restrictive interface that just uses `d3-format` underneath it.

e.g.,

```js
import { number, percent } from '@hackoregon/component-library/utils/number-formats';

let count = 7300000;
let countText = number(count); // 7.3 million

let pct = 0.2379;
let pctText = percent(pct); // 24%
```

With the implementation of `number-formats` looking something like

```js
import { format } from 'd3-format';
export const percent = d3.format(".0%"); // returns a function that takes a number and returns a string
```

**Comment by jaronheard** [comment]
#96 addressed this.
