### ISSUE TITLE
SliderWithTooltip broken on StoryBook

### ISSUE THREAD

**Issue by Dianna** [hackoregon/civic#676]
## Description

`SliderWithTooltip` component does not work

![broken-slider](https://user-images.githubusercontent.com/10056079/61843297-fce49900-ae4f-11e9-8fc1-859017556a04.gif)

### Steps to reproduce

[Try it here](https://hackoregon.github.io/civic/?path=/story/component-lib-basic-inputs-slider--slider-with-tooltip) in production

### Expected result

The user should be able to drag the slider and the value in the "knobs" section below should update.

### Actual result

The slider can't be dragged and the value doesn't update

### Environment

In production and running locally

**Comment by BJHunnicutt** [comment]
Doing this real quick because I know what it is. You stopped being able to set the value of controlled form components with a knob when we updated to Storybook 5.
