### ISSUE TITLE
Add Transportation project

### ISSUE THREAD

**Issue by clemf** [hackoregon/civic#7]
See #5

**Comment by DavideDaniel** [comment]
addressed here: https://github.com/hackoregon/civic/pull/5

**Comment by MikeTheCanuck** [comment]
As of #37 (or perhaps previously), `transportation` package is included and will run without errors when following the current README, whose command sequence is this:

```
nvm use
yarn bootstrap
yarn build
cd packages/emergency-response
yarn start
```
