### ISSUE TITLE
[Hold] -> Transportation: What Kind of Network is Trimet?

### ISSUE THREAD

**Issue by ben-chaney** [hackoregon/civic#70]
# Story Card Request

**Project:** Transportation Systems
**Card Title:** What Kind of Network is Trimet (alt The Shape of the Trimet Network)

## Description / Wireframe
A network graph showing transit stops as nodes and vehicle trips from one stop to another as edges.  This could be colored by type (max, frequent service, non-frequent service), by neighborhood, by equity index, etc.  Edge weights could include number of trips, number of people, total delay time, geographic distance, etc.  

Standard network summary statistics using OSMnx could be provided and used to describe the "character" of the network relationships.  Example - centrality, betweenness, loops...

> Include a detailed description and/or image that describes your story or visualization using
> the data described above. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> If you have a wireframe, include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

## Context
The design and shape of a transit network is an important part of understanding how it serves users, and what type of service has been prioritized.  Hub and spoke vs. grid networks, backbone service vs. expansive coverage, etc.

The network graph format enables a discussion of the connections between places and travel patterns that is not necessarily geographically-bounded.

> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)
Trimet congestion with number of passengers.

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround.

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## Client-side Calculations

> If the data from the API is not pre-calculated, please include all formulas here.
> e.g., `affordable = rent < monthlyIncome * 0.3`

## Data Sources

> All cards should trace back to their data origins. Include public links to those origins.
> In addition, any calculations on the source data should be described.

**Comment by kiniadit** [comment]
possibly could be merged with https://github.com/hackoregon/civic/issues/47

**Comment by jaronheard** [comment]
Closing as part of post-2018 project season cleanup
