### ISSUE TITLE
[Hold] -> Transportation: The End of Free Transit

### ISSUE THREAD

**Issue by ben-chaney** [hackoregon/civic#71]
# Story Card Request

**Project:** Transportation
**Card Title:** The End of Free Transit

## Description / Wireframe
Portland once had free transit throughout downtown, the legendary "Fareless Square."  But that all ended [when?], during the massive re-working of Trimet's fare structure that removed zones and switches to a flat rate ticket. 

What was the impact of this policy change?

Visualization ideas:
- map with graduated icons or hex-bin, showing change in ridership before vs after.
- line chart with all lines as individual series, focusing on change in ridership before vs. after

> Include a detailed description and/or image that describes your story or visualization using
> the data described above. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> If you have a wireframe, include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

## Context
TBD 

> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)
Trimet Ridership Census

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround.

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## Client-side Calculations

> If the data from the API is not pre-calculated, please include all formulas here.
> e.g., `affordable = rent < monthlyIncome * 0.3`

## Data Sources

> All cards should trace back to their data origins. Include public links to those origins.
> In addition, any calculations on the source data should be described.

**Comment by gouldc2** [comment]
Can I upvote this? :)

**Comment by code-farmhouse** [comment]
A zoom in feature of the Service Area over Time Card [47](https://github.com/hackoregon/civic/issues/47).

**Comment by jbeyer16** [comment]
This is an "event"... other "events" :
- Arrival of Uber
- Fare duration increase from 2 - 2.5 hours.

more?

**Comment by jaronheard** [comment]
Closing as part of post-2018 project season cleanup
