### ISSUE TITLE
Add knob to Map in storybook to adjust the angle the map is viewed at

### ISSUE THREAD

**Issue by Dianna** [hackoregon/civic#736]
**Is your feature request related to a problem? Please describe.**
For the disaster team's OMSI game we wanted to demonstrate how the map would look at an angle for our design team, but this wasn't possible on storybook.

**Describe the solution you'd like**
We'd like to be able to adjust the angle the map is viewed at

**Describe alternatives you've considered**
This is just a helpful feature for dev-design collaboration

**Comment by jaronheard** [comment]
BaseMap custom story has this parameter -- Initial Pitch
https://hackoregon.github.io/civic/?path=/story/component-lib-maps-base-map--custom

We may want the ability to pass a custom Mapbox layer url to BaseMap, I'll open a new issue for that.
