### ISSUE TITLE
WIP -> Transportation: The Relationship between Service Frequency and Ridership

### ISSUE THREAD

**Issue by ben-chaney** [hackoregon/civic#74]
# Story Card Request

**Project:** Transportation
**Card Title:** The Relationship between Service Frequency and Ridership

## Description / Wireframe
For each transit station / bus stop, how does the service frequency (average number of vehicles per weekday/weekendday) relate to the ridership (average number of boardings or alightings). 

 > Include a detailed description and/or image that describes your story or visualization using
> the data described above. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> If you have a wireframe, include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

## Context
Does more frequent service encourage or maintain high levels of ridership? Is Trimet responsive to add new service capacity where there is high unmet demand? It would be hard to distinguish any cause-and-effect order from this without a long timeframe of data.

> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround.

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## Client-side Calculations

> If the data from the API is not pre-calculated, please include all formulas here.
> e.g., `affordable = rent < monthlyIncome * 0.3`

## Data Sources

> All cards should trace back to their data origins. Include public links to those origins.
> In addition, any calculations on the source data should be described.

**Comment by jbeyer16** [comment]
For actual frequency, we'll need vehicle data, which I think we could only get from the congestion dataset. For scheduled, we can possibly get that based on time schedules? Although they would change over time as well.

**Comment by jbeyer16** [comment]
Based on the archived GTFS data, we could potentially get a scheduled frequency (stops per day, or more granular stops per time period of a day), from 2008 onward. It'd take a bit of scraping together from the data files (I volunteer @myself to do it) if we think it'd be worth it, but I believe we have the data we need (based on the route descriptions, stop times, and trip info).

**Comment by jaronheard** [comment]
@jbeyer16 How's the frequency data gathering going?

**Comment by jbeyer16** [comment]
@jaronheard  @znmeb convinced me my methods were not ideal to gather the data at scale, so he mentioned he'd take a look at it. Therefore, I yielded my responsibilities to him. If progress still needs to be made, I can jump back in on it.

**Comment by jaronheard** [comment]
@znmeb any progress on gathering frequency data or should @jbeyer16 jump back on it?

**Comment by jaronheard** [comment]
I think this is not a sandbox layer, but we need some more detail on what visualization type this is.

**Comment by jaronheard** [comment]
Closing as part of post-2018 project season cleanup
