### ISSUE TITLE
WIP -> Transportation: Origins and Destinations

### ISSUE THREAD

**Issue by ben-chaney** [hackoregon/civic#76]
# Story Card Request

**Project:** Transportation
**Card Title:** Origins and Destinations

## Description / Wireframe
Hex-bin choropleth map showing ratio of boardings to alightings, divided into a few different time periods (hourly?) through animation.  (congestion data)

ALTERNATIVE - 
Hex-bin choropleth map showing ratio of boardings to alightings, divided into a few different time periods (yearly) through animation.  (ridership data) Might be harder to do if most of the bins are roughly balanced over the course of a day.

> Include a detailed description and/or image that describes your story or visualization using
> the data described above. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> If you have a wireframe, include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

## Context
Where are people coming from, and going to, throughout the day and over time.

> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround.

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## Client-side Calculations

> If the data from the API is not pre-calculated, please include all formulas here.
> e.g., `affordable = rent < monthlyIncome * 0.3`

## Data Sources

> All cards should trace back to their data origins. Include public links to those origins.
> In addition, any calculations on the source data should be described.

**Comment by code-farmhouse** [comment]
Related to Issue [47](https://github.com/hackoregon/civic/issues/47)
