### ISSUE TITLE
Match-lock component: Orbs within interface bounds

### ISSUE THREAD

**Issue by Dianna** [hackoregon/civic#765]
### Description

Orbs tend to hover around bottom and can be significantly off-screen

<img width="1440" alt="Screen Shot 2019-08-13 at 5 03 08 PM" src="https://user-images.githubusercontent.com/10056079/62985570-cf569400-bdec-11e9-84f1-69d3e91bae95.png">

### Expected result

Orbs should stay within the bounds of the interface and be more spread throughout

**Comment by lucastswick** [comment]
Addressed in https://github.com/hackoregon/civic/pull/855
