### ISSUE TITLE
Match-lock component: evenly spread orbs across frozen match-lock interface

### ISSUE THREAD

**Issue by Dianna** [hackoregon/civic#766]
<img width="1341" alt="Screen Shot 2019-08-13 at 5 11 41 PM" src="https://user-images.githubusercontent.com/10056079/62985726-70dde580-bded-11e9-8f89-6f23200dbf68.png">

There should be more orbs and they should barely overlap if at all

**Comment by lucastswick** [comment]
Dupe of #750
