### ISSUE TITLE
WIP -> Transportation Systems: Safety Hotline text mining

### ISSUE THREAD

**Issue by znmeb** [hackoregon/civic#77]
# Story Card Request

**Project:** Transportation Systems
**Card Title:** Safety Hotline Topic Model

## Description / Wireframe

The safety hotline dataset is a single CSV file with about 5000 rows. This card will show a topic model - an unsupervised learning technique to classify hotline entries by their subjects. In lieu of a wireframe we will supply visualizations and descriptive text; the finished story card can re-create the visualizations from the API we will build.

## Context
The results show what the major safety concerns are overall, and since the entries are date stamped and geotagged, there's a potential for joining a topic-tagged version of this dataset with other geotagged datasets, like crash data.

## Data Details (APIs)
This card will use an API that simply exports the dataset - the plan is to pre-compute the topic model and build an API to feed visualizations.

## Client-side Calculations
In the finished story there will be only text and visualizations - all the calculations will have been done and made available via an API. The "formulas" are quite complex; we'll have references and explanations in the story card.

## Data Sources
The PUDL safety hotline data is the only data source.

**Comment by christinatommeraasen** [comment]
I've got a few questions on this one:

**Comment by znmeb** [comment]
Action item for me: https://github.com/hackoregon/crash-data-wrangling/issues/7

**Comment by jaronheard** [comment]
Closing as part of post-2018 project season cleanup
