### ISSUE TITLE
Cards page — filter cards based on tags

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#775]
### What

Implement a page that can filter on tags based on these Figma wireframes (still in progress, see lower level)
https://www.figma.com/file/QcCCFHKofzRk0aI4fvr2a1/Civic-Landing-Page-Prototype?node-id=376%3A254

Will have standard header

Three main pieces:
[ResponsiveDrawer](https://material-ui.com/components/drawers/#responsive-drawer)
[NestedList](https://material-ui.com/components/lists/#nested-list)
A CivicCardLayout to display card previews based on filters

### Why

Navigating between cards and projects isn’t super intuitive.

### When

By demo day, Sept. 11

**Comment by fstorr** [comment]
Hey, @jaronheard 

This is a fix for the [nested list component](https://mo2x5.csb.app) not having the "expanded" and "collapsed" aria attributes:

```
<button aria-live="polite" id="tb1" aria-labelledby="btn-txt-1 exp" type="button"><span id="btn-txt-1">Yay buttn!</span></button>

<div id="exp" hidden>expanded</div>
<div id="clp" hidden>collapsed</div>

<script>

document.addEventListener("DOMContentLoaded", function(e){

  const btn = document.querySelector('#tb1');
  btn.addEventListener('click', function(){

    if(btn.getAttribute('aria-labelledby') === 'btn-txt-1 exp'){
      btn.setAttribute('aria-labelledby', 'btn-txt-1 clp');
    }
    else{
      btn.setAttribute('aria-labelledby', 'btn-txt-1 exp');
    }
  }, false);
});
```

Notes:

1. You'll need to add `aria-live="polite"` and `aria-labelledby` attributes to the button.
2. You'll need two hidden elements to contain the text "expanded" and "collapsed".
3. You'll need to wrap the text inside the button in a `<div>` or a `<span>` with a unique `id` attribute.
4. The `aria-labelledby` attribute on the button needs to reference the button itself and then one of the hidden elements. The order is important as that's the order a screen reader will announce the content.
5. Toggle the "expanded" and "collapsed" references in the button's `aria-labelledby` attribute as the user clicks on the button.
