### ISSUE TITLE
Demo card Links And Resources section has incorrectly-nested HTML

### ISSUE THREAD

**Issue by fstorr** [hackoregon/civic#789]
## Issue
The Links And Resources block on the demo card page has some incorrectly-written HTML, which doesn't conform to [WCAG 1.3.1's Info And Relationships criterion](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships):

```
<ul>
  <div>
    <h3>Studies and Papers</h3>
    <li><a href="…">…</a></li>
    <li><a href="…">…</a></li>
    <h3>Articles</h3>
    <li>…</li>
    <a class="css-dnbo9m">More<span…> </span></a>
  </div>
</ul>
```
## How to fix

`<ul>` and `<ol>` elements must only directly contain `<li>`, `<script>` or `<template>` elements, so the `<div>`, `<h3>`, and `<a>` elements need to come out of the `<ul>` element.

**Comment by jaronheard** [comment]
I think #791 fixed, but feel free to reopen if further issues.
