### ISSUE TITLE
The Shape of a Neighborhood

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#79]
- [ ] needs component
- [ ] needs API

# Story Card Request

Project: Neighborhood Development - Cross/Sectional
Title: A multi-dimensional representation of a neighborhood

## Description / Wireframe

This card represents neighborhood health as a shape in three dimensions, using different measures of neighborhood health from different teams.

Each neighborhood has a unique shape based on the characteristics of a neighborhood. This shape could be used in a small multiples layout, and could make an interesting poster.

1. Risk / Resiliance
2. Mobility / Equity
3. Affordable Housing Stock
4. Invested Voter Population
5. Violent Crime
6. Trees - count
7. Homeless sweeps
8. Education / schools

This abstract shape represents something about the each of these characteristics using some of the following attributes:
length, width, height, skew, color, texture, curvature, rotation, sound, etc...

Shapes could transform over time.

It allows for making visual connections and comparisons between different neighborhoods.

## Data Visualization / Design Concerns
This will require the construction of an artistic component for the component library that visualizes multiple scores as a unique visualization.

## Context
Data visualization can be artistic and inspirational. This card would represent something unique in our platform that makes neighborhood data into something visually compelling and inspire creative thought. Plus, it would slay on our demo day on the big screen.

## Data Details (APIs)

Each team would need to deliver a score from 0-100 in each different rating category by neighborhood. This is not in an API yet, and would require work by each team.

### How did we calculate this
- [ ] Description of calculation by each team

### See the source
- [ ] Link to API / data documentation on GitHub
- [ ] Link to original source data

**Comment by znmeb** [comment]
1. How many neighborhoods are there?
2. How big are they?
3. Do they extend beyond Portland city limits into the TriMet service area?
4. Has someone (for example, Portland State or another city) done something like this? I'm thinking of Portland Pulse but it's been a few years since I looked at that.
5. We don't have anything on schools this year, but my instinct tells me that's an important facet of a neighborhood.

**Comment by jaronheard** [comment]
Great questions - 
1. & 2. Neighborhood development has been working with the neighborhoods, and someone from that team might be able to answer that more precisely. I think there are about 50. @ballon3 
3. I think the neighborhoods that neighborhood development are working with are within Portland city limits?
4. Not sure, but the idea is that it would definitely be unique.
5. Agreed. I actually added it to the issue, we'll see if we get there.

**Comment by znmeb** [comment]
We at least have the building footprints and disaster resilience scores for the school buildings ;-)

**Comment by mckinneybock** [comment]
I'd like to talk more about what would go into a summary and/or composite score for a neighborhood. I'm worried that a single score for a neighborhood will be interpreted by the viewer as a livability score, and that we will lose some of the nuance of the data.

After talking with @christinatommeraasen, I wonder if a multidimensional representation of neighborhoods without making a composite score (along the lines of https://www.youtube.com/watch?v=nnjkHA8xvbI) might be a better approach. Representing this by neighborhood could potentially locate (in some multidimensional space) neighborhoods that are similar or dissimilar to each other wrt these 8 measures, rather than assigning a single score that would rank neighborhoods in a single way.

Happy to talk more about this.

Also, did you have in mind some sort of PCA (principal components analysis) or another method for neighborhood comparison?

Thanks!

**Comment by mckinneybock** [comment]
@NatalieRaketic

**Comment by jaronheard** [comment]
The idea behind this card is not that we would show aggregate score for each neighborhood, and rather that we would generate shapes that display the data more abstractly, with less value judgement.

**Comment by hassanshamim** [comment]
@jaronheard  is this still something we should be looking into or is this now superceded by the civic sandbox?

**Comment by jaronheard** [comment]
Shape of the data is approximately this. More updates to come.

`[{"neighborhood":"Bowmansville","data":[{"year":2010,"dimension1":54,"dimension2":50,"dimension3":44,"dimension4":4,"dimension5":2,"dimension6":88},{"year":2011,"dimension1":98,"dimension2":37,"dimension3":94,"dimension4":39,"dimension5":60,"dimension6":78},{"year":2012,"dimension1":85,"dimension2":2,"dimension3":94,"dimension4":75,"dimension5":74,"dimension6":23},{"year":2013,"dimension1":99,"dimension2":25,"dimension3":2,"dimension4":70,"dimension5":50,"dimension6":98},{"year":2014,"dimension1":46,"dimension2":62,"dimension3":87,"dimension4":93,"dimension5":19,"dimension6":8}]},{"neighborhood":"Chaparrito","data":[{"year":2010,"dimension1":86,"dimension2":26,"dimension3":42,"dimension4":3,"dimension5":49,"dimension6":78},{"year":2011,"dimension1":66,"dimension2":100,"dimension3":71,"dimension4":87,"dimension5":28,"dimension6":7},{"year":2012,"dimension1":92,"dimension2":99,"dimension3":62,"dimension4":79,"dimension5":74,"dimension6":83},{"year":2013,"dimension1":79,"dimension2":71,"dimension3":79,"dimension4":96,"dimension5":55,"dimension6":100},{"year":2014,"dimension1":25,"dimension2":44,"dimension3":56,"dimension4":73,"dimension5":96,"dimension6":32}]},{"neighborhood":"Crenshaw","data":[{"year":2010,"dimension1":29,"dimension2":5,"dimension3":30,"dimension4":77,"dimension5":34,"dimension6":90},{"year":2011,"dimension1":58,"dimension2":86,"dimension3":32,"dimension4":34,"dimension5":38,"dimension6":77},{"year":2012,"dimension1":34,"dimension2":61,"dimension3":4,"dimension4":62,"dimension5":45,"dimension6":63},{"year":2013,"dimension1":19,"dimension2":81,"dimension3":24,"dimension4":56,"dimension5":100,"dimension6":71},{"year":2014,"dimension1":52,"dimension2":24,"dimension3":23,"dimension4":46,"dimension5":42,"dimension6":75}]},{"neighborhood":"Baden","data":[{"year":2010,"dimension1":71,"dimension2":67,"dimension3":88,"dimension4":85,"dimension5":2,"dimension6":95},{"year":2011,"dimension1":24,"dimension2":9,"dimension3":29,"dimension4":73,"dimension5":80,"dimension6":11},{"year":2012,"dimension1":39,"dimension2":5,"dimension3":89,"dimension4":100,"dimension5":0,"dimension6":54},{"year":2013,"dimension1":21,"dimension2":30,"dimension3":51,"dimension4":93,"dimension5":89,"dimension6":29},{"year":2014,"dimension1":48,"dimension2":61,"dimension3":0,"dimension4":25,"dimension5":5,"dimension6":7}]},{"neighborhood":"Cade","data":[{"year":2010,"dimension1":93,"dimension2":23,"dimension3":97,"dimension4":55,"dimension5":3,"dimension6":53},{"year":2011,"dimension1":56,"dimension2":54,"dimension3":21,"dimension4":87,"dimension5":84,"dimension6":11},{"year":2012,"dimension1":3,"dimension2":26,"dimension3":37,"dimension4":62,"dimension5":73,"dimension6":99},{"year":2013,"dimension1":34,"dimension2":60,"dimension3":61,"dimension4":35,"dimension5":94,"dimension6":41},{"year":2014,"dimension1":72,"dimension2":35,"dimension3":51,"dimension4":90,"dimension5":95,"dimension6":60}]}]`

**Comment by nam20485** [comment]
@jaronheard What specifically is blocking this progress? Is there anything I can do as the disaster-resilience backend develop (or @Moss Drake as our DB developer?

**Comment by Dianna** [comment]
@jaronheard https://github.com/orgs/hackoregon/projects/9

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
