### ISSUE TITLE
WIP -> Neighborhood or Component? - Interactive Map

### ISSUE THREAD

**Issue by LMorgan-veraly** [hackoregon/civic#81]
# Story Card Request

**Project: Neighborhood possibly a component for wider use**
**Card Title: Interactive Map**

## Description / Wireframe

Like plotpdx.org but better. We would like deltas, change over time, heat map change over time. Includes time sequence dial.

![image](https://user-images.githubusercontent.com/34141399/39611642-1091daf0-4f0e-11e8-8366-1fc68c62a4a0.png)

Precision - Start with annual data but seasonal or more frequent would be useful to see data over shorter intervals

> Also include a link to a __Figma design__ if you have one. ??? (Brett Heckman)

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here.

Different than plotpdx need better choose your own adventure, not scroll down but choose area of interest and then see that. We want all the neighborhood data and story cards to be able to be accessed from the interactive map. (Also possibly other teams data accessed through map also, hence entry as component than just for neighborhood team.)

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)

API needs to deliver the geographies, locks on Portland. First response is the neighborhood geojson. Then API deliver of more data sets. User select field, ie crime, income, trees... then when they click on neighborhood and the output then is the info for that neighborhood filtered to the field of inerest. (Ryan Brown)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## About this data
View of a lot of data, with many potential applications.

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
Neighborhood GitHub
>Link to original source data
Neighborhood spreadsheet has info about source data -

**Comment by hassanshamim** [comment]
@LMorgan-veraly This seems pretty high-level.  Is this covered by the additional issues/cards we've created so far?

**Comment by LMorgan-veraly** [comment]
This is covered by the Sandbox, closing.
