### ISSUE TITLE
WIP->Safety hotline and crash data overlay

### ISSUE THREAD

**Issue by gouldc2** [hackoregon/civic#84]
# Story Card Request

Transportation
Safety hotline and crash data overlay

## Description / Wireframe

> Include a detailed description and/or image that describes your story or visualization using
> the data described below. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> If you have a wireframe, include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

Show the locations of the safety concerns and the ODOT crash data on a map. Would be good if the points expanded to show the whole text as you clicked on them. Might be possible to run some analysis on how many areas have both crashes and safety concerns. 

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.
Citizens and even PBOT employees have a hard time tracking these complaints and referencing them for future improvements. Showing this data openly could keep the city more accountable for unsafe zones, and could "crowdsource" solutions, since neighbors usually know their own streets best. In the future, more people might find this tool valuable and can be useful for PBOT to stop crashes before they happen.

## Data Details (APIs)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.
Think we need to build an API. 

### How did we calculate this
>Description or link to GitHub description of data methodology
Need to combine XY locations from the PUDL csv file with the ODOT crash data. 

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by gouldc2** [comment]
#

**Comment by znmeb** [comment]
Action item for me: https://github.com/hackoregon/crash-data-wrangling/issues/7

**Comment by jaronheard** [comment]
This is also something that fits within the framework of the Sandbox for the map component. Labelling as such.

**Comment by jaronheard** [comment]
This is a layer in the Civic Sandbox now!
