### ISSUE TITLE
Magnitude of Urban Campsite Sweeps in Portland

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/civic#85]
# Story Card Request

**Project: Neighborhoods**
**Card Title: Campsite Sweeps over Time**

## Description / Wireframe

This card is a simple bar chart of campsite clean-ups over time, aggregated by week or by month. This card will be linked to a map representation of the point data over time as well and should be one summary in a more complete exploration of campsite sweeps from 10/2016-present (Issue #86 , Issue #87).

![image](https://user-images.githubusercontent.com/37488734/39667352-ac105db6-5068-11e8-9475-2fabf4e2e7bb.png)

![image](https://user-images.githubusercontent.com/37488734/39667357-ba754196-5068-11e8-8e00-73198e6bd285.png)

## Data Visualization / Design Concerns
At the moment, this card is relatively simple & it would be best bundled with other aggregations of the sweeps data, and/or closely linked to the interactive map of sweeps. 

## Context
This particular dataset has not been visualized or summarized by the city; currently a PDF report of clean-ups is posted online each week. The set of cards representing basic summaries of this dataset will be the first time anyone looks at this dataset as a whole. At the moment, representations are simple bar charts linked to an interactive map of point data over time, but suggestions for the overall structure of this set of cards would be welcome.

## Data Details (APIs)

Here is a link to an R notebook that shows the params & aggregation: https://drive.google.com/drive/u/0/folders/1-GMj8RvYb3PONTIVspmc5BMGO-mbSyWV

datasets:
 - camp_cleanups
 - neighborhoods

spatial join on:
- neighborhoods.geom
- camp_cleanups.geom

variables: 
- reportdate
- count of another column (e.g. lat or location) 

## About this data

Weekly reports of campsite sweeps are posted (PDF) to the Homelessness Toolkit (https://www.portlandoregon.gov/toolkit/69885), through One Point of Contact. The data reports which areas were cleaned up in any given week from October 2016-present, and reports plans for future sweeps in the upcoming week. A time-aware map of campsite reports is also available, and this dataset is also available to Hack OR (in progress; not coded for lat-long at this time): http://pdx.maps.arcgis.com/apps/TimeAware/index.html?appid=ac6a6abf1092482190984a5df9dfacb0

The text was extracted from these PDFs and geocoded (first pass through Google Maps API, second pass by hand). Ask Katy for a methods report (in progress).

### How did we calculate this
Methods report for dataset in progress; aggregation was calculated in R (see .Rmd file to reproduce).

### See the source
https://www.portlandoregon.gov/toolkit/71771

**Comment by jaronheard** [comment]
Great card! Thank you for the detail that you provided. I think that the months chart over time is a really compelling one.

Thinking about this high level again - do we have data on the number of people being moved that could be incorporated into this chart? This chart is interesting as is, but for me leads to a follow question:

Does the variations in the number of campsites relate to the number of people moved? Sweeping a campsite could indicate moving a large group of people, or just a few people.

If not, think we can work with this, but if we do, a further breakdown might be worthwhile.

**Comment by mckinneybock** [comment]
Unfortunately, these reports don't have numbers on people moved. There is another dataset that Hassan is working to geocode that does have estimates of campsite size, but those are only for campsite reports from the public (and estimates by the public on campsite size).

What we can do is cross the report date from the sweeps dataset with any matching reports from the public on/around those dates, and estimate campsite size from the public's reports that match the campsite sweep that happened.

It wouldn't be exact, but I bet we could estimate sizes. 

Another thing we could do is map the campsite reports OVER the campsite sweeps (another interesting card in and of itself), and then have some kind of representation of campsite report magnitude only from the reports, but visually crossed with sweeps to also try and visually estimate how many people might have been moved.

I wish we had those numbers! I don't think they are releasing them, if they record them at all.

**Comment by mckinneybock** [comment]
Just to clarify, we have two datasets available to us. The first is the one I reference here, "campsite sweeps", that has the actual locations that were swept by week/by month. The second data set, "public campsite reports", is the data from the online reporting system that the public can submit reports of campsites to. That second dataset has XY coordinates, and we are converting htem to lat-long so we can map them right now. It also has more details about the campsite, like size/# of people, whether there are children, in a vehicle or a tent, etc. It does *not* contain information about whether or not the PPB followed up on that campsite report and subsequently swept the camp. That is what we'd have to estimate/recreate by looking across both of those datasets. Hope that's helpeful!

**Comment by jaronheard** [comment]
I think that this basic chart of sweeps by month is something useful that we would like to show, and once API details are available, we can build it. 

Interested in looking again at crossing data-sets - but think that the bar chart component is ready to be built once we have API details.

- [ ] API details

**Comment by mckinneybock** [comment]
Great, thanks!

 I should add here that I'd like to re-review the first few months of reports. At that time, reporting was slightly less consistent, so I think part of the increase from 10/2016-Feb 2017 (or so) was due to more accurate reporting than an actual increase. The reporting after that seems more consistent, so any increase is more likely due to an actual increase. BUT: I'm following up on that this week and next, so I'll let you know if it's best to cut those first months or not.

**Comment by hassanshamim** [comment]
@jaronheard 

This endpoint is complete:

API endpoints are available here: 

https://neighborhoods-2018.herokuapp.com/neighborhood-development/camp_sweeps/bytime?timeframe=month

https://neighborhoods-2018.herokuapp.com/neighborhood-development/camp_sweeps/bytime?timeframe=week

**Comment by hassanshamim** [comment]
Proper URLs are:

http://service.civicpdx.org/neighborhood-development/api/camp_sweeps/bytime?timeframe=week
and 
http://service.civicpdx.org/neighborhood-development/api/camp_sweeps/bytime?timeframe=month

**Comment by jaronheard** [comment]
This is ready to build. 🙌🙌🙌
