### ISSUE TITLE
Create a new-component hygen template

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#854]
### What

Similar to the yarn card and yarn new-package scripts, create a Hygen generator to set up a new component and add it to Storybook

`yarn new-component`
```bash
What is the name of your new component?
tag
```

Should create a minimal implementation of the following files and all imports necessary:
Component file: component-library/src/Tag/Tag.js
Story file: component-library/stories/Tag.story.js
Story notes: component-library/stories/tag.notes.md

The component should show up in Storybook, and include a show Standard and Custom stories. The Custom story should show the usage of a knob. Should show up under `Component Lib|Experimental/Tag`

### Why

To speed up creation of components.

### When

ASAP

**Comment by Dianna** [comment]
Resolved by #859
