### ISSUE TITLE
Neighborhoods: Campsite Sweeps by Neighborhood

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/civic#86]
# Story Card Request

**Project: Neighborhoods**
**Card Title: Campsite Sweeps by Neighborhood**

## Description / Wireframe

This card is a simple bar chart of total campsite clean-ups by neighborhood from 10/2016-present.  This card will be linked to a map representation of the point data over time as well and should be one summary in a more complete exploration of campsite sweeps (Issue #85 , Issue #87).

The chart provided filters all neighborhoods in Portland to those that experience more than 4 sweeps over this period of time for purposes of this visualization. There is much more data by all neighborhoods available in the aggregated dataset (see below). 

![image](https://user-images.githubusercontent.com/37488734/39667713-02da7f70-5071-11e8-835d-1902e5894d2a.png)

## Data Visualization / Design Concerns
At the moment, this card is relatively simple & it would be best bundled with other aggregations of the sweeps data, and/or closely linked to the interactive map of sweeps.

Also, not all neighborhoods are represented in this visualization; a more complete visualization could include all other neighborhoods with less than 4 sweeps over the time period.

An exploration by neighborhood AND over time would be nice; this may be best represented on a map visualization that should be linked to this card.

## Context
This particular dataset has not been visualized or summarized by the city; currently a PDF report of clean-ups is posted online each week. The set of cards representing basic summaries of this dataset will be the first time anyone looks at this dataset as a whole. At the moment, representations are simple bar charts linked to an interactive map of point data over time, but suggestions for the overall structure of this set of cards would be welcome.

Certain neighborhoods have been very vocal to the city about how the homeless are being treated in their community. For example, neighbors in Lents have reported that they are experiencing high volumes of houseless. This data represents all reported sweeps (by the city/PPB) over time to show which neighborhoods/locations quantitatively have had more sweeps than others.

## Data Details (APIs)

Here is a link to an R notebook that shows the params & aggregation: 
https://drive.google.com/drive/u/0/folders/1gLYxkbOjjMlFKVkBg05riIPfu8RN-8QZ

Data is in the database that has been developed by the neighborhoods team.

datasets:
- camp_cleanups
- neighborhoods

spatial join on:
- neighborhoods.geom
- camp_cleanups.geom

variables:
- name
- count of another column (e.g. lat or location)

## About this data
Weekly reports of campsite sweeps are posted (PDF) to the Homelessness Toolkit (https://www.portlandoregon.gov/toolkit/69885), through One Point of Contact. The data reports which areas were cleaned up in any given week from October 2016-present, and reports plans for future sweeps in the upcoming week. A time-aware map of campsite reports is also available, and this dataset is also available to Hack OR (in progress; not coded for lat-long at this time): http://pdx.maps.arcgis.com/apps/TimeAware/index.html?appid=ac6a6abf1092482190984a5df9dfacb0

The text was extracted from these PDFs and geocoded (first pass through Google Maps API, second pass by hand). Ask Katy for a methods report (in progress).

### How did we calculate this
Methods report for dataset in progress; aggregation was calculated in R (see .Rmd file to reproduce).

### See the source

https://www.portlandoregon.gov/toolkit/71771

**Comment by jaronheard** [comment]
I think this card is pretty well fleshed out, and I'm excited to see it built, but I've been slightly struggling with this card and a few other cards on a platform level from a data visualization perspective.

That questions is how to show category data with lots of categories - more than 10-20 - there are a lot of neighborhoods shown in this bar graph.

This is actually a thing I've been thinking about for other cards as well - what is the best way to do this? One approach is using small multiples and filtering - showing information only about the top X neighborhoods in the initial view, and allowing users to filter for the neighborhood.

@christinatommeraasen this is something I would be interested in talking to you about.

**Comment by mckinneybock** [comment]
I would support showing fewer neighborhoods (those will more than 5 occurrences total over time, perhaps). Maybe there is a way to cluster these neighborhoods; I'll think on this (i.e. have a set of bar charts of those most affected vs. least affected?). 

I like the filter suggestion; letting users interact with the neighborhoods to only show ranks and/or neighborhoods of interest.

Additionally, this type of aggregate is informative in a bar chart but can also be represented on a map as that holds more information. We do lose the rank of magnitude/direct comparison of those neighborhoods most affected, and I think the most important information are the highest ranked neighborhoods in this particular viz.

**Comment by LMorgan-veraly** [comment]
@hassanshamim @accua start here with API... IMS Neighborhood Demographics is the census data vs the campsite sweeps

**Comment by hassanshamim** [comment]
Questions we (backend) would like answered to deliver you your data
- What is an example format of the data you are expecting? (see below for trivial example)
- What keys or values change (aka would you like to adjust)?
        - CHANGE: year, neighborhood, race
        - SAME: total, percentages, descriptions, etc
- What are we AGGREGATING by?
        - will generally be a shape/boundry (neighborhood, block group, tablet?)
        - or a time: year, month, etc.

example data:
```json
{
  "neighborhoods": [
    {
      "name": "Buckman",
      "geometry": "geometry point or polygon data... etc",
      "total": 320234,
      "percentage of some value I care about": 32.13
    },
    {
      "name": "Richmond",
      "geometry": "geometry point or polygon data... etc",
      "total": 1234,
      "percentage of some value I care about": 11.82
    }
  ]
}
```

**Comment by hassanshamim** [comment]
@jaronheard 

Current endpoint: https://neighborhoods-2018.herokuapp.com/neighborhood-development/camp_sweeps/by_neighborhood

Currently limits to neighborhoods with >= 4 sweeps as described, can be tweaked if you would like @mckinneybock

**Comment by mckinneybock** [comment]
This will be available in sandbox, I believe, but it's not going in the story collection. So I'm closing!
