### ISSUE TITLE
Neighborhoods: Map of Campsite Sweeps (Point Data over Time)

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/civic#87]
- [x] Animate map over time
- [x] Needs API that can return sweeps by time

# Story Card Request

**Project: Neighborhoods**
**Card Title: Map of Campsite Sweeps**

## Description / Wireframe

See Issue #102 - these two cards have been combined into one Sandbox card for the neighborhoods story collection (as of 6/14/18).

Interactive Map of campsite sweeps (link to Issue #81) as part of a greater interactive map representing data about neighborhoods. Represent each sweep as a point on the map; have a dial to represent the data by week (this is the most granular option with this dataset), by month, by 6 months, or by 12 months. A scrolling window would be nice (i.e. any 12-month window would be available). 

In particular, an independent map or visualization with this data would be potentially compelling as a 3D graphic map with quantity of campsite sweeps by month changing over time, perhaps by census block. I'm thinking the style of a relief map, with counts by census block or neighborhood raising or lowering based on the time window & quantity.  (This may be another independent card; I'd be happy to split this off into another issue if so).

A fixed movement through this visualization (either by week or by month) to show the movement of houseless camps and un-housed people over time would visually illustrate how often/frequency of how campsites are displaced. For example, several campsites are swept each week in the same location, and a map visualization that captures this would show frequent movement of sites (and people) over time. 

I don't have a map visualization of the point data right now, but can provide a screenshot if needed. Aggregation over neighborhood is available in Issue #85/Issue #86, and census block can be done using the same methods over the census block polygon in the neighborhoods database. There are lat/long values for the campsite sweeps (~1800) over the time period available (10/2016-present).

## Data Visualization / Design Concerns
- Showing the counts of campsites per week visually, to represent how many sweeps per week/month are occurring over time, via a 3D curved topography (raised where there is a campsite or aggregate of campsites over census block). 
- Visualizing locations/hot spots where lots of campsites are located and frequently swept would show up as an undulation (i.e. from one week to the next, the count would rise, then fall, then rise again). This would require more than just mapping counts, but some sort of delta between weeks to illustrate a quantity of campsites/presence of a campsite, followed by a 'sweep' of that site and then another rise to show that the campsite returned. I'd be happy to chat more in comments.
- Is there an appropriate type of marker that would represent a campsite to show human movement/displacement rather than a point on a map? I'd like to discuss more to ensure that identifying visualizations don't convey myths about homelessness, but at the same time humanize what is happening each week with the map. 

## Context
This particular dataset has not been visualized or summarized by the city; currently a PDF report of clean-ups is posted online each week. The set of cards representing basic summaries of this dataset will be the first time anyone looks at this dataset as a whole. At the moment, representations are simple bar charts linked to an interactive map of point data over time, but suggestions for the overall structure of this set of cards would be welcome.

## Data Details (APIs)

Data is in the database that has been developed by the neighborhoods team.

datasets:
- camp_cleanups
- neighborhoods

(potential) spatial join on:
- neighborhoods
- census blocks 

variables:
- reportdate
- lat
- long

## About this data
Weekly reports of campsite sweeps are posted (PDF) to the Homelessness Toolkit (https://www.portlandoregon.gov/toolkit/69885), through One Point of Contact. The data reports which areas were cleaned up in any given week from October 2016-present, and reports plans for future sweeps in the upcoming week. A time-aware map of campsite reports is also available, and this dataset is also available to Hack OR (in progress; not coded for lat-long at this time): http://pdx.maps.arcgis.com/apps/TimeAware/index.html?appid=ac6a6abf1092482190984a5df9dfacb0

The text was extracted from these PDFs and geocoded (first pass through Google Maps API, second pass by hand). Ask Katy for a methods report (in progress).

### How did we calculate this
Methods report for dataset in progress; aggregation was calculated in R (see .Rmd file to reproduce).

### See the source

https://www.portlandoregon.gov/toolkit/71771

**Comment by christinatommeraasen** [comment]
This one can be absorbed by the sandbox concept, likely as a layer. There won't be any analysis associated.

**Comment by hassanshamim** [comment]
API for raw sweep data is available here: https://neighborhoods-2018.herokuapp.com/neighborhood-development/camp_sweeps

Right now it's just returning 10 points at a time, we can absolutely increase this.  There are 1834 recorded sweeps in total.

@AraOshin we can discuss how to get this data across more efficiently.

**Comment by mckinneybock** [comment]
There will be another 400 or so point added, and some more fixes to the 1834 current points. Structure of the data is identical; just adding the last 6 weeks of data. I'll get that to you ASAP, goal EOD Monday 6/4.

**Comment by hassanshamim** [comment]
updated URL: http://service.civicpdx.org/neighborhood-development/api/camp_sweeps

**Comment by jaronheard** [comment]
This API is currently down - please indicate when available again.

**Comment by AraOshin** [comment]
Is this card and discussion no longer about the sandbox layer with this data? If so, carry on! 

If this seems to be about sandbox then I think there are some crossed wires happening. 

The sandbox endpoint is http://service.civicpdx.org/neighborhood-development/sandbox/slides/campsweeps/ and it is working. 

Front end devs working on sandbox would be hitting that endpoint from the central sandbox api.

**Comment by mckinneybock** [comment]
My wires were crossed! Or, to be clear, I had my tabs crossed. Thanks for the clarification!

**Comment by jaronheard** [comment]
We are not showing this in the Sandbox - it is a map within a card - but we will be using the Sandbox endpoint.

Here's the priorities for front-end:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/7065695/41511978-7e4adf24-7236-11e8-8607-29b55a546d7b.png">

**Comment by AraOshin** [comment]
@jaronheard This dataset *is* getting used in a sandbox package. 

For the non sandbox card, I hope someone else (@hassanshamim) is on board writing that endpoint because for now the sandbox only has yearly filtering, though I do plan to add monthly for the sandbox layer as soon as apis are back up and running.

**Comment by hassanshamim** [comment]
API is fixed now. @jaronheard this should be `api ready`

http://service.civicpdx.org/neighborhood-development/api/camp_sweeps?limit=3000 to get all the data in one go (about 400K in size).  It's sorted by date ascending.  The date field is `reportdate` in YYYY-MM-DD format.

**Comment by mckinneybock** [comment]
The data (points) was showing up last night, but is no longer showing in the staging area.

**Comment by jaronheard** [comment]
#294 implemented - follow-up with additional issues for improvements.
