### ISSUE TITLE
No obvious way to get to full card layout from classic card layout

### ISSUE THREAD

**Issue by Dianna** [hackoregon/civic#885]
Check out https://civicplatform.org/2019/template
Each card has significantly more data than is shown. To see it, you need to click share and then paste it in your browser and go. No one will no to do that. We should have a link somewhere to open the full card in another tab or something simple like that

**Comment by jaronheard** [comment]
We can just link from the title -- so the highted below will be a link in the CivicCardClassic layout

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/7065695/64891146-086d6880-d626-11e9-881c-54e57258c9c4.png">

**Comment by jaronheard** [comment]
Closed via #1017
