### ISSUE TITLE
WIP -> Bus route by stop type

### ISSUE THREAD

**Issue by gouldc2** [hackoregon/civic#89]
# Story Card Request

Transportation
Bus route time by moving type

## Description / Wireframe

> Include a detailed description and/or image that describes your story or visualization using
> the data described below. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> If you have a wireframe, include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

Parse each route (end to end, or by smaller segments) to show the percentage time for different moving codes (stopped at bus stop, stopped not at a bus stop, moving)
Example on slide 2: 
https://docs.google.com/presentation/d/1QJ5SfxQwRlPaHuzACUmBwOEiuwwTC1P24jDz4SmKxms/edit#slide=id.g3873888d06_0_77

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.
There are different solutions to target different categories. Good for before and after on how effective a treatment was. 

## Data Details (APIs)

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround. Also include any calculations needed for the
> data recieved from the API

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.
Use through the congestion dataset init_veh_stop_data

### How did we calculate this
>Description or link to GitHub description of data methodology
use stop type codes. Not sure how to determine cut off points.

### See the source
>Link to API / data documentation on GitHub
>Link to original source data

**Comment by gouldc2** [comment]
https://drive.google.com/file/d/1XvIxzwFpfzbInQvxGSUDyuM7S7ooqEl2/view?usp=sharing 

![route_by_moving_type](https://user-images.githubusercontent.com/13370745/39678593-59da3288-5144-11e8-85b6-77ff48583ce8.JPG)

**Comment by jaronheard** [comment]
I'd like this to use our horizontal bar chart component, instead of a stacked 100% bar. I think that once the API details are available, this component can be built. 

I could envision this as a part of a card that shows multiple statistics about a bus route.

- [ ] API details

**Comment by jaronheard** [comment]
Data science work to be done:

For each route - calculate the following variables for the whole time period
stopped not at bus stop
at bus stop
moving
And put in a table
