### ISSUE TITLE
Hold - Neighborhoods: Parks Data/Green Spaces & Campsite Reports

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/civic#99]
# Story Card Request

**Project: Neighborhoods**
**Card Title: Parks, Trails, and Green Spaces & Locations of Campsites**

## Description / Wireframe

This data is not visualized yet, as the Campsite Reports are still being geocoded. A map of green spaces crossed with reports of campsites, to explore where people are camping in Portland. 

## Data Visualization / Design Concerns
- The data is in preparation.

## Context
More thought needs to be put into why this question is interesting/what the data tells us. This is an exploration of whether people are camping in green spaces or in other areas (and whether the parks vs. other areas are being swept more frequently). This could give another perspective on how often people are being forced to move, and whether choice of campsite allows people to stay longer in one place (or not).

## Data Details (APIs)
- Data is being geocoded, and will be put into the Neighborhoods database when complete.
- Parks data is being analyzed (in process) as well.

### How did we calculate this
>Description or link to GitHub description of data methodology
To be posted.

### See the source
>Link to API / data documentation on GitHub
>Link to original source data
To be reported.

**Comment by hassanshamim** [comment]
@mckinneybock So is the intention here to enumerate the 'hot spots' for sweeps?  I have a tentative query with some results:

query (more for my reference later)

```sql
SELECT p.name, count(c.id) as num_sweeps, st_astext(p.geom)
 	FROM parks as p
	INNER JOIN camp_sweeps as c ON st_contains(p.geom, c.geom)
	GROUP BY p.name, p.geom
```

**Comment by mckinneybock** [comment]
Hey! There's a hold on this card, as the analysis likely won't proceed. The intention was to look at campsite reports in green spaces vs. urban spaces, but I think we won't be representing that at this point. Thanks for taking a look - I'm here for donut day if you want to go over the other issues.

**Comment by LMorgan-veraly** [comment]
@mckinneybock - let's look at the sandbox package for sweeps/reports. It may cover this, or I can adjust package per your thoughts.

**Comment by mckinneybock** [comment]
Not going in to the story collection! I believe these datasets will be in the neighborhood sandbox package - see Lynn's spreadsheet for details.
